{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.Impl.OpenGL2 where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types

#include "dcimgui_impl_opengl2.h"

-- functions

-- C: bool ImGui_ImplOpenGL2_CreateDeviceObjects()
foreign import capi unsafe "dcimgui_impl_opengl2.h cImGui_ImplOpenGL2_CreateDeviceObjects"
  cImGui_ImplOpenGL2_CreateDeviceObjects :: IO CBool
-- C: void ImGui_ImplOpenGL2_DestroyDeviceObjects()
foreign import capi unsafe "dcimgui_impl_opengl2.h cImGui_ImplOpenGL2_DestroyDeviceObjects"
  cImGui_ImplOpenGL2_DestroyDeviceObjects :: IO ()
-- C: bool ImGui_ImplOpenGL2_Init()
foreign import capi unsafe "dcimgui_impl_opengl2.h cImGui_ImplOpenGL2_Init"
  cImGui_ImplOpenGL2_Init :: IO CBool
-- C: void ImGui_ImplOpenGL2_NewFrame()
foreign import capi unsafe "dcimgui_impl_opengl2.h cImGui_ImplOpenGL2_NewFrame"
  cImGui_ImplOpenGL2_NewFrame :: IO ()
-- C: void ImGui_ImplOpenGL2_RenderDrawData(ImDrawData* draw_data)
foreign import capi unsafe "dcimgui_impl_opengl2.h cImGui_ImplOpenGL2_RenderDrawData"
  cImGui_ImplOpenGL2_RenderDrawData :: (Ptr ImDrawData) -> IO ()
-- C: void ImGui_ImplOpenGL2_Shutdown()
foreign import capi unsafe "dcimgui_impl_opengl2.h cImGui_ImplOpenGL2_Shutdown"
  cImGui_ImplOpenGL2_Shutdown :: IO ()
-- C: void ImGui_ImplOpenGL2_UpdateTexture(ImTextureData* tex)
foreign import capi unsafe "dcimgui_impl_opengl2.h cImGui_ImplOpenGL2_UpdateTexture"
  cImGui_ImplOpenGL2_UpdateTexture :: (Ptr ImTextureData) -> IO ()
