{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.Impl.SDL3 where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types
import DearImGui.Raw.Impl.SDL3.Types

#include "dcimgui_impl_sdl3.h"

-- functions

-- C: bool ImGui_ImplSDL3_InitForD3D(SDL_Window* window)
foreign import capi unsafe "dcimgui_impl_sdl3.h cImGui_ImplSDL3_InitForD3D"
  cImGui_ImplSDL3_InitForD3D :: (Ptr SDL_Window) -> IO CBool
-- C: bool ImGui_ImplSDL3_InitForMetal(SDL_Window* window)
foreign import capi unsafe "dcimgui_impl_sdl3.h cImGui_ImplSDL3_InitForMetal"
  cImGui_ImplSDL3_InitForMetal :: (Ptr SDL_Window) -> IO CBool
-- C: bool ImGui_ImplSDL3_InitForOpenGL(SDL_Window* window, void* sdl_gl_context)
foreign import capi unsafe "dcimgui_impl_sdl3.h cImGui_ImplSDL3_InitForOpenGL"
  cImGui_ImplSDL3_InitForOpenGL :: (Ptr SDL_Window) -> (Ptr ()) -> IO CBool
-- C: bool ImGui_ImplSDL3_InitForOther(SDL_Window* window)
foreign import capi unsafe "dcimgui_impl_sdl3.h cImGui_ImplSDL3_InitForOther"
  cImGui_ImplSDL3_InitForOther :: (Ptr SDL_Window) -> IO CBool
-- C: bool ImGui_ImplSDL3_InitForSDLGPU(SDL_Window* window)
foreign import capi unsafe "dcimgui_impl_sdl3.h cImGui_ImplSDL3_InitForSDLGPU"
  cImGui_ImplSDL3_InitForSDLGPU :: (Ptr SDL_Window) -> IO CBool
-- C: bool ImGui_ImplSDL3_InitForSDLRenderer(SDL_Window* window, SDL_Renderer* renderer)
foreign import capi unsafe "dcimgui_impl_sdl3.h cImGui_ImplSDL3_InitForSDLRenderer"
  cImGui_ImplSDL3_InitForSDLRenderer :: (Ptr SDL_Window) -> (Ptr SDL_Renderer) -> IO CBool
-- C: bool ImGui_ImplSDL3_InitForVulkan(SDL_Window* window)
foreign import capi unsafe "dcimgui_impl_sdl3.h cImGui_ImplSDL3_InitForVulkan"
  cImGui_ImplSDL3_InitForVulkan :: (Ptr SDL_Window) -> IO CBool
-- C: void ImGui_ImplSDL3_NewFrame()
foreign import capi unsafe "dcimgui_impl_sdl3.h cImGui_ImplSDL3_NewFrame"
  cImGui_ImplSDL3_NewFrame :: IO ()
-- C: bool ImGui_ImplSDL3_ProcessEvent(const SDL_Event* event)
foreign import capi unsafe "dcimgui_impl_sdl3.h cImGui_ImplSDL3_ProcessEvent"
  cImGui_ImplSDL3_ProcessEvent :: (Ptr SDL_Event) -> IO CBool
-- C: void ImGui_ImplSDL3_SetGamepadMode(ImGui_ImplSDL3_GamepadMode mode, SDL_Gamepad** manual_gamepads_array, int manual_gamepads_count)
foreign import capi unsafe "dcimgui_impl_sdl3.h cImGui_ImplSDL3_SetGamepadModeEx"
  cImGui_ImplSDL3_SetGamepadModeEx :: ImGui_ImplSDL3_GamepadMode -> (Ptr (Ptr SDL_Gamepad)) -> CInt -> IO ()
-- C: void ImGui_ImplSDL3_SetMouseCaptureMode(ImGui_ImplSDL3_MouseCaptureMode mode)
foreign import capi unsafe "dcimgui_impl_sdl3.h cImGui_ImplSDL3_SetMouseCaptureMode"
  cImGui_ImplSDL3_SetMouseCaptureMode :: ImGui_ImplSDL3_MouseCaptureMode -> IO ()
-- C: void ImGui_ImplSDL3_Shutdown()
foreign import capi unsafe "dcimgui_impl_sdl3.h cImGui_ImplSDL3_Shutdown"
  cImGui_ImplSDL3_Shutdown :: IO ()
