{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.Impl.SDLGPU3 where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types
import DearImGui.Raw.Impl.SDLGPU3.Types

#include "dcimgui_impl_sdlgpu3.h"

-- functions

-- C: void ImGui_ImplSDLGPU3_CreateDeviceObjects()
foreign import capi unsafe "dcimgui_impl_sdlgpu3.h cImGui_ImplSDLGPU3_CreateDeviceObjects"
  cImGui_ImplSDLGPU3_CreateDeviceObjects :: IO ()
-- C: void ImGui_ImplSDLGPU3_DestroyDeviceObjects()
foreign import capi unsafe "dcimgui_impl_sdlgpu3.h cImGui_ImplSDLGPU3_DestroyDeviceObjects"
  cImGui_ImplSDLGPU3_DestroyDeviceObjects :: IO ()
-- C: bool ImGui_ImplSDLGPU3_Init(ImGui_ImplSDLGPU3_InitInfo* info)
foreign import capi unsafe "dcimgui_impl_sdlgpu3.h cImGui_ImplSDLGPU3_Init"
  cImGui_ImplSDLGPU3_Init :: (Ptr ImGui_ImplSDLGPU3_InitInfo) -> IO CBool
-- C: void ImGui_ImplSDLGPU3_NewFrame()
foreign import capi unsafe "dcimgui_impl_sdlgpu3.h cImGui_ImplSDLGPU3_NewFrame"
  cImGui_ImplSDLGPU3_NewFrame :: IO ()
-- C: void ImGui_ImplSDLGPU3_PrepareDrawData(ImDrawData* draw_data, SDL_GPUCommandBuffer* command_buffer)
foreign import capi unsafe "dcimgui_impl_sdlgpu3.h cImGui_ImplSDLGPU3_PrepareDrawData"
  cImGui_ImplSDLGPU3_PrepareDrawData :: (Ptr ImDrawData) -> (Ptr SDL_GPUCommandBuffer) -> IO ()
-- C: void ImGui_ImplSDLGPU3_RenderDrawData(ImDrawData* draw_data, SDL_GPUCommandBuffer* command_buffer, SDL_GPURenderPass* render_pass, SDL_GPUGraphicsPipeline* pipeline)
foreign import capi unsafe "dcimgui_impl_sdlgpu3.h cImGui_ImplSDLGPU3_RenderDrawDataEx"
  cImGui_ImplSDLGPU3_RenderDrawDataEx :: (Ptr ImDrawData) -> (Ptr SDL_GPUCommandBuffer) -> (Ptr SDL_GPURenderPass) -> (Ptr SDL_GPUGraphicsPipeline) -> IO ()
-- C: void ImGui_ImplSDLGPU3_Shutdown()
foreign import capi unsafe "dcimgui_impl_sdlgpu3.h cImGui_ImplSDLGPU3_Shutdown"
  cImGui_ImplSDLGPU3_Shutdown :: IO ()
-- C: void ImGui_ImplSDLGPU3_UpdateTexture(ImTextureData* tex)
foreign import capi unsafe "dcimgui_impl_sdlgpu3.h cImGui_ImplSDLGPU3_UpdateTexture"
  cImGui_ImplSDLGPU3_UpdateTexture :: (Ptr ImTextureData) -> IO ()
