{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.Impl.SDLRenderer3.Types where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types

#include "dcimgui_impl_sdlrenderer3.h"

-- structs (opaque)

data ImGui_ImplSDLRenderer3_RenderState
instance Storable ImGui_ImplSDLRenderer3_RenderState where
  sizeOf _    = #{size ImGui_ImplSDLRenderer3_RenderState}
  alignment _ = #{alignment ImGui_ImplSDLRenderer3_RenderState}
  peek _ = error "ImGui_ImplSDLRenderer3_RenderState: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGui_ImplSDLRenderer3_RenderState: opaque struct, poke not supported in v0"
data SDL_Renderer
