{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.Impl.SDL3.Types where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types

#include "dcimgui_impl_sdl3.h"

-- structs (opaque)

data SDL_Event
data SDL_Gamepad
data SDL_Renderer
data SDL_Window

-- enums

type ImGui_ImplSDL3_GamepadMode = CInt
pattern ImGui_ImplSDL3_GamepadMode_AutoFirst :: ImGui_ImplSDL3_GamepadMode
pattern ImGui_ImplSDL3_GamepadMode_AutoFirst = #{const ImGui_ImplSDL3_GamepadMode_AutoFirst}
pattern ImGui_ImplSDL3_GamepadMode_AutoAll :: ImGui_ImplSDL3_GamepadMode
pattern ImGui_ImplSDL3_GamepadMode_AutoAll = #{const ImGui_ImplSDL3_GamepadMode_AutoAll}
pattern ImGui_ImplSDL3_GamepadMode_Manual :: ImGui_ImplSDL3_GamepadMode
pattern ImGui_ImplSDL3_GamepadMode_Manual = #{const ImGui_ImplSDL3_GamepadMode_Manual}
type ImGui_ImplSDL3_MouseCaptureMode = CInt
pattern ImGui_ImplSDL3_MouseCaptureMode_Enabled :: ImGui_ImplSDL3_MouseCaptureMode
pattern ImGui_ImplSDL3_MouseCaptureMode_Enabled = #{const ImGui_ImplSDL3_MouseCaptureMode_Enabled}
pattern ImGui_ImplSDL3_MouseCaptureMode_EnabledAfterDrag :: ImGui_ImplSDL3_MouseCaptureMode
pattern ImGui_ImplSDL3_MouseCaptureMode_EnabledAfterDrag = #{const ImGui_ImplSDL3_MouseCaptureMode_EnabledAfterDrag}
pattern ImGui_ImplSDL3_MouseCaptureMode_Disabled :: ImGui_ImplSDL3_MouseCaptureMode
pattern ImGui_ImplSDL3_MouseCaptureMode_Disabled = #{const ImGui_ImplSDL3_MouseCaptureMode_Disabled}
