{-# LANGUAGE CApiFFI #-}

-- The imnodes side of the demo: a self-portrait.
--
-- The starting node set mirrors `stack dot --no-include-base`'s
-- output — six nodes (this app + the five dear-imgui-raw-* packages
-- it pulls in) wired by their actual `depends-on` edges. Drag a new
-- pin-to-pin link and it appends to the same list; select one and
-- press Delete to drop it. The first frame seeds positions so the
-- nodes don't pile up; later frames don't touch them, leaving the
-- user free to drag.

module App.NodeEditor
  ( EditorState
  , newEditorState
  , drawEditor
  , drawStatus
  , numLinks
  ) where

import Data.Foldable (for_)
import Data.IORef (IORef, modifyIORef', newIORef, readIORef, writeIORef)
import Data.Text (Text)
import Data.Text qualified as Text
import Data.Text.Encoding qualified as TextE
import Data.ByteString qualified as BS
import DearImGui.Raw.ImGui qualified as ImGui
import DearImGui.Raw.ImNodes qualified as Nodes
import DearImGui.Raw.ImNodes.Types
  ( pattern ImNodesPinShape_CircleFilled
  )
import DearImGui.Raw.Types (ImVec2 (..))
import Foreign.C.Types (CBool (..), CInt (..))
import Foreign.C.String (withCString)
import Foreign.Marshal.Alloc (alloca)
import Foreign.Ptr (castPtr, nullPtr, plusPtr)
import Foreign.Storable (peek)

-- ----- starting graph (the self-portrait) ----------------------------
--
-- Edges follow stack-dot semantics: `from -> to` means @from depends
-- on to@. We render that with the depender's input pin (left side)
-- consuming the dependency's output pin (right side), so links flow
-- left-to-right, leaves on the left, root consumer on the right.
--
-- Three layers laid out left-to-right:
--   1. Build-time toolchain   — dear-bindings-aeson + dear-bindings-ffi.
--      The exe consumes the lib (true cabal dep) and conceptually
--      generates the dear-imgui-raw-* packages downstream of it.
--   2. The generated bindings — dear-imgui-raw-{docking, mid pkgs}.
--   3. The example consumer   — imnodes-demo itself.
-- The "ffi feeds the bindings" arrows aren't strict cabal edges but
-- the generation pipeline is the whole point of this repo, so they
-- earn their visual link.

data NodeKind = Library | Executable
  deriving (Eq, Show)

kindLabel :: NodeKind -> Text
kindLabel Library    = "library"
kindLabel Executable = "executable"

data DepNode = DepNode
  { nodeId :: !CInt
  , label  :: !Text
  , kind   :: !NodeKind
  , pos    :: !ImVec2
  }

depNodes :: [DepNode]
depNodes =
  [ DepNode 1 "dear-imgui-raw-docking"          Library    (ImVec2 620 200)
  , DepNode 2 "dear-imgui-raw-docking-internal" Library    (ImVec2 920  40)
  , DepNode 3 "dear-imgui-raw-imnodes"          Library    (ImVec2 920 140)
  , DepNode 4 "dear-imgui-raw-impl-opengl3"     Library    (ImVec2 920 240)
  , DepNode 5 "dear-imgui-raw-impl-sdl2"        Library    (ImVec2 920 340)
  , DepNode 6 "imnodes-demo"                    Executable (ImVec2 1260 200)
  , DepNode 7 "dear-bindings-aeson"             Library    (ImVec2  20 200)
  , DepNode 8 "dear-bindings-ffi"               Executable (ImVec2 320 200)
  ]

-- (depender, dependency) — `stack dot` relation, plus the conceptual
-- "generated by ffi" edges from each emitted binding back to the
-- generator exe.
depEdges :: [(CInt, CInt)]
depEdges =
  [ -- cabal deps among the generated bindings
    (2, 1)  -- docking-internal -> docking
  , (3, 1)  -- imnodes          -> docking
  , (4, 1)  -- impl-opengl3     -> docking
  , (5, 1)  -- impl-sdl2        -> docking
  , (6, 1)  -- imnodes-demo     -> docking
  , (6, 2)  -- imnodes-demo     -> docking-internal
  , (6, 3)  -- imnodes-demo     -> imnodes
  , (6, 4)  -- imnodes-demo     -> impl-opengl3
  , (6, 5)  -- imnodes-demo     -> impl-sdl2

    -- toolchain: the binding generator is itself a cabal exe that
    -- depends on the JSON-parsing library.
  , (8, 7)  -- dear-bindings-ffi -> dear-bindings-aeson

    -- generation: each emitted binding is produced by the ffi exe.
    -- Modeled as a depends-on edge for visual consistency.
  , (1, 8)
  , (2, 8)
  , (3, 8)
  , (4, 8)
  , (5, 8)
  ]

-- Pin id scheme: encode the owning node id and a side bit. Keeps
-- ids unique without a global registry.
nodeIn, nodeOut :: CInt -> CInt
nodeIn  n = n * 10 + 1
nodeOut n = n * 10 + 2

-- ----- runtime state -------------------------------------------------

data Link = Link
  { id_   :: !CInt
  , start :: !CInt
  , end   :: !CInt
  } deriving (Show)

data EditorState = EditorState
  { links         :: !(IORef [Link])
  , nextId        :: !(IORef CInt)
  , layoutSeeded  :: !(IORef Bool)
  }

newEditorState :: IO EditorState
newEditorState = do
  -- Pre-populate the link list with the depEdges so the graph
  -- shows up wired on first frame. Link ids start at 1; user-
  -- created links continue the same counter.
  let seedLinks = zipWith mkLink [1 ..] depEdges
      mkLink i (depender, dependency) =
        Link i (nodeOut dependency) (nodeIn depender)
  links        <- newIORef seedLinks
  nextId       <- newIORef (fromIntegral (length depEdges + 1))
  layoutSeeded <- newIORef False
  pure EditorState{links, nextId, layoutSeeded}

numLinks :: EditorState -> IO Int
numLinks st = length <$> readIORef st.links

-- ----- per-frame draw ------------------------------------------------

drawEditor :: EditorState -> IO ()
drawEditor st = window "Editor" do
  Nodes.imNodesBeginNodeEditor

  for_ depNodes \n -> drawDepNode n

  ls <- readIORef st.links
  for_ ls \l -> Nodes.imNodesLink l.id_ l.start l.end

  Nodes.imNodesEndNodeEditor

  -- Initial position seed has to come AFTER EndNodeEditor on the
  -- frame the editor first runs — imnodes lazily creates per-node
  -- state during BeginNode, and SetNodeGridSpacePos targets that
  -- state. Calling it before the editor has seen the node is a
  -- no-op. Gate so user drags after frame 1 aren't reset.
  seedNeeded <- readIORef st.layoutSeeded
  when_ (not seedNeeded) do
    for_ depNodes \n -> Nodes.imNodesSetNodeGridSpacePos n.nodeId n.pos
    writeIORef st.layoutSeeded True

  detectLinkCreated st
  detectLinkDestroyed st

drawStatus :: EditorState -> IO ()
drawStatus st = window "Status" do
  n <- numLinks st
  text $ Text.pack ("Links: " <> show n <> "  (initial set from `stack dot`)")
  ImGui.imGui_Separator
  hovered <- alloca \p -> do
    cb <- Nodes.imNodesIsNodeHovered p
    case cb of
      CBool 0 -> pure Nothing
      _       -> Just <$> peek p
  text $ case hovered of
    Nothing  -> "Hovered node: -"
    Just nid -> Text.pack ("Hovered node: " <> show nid)
  hoveredLink <- alloca \p -> do
    cb <- Nodes.imNodesIsLinkHovered p
    case cb of
      CBool 0 -> pure Nothing
      _       -> Just <$> peek p
  text $ case hoveredLink of
    Nothing  -> "Hovered link: -"
    Just lid -> Text.pack ("Hovered link: " <> show lid)
  ImGui.imGui_Separator
  text "Drag pin-to-pin to add a link."
  text "Hover a link and press Delete to remove it (when supported)."

-- ----- helpers --------------------------------------------------------

drawDepNode :: DepNode -> IO ()
drawDepNode n = do
  Nodes.imNodesBeginNode n.nodeId
  Nodes.imNodesBeginNodeTitleBar
  text n.label
  Nodes.imNodesEndNodeTitleBar
  -- Single kind annotation in the node body — shared by both pins,
  -- shown once. Pin labels are left empty so the notice doesn't
  -- duplicate.
  text (kindLabel n.kind)
  Nodes.imNodesBeginInputAttributeEx (nodeIn n.nodeId) ImNodesPinShape_CircleFilled
  Nodes.imNodesEndInputAttribute
  Nodes.imNodesBeginOutputAttributeEx (nodeOut n.nodeId) ImNodesPinShape_CircleFilled
  Nodes.imNodesEndOutputAttribute
  Nodes.imNodesEndNode

detectLinkCreated :: EditorState -> IO ()
detectLinkCreated st = alloca \aP -> alloca \bP -> alloca \snapP -> do
  cb <- Nodes.imNodesIsLinkCreatedEx aP bP snapP
  case cb of
    CBool 0 -> pure ()
    _ -> do
      a <- peek aP
      b <- peek bP
      newId <- nextLinkId st
      modifyIORef' st.links (Link newId a b :)

detectLinkDestroyed :: EditorState -> IO ()
detectLinkDestroyed st = alloca \linkP -> do
  cb <- Nodes.imNodesIsLinkDestroyed linkP
  case cb of
    CBool 0 -> pure ()
    _ -> do
      lid <- peek linkP
      modifyIORef' st.links (filter (\l -> l.id_ /= lid))

nextLinkId :: EditorState -> IO CInt
nextLinkId st = do
  n <- readIORef st.nextId
  writeIORef st.nextId (n + 1)
  pure n

-- ----- text + Begin/End wrappers (mirror file-viewer's style) -------

window :: String -> IO () -> IO ()
window title body = do
  open <- withCString title \t -> ImGui.imGui_Begin t nullPtr 0
  case open of
    CBool 0 -> pure ()
    _       -> body
  ImGui.imGui_End

text :: Text -> IO ()
text t = do
  let bs = TextE.encodeUtf8 t
  BS.useAsCStringLen bs \(p, len) ->
    ImGui.imGui_TextUnformatted (castPtr p) (castPtr (p `plusPtr` len))

when_ :: Bool -> IO () -> IO ()
when_ True  k = k
when_ False _ = pure ()
