{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.Internal.ImBitVector where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types hiding (ImDrawListSharedData, ImFontAtlasBuilder, ImFontLoader, ImGuiContext)
import DearImGui.Raw.Internal.Types

#include "dcimgui_nodefaultargfunctions_internal.h"

-- functions

-- C: void Clear(ImBitVector* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImBitVector_Clear"
  imBitVector_Clear :: (Ptr ImBitVector) -> IO ()
-- C: void ClearBit(ImBitVector* self, int n)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImBitVector_ClearBit"
  imBitVector_ClearBit :: (Ptr ImBitVector) -> CInt -> IO ()
-- C: void Create(ImBitVector* self, int sz)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImBitVector_Create"
  imBitVector_Create :: (Ptr ImBitVector) -> CInt -> IO ()
-- C: void SetBit(ImBitVector* self, int n)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImBitVector_SetBit"
  imBitVector_SetBit :: (Ptr ImBitVector) -> CInt -> IO ()
-- C: bool TestBit(const ImBitVector* self, int n)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImBitVector_TestBit"
  imBitVector_TestBit :: (Ptr ImBitVector) -> CInt -> IO CBool
