{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.Internal.ImGuiListClipperRange where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types hiding (ImDrawListSharedData, ImFontAtlasBuilder, ImFontLoader, ImGuiContext)
import DearImGui.Raw.Internal.Types

#include "dcimgui_nodefaultargfunctions_internal.h"

-- functions

foreign import capi unsafe "DearImGuiWrappers.h ImGuiListClipperRange_FromIndices_wrap"
  c_imGuiListClipperRange_FromIndices :: CInt -> CInt -> (Ptr ImGuiListClipperRange) -> IO ()

imGuiListClipperRange_FromIndices :: CInt -> CInt -> IO ImGuiListClipperRange
imGuiListClipperRange_FromIndices min_ max_ =
  alloca $ \_pOut -> c_imGuiListClipperRange_FromIndices min_ max_ _pOut >> peek _pOut

foreign import capi unsafe "DearImGuiWrappers.h ImGuiListClipperRange_FromPositions_wrap"
  c_imGuiListClipperRange_FromPositions :: CFloat -> CFloat -> CInt -> CInt -> (Ptr ImGuiListClipperRange) -> IO ()

imGuiListClipperRange_FromPositions :: CFloat -> CFloat -> CInt -> CInt -> IO ImGuiListClipperRange
imGuiListClipperRange_FromPositions y1 y2 off_min off_max =
  alloca $ \_pOut -> c_imGuiListClipperRange_FromPositions y1 y2 off_min off_max _pOut >> peek _pOut

