{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.Internal.ImGuiWindow where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types hiding (ImDrawListSharedData, ImFontAtlasBuilder, ImFontLoader, ImGuiContext)
import DearImGui.Raw.Internal.Types

#include "dcimgui_nodefaultargfunctions_internal.h"

-- functions

-- C: ImGuiID GetID(ImGuiWindow* self, const void* ptr)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiWindow_GetID"
  imGuiWindow_GetID :: (Ptr ImGuiWindow) -> (Ptr ()) -> IO ImGuiID
foreign import capi unsafe "DearImGuiWrappers.h ImGuiWindow_GetIDFromPos_wrap"
  c_imGuiWindow_GetIDFromPos :: (Ptr ImGuiWindow) -> (Ptr ImVec2) -> IO ImGuiID

imGuiWindow_GetIDFromPos :: (Ptr ImGuiWindow) -> ImVec2 -> IO ImGuiID
imGuiWindow_GetIDFromPos self p_abs =
  with p_abs $ \_p1 -> c_imGuiWindow_GetIDFromPos self _p1

foreign import capi unsafe "DearImGuiWrappers.h ImGuiWindow_GetIDFromRectangle_wrap"
  c_imGuiWindow_GetIDFromRectangle :: (Ptr ImGuiWindow) -> (Ptr ImRect) -> IO ImGuiID

imGuiWindow_GetIDFromRectangle :: (Ptr ImGuiWindow) -> ImRect -> IO ImGuiID
imGuiWindow_GetIDFromRectangle self r_abs =
  with r_abs $ \_p1 -> c_imGuiWindow_GetIDFromRectangle self _p1

-- C: ImGuiID GetID(ImGuiWindow* self, int n)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiWindow_GetIDInt"
  imGuiWindow_GetIDInt :: (Ptr ImGuiWindow) -> CInt -> IO ImGuiID
-- C: ImGuiID GetID(ImGuiWindow* self, const char* str, const char* str_end)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiWindow_GetIDStr"
  imGuiWindow_GetIDStr :: (Ptr ImGuiWindow) -> CString -> CString -> IO ImGuiID
foreign import capi unsafe "DearImGuiWrappers.h ImGuiWindow_MenuBarRect_wrap"
  c_imGuiWindow_MenuBarRect :: (Ptr ImGuiWindow) -> (Ptr ImRect) -> IO ()

imGuiWindow_MenuBarRect :: (Ptr ImGuiWindow) -> IO ImRect
imGuiWindow_MenuBarRect self =
  alloca $ \_pOut -> c_imGuiWindow_MenuBarRect self _pOut >> peek _pOut

foreign import capi unsafe "DearImGuiWrappers.h ImGuiWindow_Rect_wrap"
  c_imGuiWindow_Rect :: (Ptr ImGuiWindow) -> (Ptr ImRect) -> IO ()

imGuiWindow_Rect :: (Ptr ImGuiWindow) -> IO ImRect
imGuiWindow_Rect self =
  alloca $ \_pOut -> c_imGuiWindow_Rect self _pOut >> peek _pOut

foreign import capi unsafe "DearImGuiWrappers.h ImGuiWindow_TitleBarRect_wrap"
  c_imGuiWindow_TitleBarRect :: (Ptr ImGuiWindow) -> (Ptr ImRect) -> IO ()

imGuiWindow_TitleBarRect :: (Ptr ImGuiWindow) -> IO ImRect
imGuiWindow_TitleBarRect self =
  alloca $ \_pOut -> c_imGuiWindow_TitleBarRect self _pOut >> peek _pOut

