{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.Internal.ImRect where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types hiding (ImDrawListSharedData, ImFontAtlasBuilder, ImFontLoader, ImGuiContext)
import DearImGui.Raw.Internal.Types

#include "dcimgui_nodefaultargfunctions_internal.h"

-- functions

foreign import capi unsafe "DearImGuiWrappers.h ImRect_Add_wrap"
  c_imRect_Add :: (Ptr ImRect) -> (Ptr ImVec2) -> IO ()

imRect_Add :: (Ptr ImRect) -> ImVec2 -> IO ()
imRect_Add self p =
  with p $ \_p1 -> c_imRect_Add self _p1

foreign import capi unsafe "DearImGuiWrappers.h ImRect_AddImRect_wrap"
  c_imRect_AddImRect :: (Ptr ImRect) -> (Ptr ImRect) -> IO ()

imRect_AddImRect :: (Ptr ImRect) -> ImRect -> IO ()
imRect_AddImRect self r =
  with r $ \_p1 -> c_imRect_AddImRect self _p1

foreign import capi unsafe "DearImGuiWrappers.h ImRect_ClipWith_wrap"
  c_imRect_ClipWith :: (Ptr ImRect) -> (Ptr ImRect) -> IO ()

imRect_ClipWith :: (Ptr ImRect) -> ImRect -> IO ()
imRect_ClipWith self r =
  with r $ \_p1 -> c_imRect_ClipWith self _p1

foreign import capi unsafe "DearImGuiWrappers.h ImRect_ClipWithFull_wrap"
  c_imRect_ClipWithFull :: (Ptr ImRect) -> (Ptr ImRect) -> IO ()

imRect_ClipWithFull :: (Ptr ImRect) -> ImRect -> IO ()
imRect_ClipWithFull self r =
  with r $ \_p1 -> c_imRect_ClipWithFull self _p1

foreign import capi unsafe "DearImGuiWrappers.h ImRect_Contains_wrap"
  c_imRect_Contains :: (Ptr ImRect) -> (Ptr ImVec2) -> IO CBool

imRect_Contains :: (Ptr ImRect) -> ImVec2 -> IO CBool
imRect_Contains self p =
  with p $ \_p1 -> c_imRect_Contains self _p1

foreign import capi unsafe "DearImGuiWrappers.h ImRect_ContainsImRect_wrap"
  c_imRect_ContainsImRect :: (Ptr ImRect) -> (Ptr ImRect) -> IO CBool

imRect_ContainsImRect :: (Ptr ImRect) -> ImRect -> IO CBool
imRect_ContainsImRect self r =
  with r $ \_p1 -> c_imRect_ContainsImRect self _p1

foreign import capi unsafe "DearImGuiWrappers.h ImRect_ContainsWithPad_wrap"
  c_imRect_ContainsWithPad :: (Ptr ImRect) -> (Ptr ImVec2) -> (Ptr ImVec2) -> IO CBool

imRect_ContainsWithPad :: (Ptr ImRect) -> ImVec2 -> ImVec2 -> IO CBool
imRect_ContainsWithPad self p pad =
  with p $ \_p1 -> with pad $ \_p2 -> c_imRect_ContainsWithPad self _p1 _p2

-- C: void Expand(ImRect* self, const float amount)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImRect_Expand"
  imRect_Expand :: (Ptr ImRect) -> CFloat -> IO ()
foreign import capi unsafe "DearImGuiWrappers.h ImRect_ExpandImVec2_wrap"
  c_imRect_ExpandImVec2 :: (Ptr ImRect) -> (Ptr ImVec2) -> IO ()

imRect_ExpandImVec2 :: (Ptr ImRect) -> ImVec2 -> IO ()
imRect_ExpandImVec2 self amount =
  with amount $ \_p1 -> c_imRect_ExpandImVec2 self _p1

-- C: float GetArea(const ImRect* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImRect_GetArea"
  imRect_GetArea :: (Ptr ImRect) -> IO CFloat
foreign import capi unsafe "DearImGuiWrappers.h ImRect_GetBL_wrap"
  c_imRect_GetBL :: (Ptr ImRect) -> (Ptr ImVec2) -> IO ()

imRect_GetBL :: (Ptr ImRect) -> IO ImVec2
imRect_GetBL self =
  alloca $ \_pOut -> c_imRect_GetBL self _pOut >> peek _pOut

foreign import capi unsafe "DearImGuiWrappers.h ImRect_GetBR_wrap"
  c_imRect_GetBR :: (Ptr ImRect) -> (Ptr ImVec2) -> IO ()

imRect_GetBR :: (Ptr ImRect) -> IO ImVec2
imRect_GetBR self =
  alloca $ \_pOut -> c_imRect_GetBR self _pOut >> peek _pOut

foreign import capi unsafe "DearImGuiWrappers.h ImRect_GetCenter_wrap"
  c_imRect_GetCenter :: (Ptr ImRect) -> (Ptr ImVec2) -> IO ()

imRect_GetCenter :: (Ptr ImRect) -> IO ImVec2
imRect_GetCenter self =
  alloca $ \_pOut -> c_imRect_GetCenter self _pOut >> peek _pOut

-- C: float GetHeight(const ImRect* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImRect_GetHeight"
  imRect_GetHeight :: (Ptr ImRect) -> IO CFloat
foreign import capi unsafe "DearImGuiWrappers.h ImRect_GetSize_wrap"
  c_imRect_GetSize :: (Ptr ImRect) -> (Ptr ImVec2) -> IO ()

imRect_GetSize :: (Ptr ImRect) -> IO ImVec2
imRect_GetSize self =
  alloca $ \_pOut -> c_imRect_GetSize self _pOut >> peek _pOut

foreign import capi unsafe "DearImGuiWrappers.h ImRect_GetTL_wrap"
  c_imRect_GetTL :: (Ptr ImRect) -> (Ptr ImVec2) -> IO ()

imRect_GetTL :: (Ptr ImRect) -> IO ImVec2
imRect_GetTL self =
  alloca $ \_pOut -> c_imRect_GetTL self _pOut >> peek _pOut

foreign import capi unsafe "DearImGuiWrappers.h ImRect_GetTR_wrap"
  c_imRect_GetTR :: (Ptr ImRect) -> (Ptr ImVec2) -> IO ()

imRect_GetTR :: (Ptr ImRect) -> IO ImVec2
imRect_GetTR self =
  alloca $ \_pOut -> c_imRect_GetTR self _pOut >> peek _pOut

-- C: float GetWidth(const ImRect* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImRect_GetWidth"
  imRect_GetWidth :: (Ptr ImRect) -> IO CFloat
-- C: bool IsInverted(const ImRect* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImRect_IsInverted"
  imRect_IsInverted :: (Ptr ImRect) -> IO CBool
foreign import capi unsafe "DearImGuiWrappers.h ImRect_Overlaps_wrap"
  c_imRect_Overlaps :: (Ptr ImRect) -> (Ptr ImRect) -> IO CBool

imRect_Overlaps :: (Ptr ImRect) -> ImRect -> IO CBool
imRect_Overlaps self r =
  with r $ \_p1 -> c_imRect_Overlaps self _p1

foreign import capi unsafe "DearImGuiWrappers.h ImRect_ToVec4_wrap"
  c_imRect_ToVec4 :: (Ptr ImRect) -> (Ptr ImVec4) -> IO ()

imRect_ToVec4 :: (Ptr ImRect) -> IO ImVec4
imRect_ToVec4 self =
  alloca $ \_pOut -> c_imRect_ToVec4 self _pOut >> peek _pOut

foreign import capi unsafe "DearImGuiWrappers.h ImRect_Translate_wrap"
  c_imRect_Translate :: (Ptr ImRect) -> (Ptr ImVec2) -> IO ()

imRect_Translate :: (Ptr ImRect) -> ImVec2 -> IO ()
imRect_Translate self d =
  with d $ \_p1 -> c_imRect_Translate self _p1

-- C: void TranslateX(ImRect* self, float dx)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImRect_TranslateX"
  imRect_TranslateX :: (Ptr ImRect) -> CFloat -> IO ()
-- C: void TranslateY(ImRect* self, float dy)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImRect_TranslateY"
  imRect_TranslateY :: (Ptr ImRect) -> CFloat -> IO ()
