// Generated by dear-bindings-ffi. Do not edit.
#ifndef DEAR_IMGUI_WRAPPERS_H
#define DEAR_IMGUI_WRAPPERS_H

#include "dcimnodes.h"

#ifdef __cplusplus
extern "C" {
#endif

void ImNodesEditorContextGetPanning_wrap(ImVec2* _out);
void ImNodesEditorContextResetPanning_wrap(ImVec2 const* pos);
void ImNodesGetNodeDimensions_wrap(int id, ImVec2* _out);
void ImNodesGetNodeEditorSpacePos_wrap(const int node_id, ImVec2* _out);
void ImNodesGetNodeGridSpacePos_wrap(const int node_id, ImVec2* _out);
void ImNodesGetNodeScreenSpacePos_wrap(const int node_id, ImVec2* _out);
void ImNodesPushStyleVarImVec2_wrap(ImNodesStyleVar style_item, ImVec2 const* value);
void ImNodesSetNodeEditorSpacePos_wrap(int node_id, ImVec2 const* editor_space_pos);
void ImNodesSetNodeGridSpacePos_wrap(int node_id, ImVec2 const* grid_pos);
void ImNodesSetNodeScreenSpacePos_wrap(int node_id, ImVec2 const* screen_space_pos);

#ifdef __cplusplus
}
#endif

#endif
