// Generated by dear-bindings-ffi. Do not edit.
#include "DearImGuiWrappers.h"

extern "C" void ImNodesEditorContextGetPanning_wrap(ImVec2* _out) {
    *_out = ImNodesEditorContextGetPanning();
}

extern "C" void ImNodesEditorContextResetPanning_wrap(ImVec2 const* pos) {
    ImNodesEditorContextResetPanning(*pos);
}

extern "C" void ImNodesGetNodeDimensions_wrap(int id, ImVec2* _out) {
    *_out = ImNodesGetNodeDimensions(id);
}

extern "C" void ImNodesGetNodeEditorSpacePos_wrap(const int node_id, ImVec2* _out) {
    *_out = ImNodesGetNodeEditorSpacePos(node_id);
}

extern "C" void ImNodesGetNodeGridSpacePos_wrap(const int node_id, ImVec2* _out) {
    *_out = ImNodesGetNodeGridSpacePos(node_id);
}

extern "C" void ImNodesGetNodeScreenSpacePos_wrap(const int node_id, ImVec2* _out) {
    *_out = ImNodesGetNodeScreenSpacePos(node_id);
}

extern "C" void ImNodesPushStyleVarImVec2_wrap(ImNodesStyleVar style_item, ImVec2 const* value) {
    ImNodesPushStyleVarImVec2(style_item, *value);
}

extern "C" void ImNodesSetNodeEditorSpacePos_wrap(int node_id, ImVec2 const* editor_space_pos) {
    ImNodesSetNodeEditorSpacePos(node_id, *editor_space_pos);
}

extern "C" void ImNodesSetNodeGridSpacePos_wrap(int node_id, ImVec2 const* grid_pos) {
    ImNodesSetNodeGridSpacePos(node_id, *grid_pos);
}

extern "C" void ImNodesSetNodeScreenSpacePos_wrap(int node_id, ImVec2 const* screen_space_pos) {
    ImNodesSetNodeScreenSpacePos(node_id, *screen_space_pos);
}

