{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.ImDrawData where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types

#include "dcimgui_nodefaultargfunctions.h"

-- functions

-- C: void AddDrawList(ImDrawData* self, ImDrawList* draw_list)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImDrawData_AddDrawList"
  imDrawData_AddDrawList :: (Ptr ImDrawData) -> (Ptr ImDrawList) -> IO ()
-- C: void Clear(ImDrawData* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImDrawData_Clear"
  imDrawData_Clear :: (Ptr ImDrawData) -> IO ()
-- C: void DeIndexAllBuffers(ImDrawData* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImDrawData_DeIndexAllBuffers"
  imDrawData_DeIndexAllBuffers :: (Ptr ImDrawData) -> IO ()
foreign import capi unsafe "DearImGuiWrappers.h ImDrawData_ScaleClipRects_wrap"
  c_imDrawData_ScaleClipRects :: (Ptr ImDrawData) -> (Ptr ImVec2) -> IO ()

imDrawData_ScaleClipRects :: (Ptr ImDrawData) -> ImVec2 -> IO ()
imDrawData_ScaleClipRects self fb_scale =
  with fb_scale $ \_p1 -> c_imDrawData_ScaleClipRects self _p1

