{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.ImGuiPayload where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types

#include "dcimgui_nodefaultargfunctions.h"

-- functions

-- C: void Clear(ImGuiPayload* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGuiPayload_Clear"
  imGuiPayload_Clear :: (Ptr ImGuiPayload) -> IO ()
-- C: bool IsDataType(const ImGuiPayload* self, const char* type)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGuiPayload_IsDataType"
  imGuiPayload_IsDataType :: (Ptr ImGuiPayload) -> CString -> IO CBool
-- C: bool IsDelivery(const ImGuiPayload* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGuiPayload_IsDelivery"
  imGuiPayload_IsDelivery :: (Ptr ImGuiPayload) -> IO CBool
-- C: bool IsPreview(const ImGuiPayload* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGuiPayload_IsPreview"
  imGuiPayload_IsPreview :: (Ptr ImGuiPayload) -> IO CBool
