{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.ImGuiTextBuffer where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types

#include "dcimgui_nodefaultargfunctions.h"

-- functions

-- C: void append(ImGuiTextBuffer* self, const char* str, const char* str_end)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGuiTextBuffer_append"
  imGuiTextBuffer_append :: (Ptr ImGuiTextBuffer) -> CString -> CString -> IO ()
-- C: const char* begin(const ImGuiTextBuffer* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGuiTextBuffer_begin"
  imGuiTextBuffer_begin :: (Ptr ImGuiTextBuffer) -> IO CString
-- C: void clear(ImGuiTextBuffer* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGuiTextBuffer_clear"
  imGuiTextBuffer_clear :: (Ptr ImGuiTextBuffer) -> IO ()
-- C: bool empty(const ImGuiTextBuffer* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGuiTextBuffer_empty"
  imGuiTextBuffer_empty :: (Ptr ImGuiTextBuffer) -> IO CBool
-- C: const char* end(const ImGuiTextBuffer* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGuiTextBuffer_end"
  imGuiTextBuffer_end :: (Ptr ImGuiTextBuffer) -> IO CString
-- C: void reserve(ImGuiTextBuffer* self, int capacity)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGuiTextBuffer_reserve"
  imGuiTextBuffer_reserve :: (Ptr ImGuiTextBuffer) -> CInt -> IO ()
-- C: void resize(ImGuiTextBuffer* self, int size)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGuiTextBuffer_resize"
  imGuiTextBuffer_resize :: (Ptr ImGuiTextBuffer) -> CInt -> IO ()
-- C: int size(const ImGuiTextBuffer* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGuiTextBuffer_size"
  imGuiTextBuffer_size :: (Ptr ImGuiTextBuffer) -> IO CInt
