{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.ImNodes.Types where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types

#include "dcimnodes.h"

-- typedefs

type ImNodesAttributeFlags = CInt
type ImNodesCol = CInt
type ImNodesMiniMapLocation = CInt
type ImNodesMiniMapNodeHoveringCallback = FunPtr (CInt -> (Ptr ()) -> IO ())
type ImNodesMiniMapNodeHoveringCallbackUserData = Ptr ()
type ImNodesPinShape = CInt
type ImNodesStyleFlags = CInt
type ImNodesStyleVar = CInt

-- structs (opaque)

data ImNodesContext
data ImNodesEditorContext
data ImNodesIO
instance Storable ImNodesIO where
  sizeOf _    = #{size ImNodesIO}
  alignment _ = #{alignment ImNodesIO}
  peek _ = error "ImNodesIO: opaque struct, peek not supported in v0"
  poke _ _ = error "ImNodesIO: opaque struct, poke not supported in v0"
data ImNodesIO_EmulateThreeButtonMouse
instance Storable ImNodesIO_EmulateThreeButtonMouse where
  sizeOf _    = #{size ImNodesIO_EmulateThreeButtonMouse}
  alignment _ = #{alignment ImNodesIO_EmulateThreeButtonMouse}
  peek _ = error "ImNodesIO_EmulateThreeButtonMouse: opaque struct, peek not supported in v0"
  poke _ _ = error "ImNodesIO_EmulateThreeButtonMouse: opaque struct, poke not supported in v0"
data ImNodesIO_LinkDetachWithModifierClick
instance Storable ImNodesIO_LinkDetachWithModifierClick where
  sizeOf _    = #{size ImNodesIO_LinkDetachWithModifierClick}
  alignment _ = #{alignment ImNodesIO_LinkDetachWithModifierClick}
  peek _ = error "ImNodesIO_LinkDetachWithModifierClick: opaque struct, peek not supported in v0"
  poke _ _ = error "ImNodesIO_LinkDetachWithModifierClick: opaque struct, poke not supported in v0"
data ImNodesIO_MultipleSelectModifier
instance Storable ImNodesIO_MultipleSelectModifier where
  sizeOf _    = #{size ImNodesIO_MultipleSelectModifier}
  alignment _ = #{alignment ImNodesIO_MultipleSelectModifier}
  peek _ = error "ImNodesIO_MultipleSelectModifier: opaque struct, peek not supported in v0"
  poke _ _ = error "ImNodesIO_MultipleSelectModifier: opaque struct, poke not supported in v0"
data ImNodesStyle
instance Storable ImNodesStyle where
  sizeOf _    = #{size ImNodesStyle}
  alignment _ = #{alignment ImNodesStyle}
  peek _ = error "ImNodesStyle: opaque struct, peek not supported in v0"
  poke _ _ = error "ImNodesStyle: opaque struct, poke not supported in v0"

-- enums

type ImNodesAttributeFlags_ = CInt
pattern ImNodesAttributeFlags_None :: ImNodesAttributeFlags_
pattern ImNodesAttributeFlags_None = #{const ImNodesAttributeFlags_None}
pattern ImNodesAttributeFlags_EnableLinkDetachWithDragClick :: ImNodesAttributeFlags_
pattern ImNodesAttributeFlags_EnableLinkDetachWithDragClick = #{const ImNodesAttributeFlags_EnableLinkDetachWithDragClick}
pattern ImNodesAttributeFlags_EnableLinkCreationOnSnap :: ImNodesAttributeFlags_
pattern ImNodesAttributeFlags_EnableLinkCreationOnSnap = #{const ImNodesAttributeFlags_EnableLinkCreationOnSnap}
type ImNodesCol_ = CInt
pattern ImNodesCol_NodeBackground :: ImNodesCol_
pattern ImNodesCol_NodeBackground = #{const ImNodesCol_NodeBackground}
pattern ImNodesCol_NodeBackgroundHovered :: ImNodesCol_
pattern ImNodesCol_NodeBackgroundHovered = #{const ImNodesCol_NodeBackgroundHovered}
pattern ImNodesCol_NodeBackgroundSelected :: ImNodesCol_
pattern ImNodesCol_NodeBackgroundSelected = #{const ImNodesCol_NodeBackgroundSelected}
pattern ImNodesCol_NodeOutline :: ImNodesCol_
pattern ImNodesCol_NodeOutline = #{const ImNodesCol_NodeOutline}
pattern ImNodesCol_TitleBar :: ImNodesCol_
pattern ImNodesCol_TitleBar = #{const ImNodesCol_TitleBar}
pattern ImNodesCol_TitleBarHovered :: ImNodesCol_
pattern ImNodesCol_TitleBarHovered = #{const ImNodesCol_TitleBarHovered}
pattern ImNodesCol_TitleBarSelected :: ImNodesCol_
pattern ImNodesCol_TitleBarSelected = #{const ImNodesCol_TitleBarSelected}
pattern ImNodesCol_Link :: ImNodesCol_
pattern ImNodesCol_Link = #{const ImNodesCol_Link}
pattern ImNodesCol_LinkHovered :: ImNodesCol_
pattern ImNodesCol_LinkHovered = #{const ImNodesCol_LinkHovered}
pattern ImNodesCol_LinkSelected :: ImNodesCol_
pattern ImNodesCol_LinkSelected = #{const ImNodesCol_LinkSelected}
pattern ImNodesCol_Pin :: ImNodesCol_
pattern ImNodesCol_Pin = #{const ImNodesCol_Pin}
pattern ImNodesCol_PinHovered :: ImNodesCol_
pattern ImNodesCol_PinHovered = #{const ImNodesCol_PinHovered}
pattern ImNodesCol_BoxSelector :: ImNodesCol_
pattern ImNodesCol_BoxSelector = #{const ImNodesCol_BoxSelector}
pattern ImNodesCol_BoxSelectorOutline :: ImNodesCol_
pattern ImNodesCol_BoxSelectorOutline = #{const ImNodesCol_BoxSelectorOutline}
pattern ImNodesCol_GridBackground :: ImNodesCol_
pattern ImNodesCol_GridBackground = #{const ImNodesCol_GridBackground}
pattern ImNodesCol_GridLine :: ImNodesCol_
pattern ImNodesCol_GridLine = #{const ImNodesCol_GridLine}
pattern ImNodesCol_GridLinePrimary :: ImNodesCol_
pattern ImNodesCol_GridLinePrimary = #{const ImNodesCol_GridLinePrimary}
pattern ImNodesCol_MiniMapBackground :: ImNodesCol_
pattern ImNodesCol_MiniMapBackground = #{const ImNodesCol_MiniMapBackground}
pattern ImNodesCol_MiniMapBackgroundHovered :: ImNodesCol_
pattern ImNodesCol_MiniMapBackgroundHovered = #{const ImNodesCol_MiniMapBackgroundHovered}
pattern ImNodesCol_MiniMapOutline :: ImNodesCol_
pattern ImNodesCol_MiniMapOutline = #{const ImNodesCol_MiniMapOutline}
pattern ImNodesCol_MiniMapOutlineHovered :: ImNodesCol_
pattern ImNodesCol_MiniMapOutlineHovered = #{const ImNodesCol_MiniMapOutlineHovered}
pattern ImNodesCol_MiniMapNodeBackground :: ImNodesCol_
pattern ImNodesCol_MiniMapNodeBackground = #{const ImNodesCol_MiniMapNodeBackground}
pattern ImNodesCol_MiniMapNodeBackgroundHovered :: ImNodesCol_
pattern ImNodesCol_MiniMapNodeBackgroundHovered = #{const ImNodesCol_MiniMapNodeBackgroundHovered}
pattern ImNodesCol_MiniMapNodeBackgroundSelected :: ImNodesCol_
pattern ImNodesCol_MiniMapNodeBackgroundSelected = #{const ImNodesCol_MiniMapNodeBackgroundSelected}
pattern ImNodesCol_MiniMapNodeOutline :: ImNodesCol_
pattern ImNodesCol_MiniMapNodeOutline = #{const ImNodesCol_MiniMapNodeOutline}
pattern ImNodesCol_MiniMapLink :: ImNodesCol_
pattern ImNodesCol_MiniMapLink = #{const ImNodesCol_MiniMapLink}
pattern ImNodesCol_MiniMapLinkSelected :: ImNodesCol_
pattern ImNodesCol_MiniMapLinkSelected = #{const ImNodesCol_MiniMapLinkSelected}
pattern ImNodesCol_MiniMapCanvas :: ImNodesCol_
pattern ImNodesCol_MiniMapCanvas = #{const ImNodesCol_MiniMapCanvas}
pattern ImNodesCol_MiniMapCanvasOutline :: ImNodesCol_
pattern ImNodesCol_MiniMapCanvasOutline = #{const ImNodesCol_MiniMapCanvasOutline}
pattern ImNodesCol_COUNT :: ImNodesCol_
pattern ImNodesCol_COUNT = #{const ImNodesCol_COUNT}
type ImNodesMiniMapLocation_ = CInt
pattern ImNodesMiniMapLocation_BottomLeft :: ImNodesMiniMapLocation_
pattern ImNodesMiniMapLocation_BottomLeft = #{const ImNodesMiniMapLocation_BottomLeft}
pattern ImNodesMiniMapLocation_BottomRight :: ImNodesMiniMapLocation_
pattern ImNodesMiniMapLocation_BottomRight = #{const ImNodesMiniMapLocation_BottomRight}
pattern ImNodesMiniMapLocation_TopLeft :: ImNodesMiniMapLocation_
pattern ImNodesMiniMapLocation_TopLeft = #{const ImNodesMiniMapLocation_TopLeft}
pattern ImNodesMiniMapLocation_TopRight :: ImNodesMiniMapLocation_
pattern ImNodesMiniMapLocation_TopRight = #{const ImNodesMiniMapLocation_TopRight}
type ImNodesPinShape_ = CInt
pattern ImNodesPinShape_Circle :: ImNodesPinShape_
pattern ImNodesPinShape_Circle = #{const ImNodesPinShape_Circle}
pattern ImNodesPinShape_CircleFilled :: ImNodesPinShape_
pattern ImNodesPinShape_CircleFilled = #{const ImNodesPinShape_CircleFilled}
pattern ImNodesPinShape_Triangle :: ImNodesPinShape_
pattern ImNodesPinShape_Triangle = #{const ImNodesPinShape_Triangle}
pattern ImNodesPinShape_TriangleFilled :: ImNodesPinShape_
pattern ImNodesPinShape_TriangleFilled = #{const ImNodesPinShape_TriangleFilled}
pattern ImNodesPinShape_Quad :: ImNodesPinShape_
pattern ImNodesPinShape_Quad = #{const ImNodesPinShape_Quad}
pattern ImNodesPinShape_QuadFilled :: ImNodesPinShape_
pattern ImNodesPinShape_QuadFilled = #{const ImNodesPinShape_QuadFilled}
type ImNodesStyleFlags_ = CInt
pattern ImNodesStyleFlags_None :: ImNodesStyleFlags_
pattern ImNodesStyleFlags_None = #{const ImNodesStyleFlags_None}
pattern ImNodesStyleFlags_NodeOutline :: ImNodesStyleFlags_
pattern ImNodesStyleFlags_NodeOutline = #{const ImNodesStyleFlags_NodeOutline}
pattern ImNodesStyleFlags_GridLines :: ImNodesStyleFlags_
pattern ImNodesStyleFlags_GridLines = #{const ImNodesStyleFlags_GridLines}
pattern ImNodesStyleFlags_GridLinesPrimary :: ImNodesStyleFlags_
pattern ImNodesStyleFlags_GridLinesPrimary = #{const ImNodesStyleFlags_GridLinesPrimary}
pattern ImNodesStyleFlags_GridSnapping :: ImNodesStyleFlags_
pattern ImNodesStyleFlags_GridSnapping = #{const ImNodesStyleFlags_GridSnapping}
type ImNodesStyleVar_ = CInt
pattern ImNodesStyleVar_GridSpacing :: ImNodesStyleVar_
pattern ImNodesStyleVar_GridSpacing = #{const ImNodesStyleVar_GridSpacing}
pattern ImNodesStyleVar_NodeCornerRounding :: ImNodesStyleVar_
pattern ImNodesStyleVar_NodeCornerRounding = #{const ImNodesStyleVar_NodeCornerRounding}
pattern ImNodesStyleVar_NodePadding :: ImNodesStyleVar_
pattern ImNodesStyleVar_NodePadding = #{const ImNodesStyleVar_NodePadding}
pattern ImNodesStyleVar_NodeBorderThickness :: ImNodesStyleVar_
pattern ImNodesStyleVar_NodeBorderThickness = #{const ImNodesStyleVar_NodeBorderThickness}
pattern ImNodesStyleVar_LinkThickness :: ImNodesStyleVar_
pattern ImNodesStyleVar_LinkThickness = #{const ImNodesStyleVar_LinkThickness}
pattern ImNodesStyleVar_LinkLineSegmentsPerLength :: ImNodesStyleVar_
pattern ImNodesStyleVar_LinkLineSegmentsPerLength = #{const ImNodesStyleVar_LinkLineSegmentsPerLength}
pattern ImNodesStyleVar_LinkHoverDistance :: ImNodesStyleVar_
pattern ImNodesStyleVar_LinkHoverDistance = #{const ImNodesStyleVar_LinkHoverDistance}
pattern ImNodesStyleVar_PinCircleRadius :: ImNodesStyleVar_
pattern ImNodesStyleVar_PinCircleRadius = #{const ImNodesStyleVar_PinCircleRadius}
pattern ImNodesStyleVar_PinQuadSideLength :: ImNodesStyleVar_
pattern ImNodesStyleVar_PinQuadSideLength = #{const ImNodesStyleVar_PinQuadSideLength}
pattern ImNodesStyleVar_PinTriangleSideLength :: ImNodesStyleVar_
pattern ImNodesStyleVar_PinTriangleSideLength = #{const ImNodesStyleVar_PinTriangleSideLength}
pattern ImNodesStyleVar_PinLineThickness :: ImNodesStyleVar_
pattern ImNodesStyleVar_PinLineThickness = #{const ImNodesStyleVar_PinLineThickness}
pattern ImNodesStyleVar_PinHoverRadius :: ImNodesStyleVar_
pattern ImNodesStyleVar_PinHoverRadius = #{const ImNodesStyleVar_PinHoverRadius}
pattern ImNodesStyleVar_PinOffset :: ImNodesStyleVar_
pattern ImNodesStyleVar_PinOffset = #{const ImNodesStyleVar_PinOffset}
pattern ImNodesStyleVar_MiniMapPadding :: ImNodesStyleVar_
pattern ImNodesStyleVar_MiniMapPadding = #{const ImNodesStyleVar_MiniMapPadding}
pattern ImNodesStyleVar_MiniMapOffset :: ImNodesStyleVar_
pattern ImNodesStyleVar_MiniMapOffset = #{const ImNodesStyleVar_MiniMapOffset}
pattern ImNodesStyleVar_COUNT :: ImNodesStyleVar_
pattern ImNodesStyleVar_COUNT = #{const ImNodesStyleVar_COUNT}
