{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.Impl.OpenGL3 where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types
import DearImGui.Raw.Impl.OpenGL3.Types

#include "dcimgui_impl_opengl3.h"

-- functions

-- C: bool ImGui_ImplOpenGL3_CreateDeviceObjects()
foreign import capi unsafe "dcimgui_impl_opengl3.h cImGui_ImplOpenGL3_CreateDeviceObjects"
  cImGui_ImplOpenGL3_CreateDeviceObjects :: IO CBool
-- C: void ImGui_ImplOpenGL3_DestroyDeviceObjects()
foreign import capi unsafe "dcimgui_impl_opengl3.h cImGui_ImplOpenGL3_DestroyDeviceObjects"
  cImGui_ImplOpenGL3_DestroyDeviceObjects :: IO ()
-- C: bool ImGui_ImplOpenGL3_Init(const char* glsl_version)
foreign import capi unsafe "dcimgui_impl_opengl3.h cImGui_ImplOpenGL3_InitEx"
  cImGui_ImplOpenGL3_InitEx :: CString -> IO CBool
-- C: void ImGui_ImplOpenGL3_NewFrame()
foreign import capi unsafe "dcimgui_impl_opengl3.h cImGui_ImplOpenGL3_NewFrame"
  cImGui_ImplOpenGL3_NewFrame :: IO ()
-- C: void ImGui_ImplOpenGL3_RenderDrawData(ImDrawData* draw_data)
foreign import capi unsafe "dcimgui_impl_opengl3.h cImGui_ImplOpenGL3_RenderDrawData"
  cImGui_ImplOpenGL3_RenderDrawData :: (Ptr ImDrawData) -> IO ()
-- C: void ImGui_ImplOpenGL3_Shutdown()
foreign import capi unsafe "dcimgui_impl_opengl3.h cImGui_ImplOpenGL3_Shutdown"
  cImGui_ImplOpenGL3_Shutdown :: IO ()
-- C: void ImGui_ImplOpenGL3_UpdateTexture(ImTextureData* tex)
foreign import capi unsafe "dcimgui_impl_opengl3.h cImGui_ImplOpenGL3_UpdateTexture"
  cImGui_ImplOpenGL3_UpdateTexture :: (Ptr ImTextureData) -> IO ()
