{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.Internal.ImGuiInputTextState where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types hiding (ImDrawListSharedData, ImFontAtlasBuilder, ImFontLoader, ImGuiContext)
import DearImGui.Raw.Internal.Types

#include "dcimgui_nodefaultargfunctions_internal.h"

-- functions

-- C: void ClearFreeMemory(ImGuiInputTextState* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiInputTextState_ClearFreeMemory"
  imGuiInputTextState_ClearFreeMemory :: (Ptr ImGuiInputTextState) -> IO ()
-- C: void ClearSelection(ImGuiInputTextState* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiInputTextState_ClearSelection"
  imGuiInputTextState_ClearSelection :: (Ptr ImGuiInputTextState) -> IO ()
-- C: void ClearText(ImGuiInputTextState* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiInputTextState_ClearText"
  imGuiInputTextState_ClearText :: (Ptr ImGuiInputTextState) -> IO ()
-- C: void CursorAnimReset(ImGuiInputTextState* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiInputTextState_CursorAnimReset"
  imGuiInputTextState_CursorAnimReset :: (Ptr ImGuiInputTextState) -> IO ()
-- C: void CursorClamp(ImGuiInputTextState* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiInputTextState_CursorClamp"
  imGuiInputTextState_CursorClamp :: (Ptr ImGuiInputTextState) -> IO ()
-- C: int GetCursorPos(const ImGuiInputTextState* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiInputTextState_GetCursorPos"
  imGuiInputTextState_GetCursorPos :: (Ptr ImGuiInputTextState) -> IO CInt
-- C: float GetPreferredOffsetX(const ImGuiInputTextState* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiInputTextState_GetPreferredOffsetX"
  imGuiInputTextState_GetPreferredOffsetX :: (Ptr ImGuiInputTextState) -> IO CFloat
-- C: int GetSelectionEnd(const ImGuiInputTextState* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiInputTextState_GetSelectionEnd"
  imGuiInputTextState_GetSelectionEnd :: (Ptr ImGuiInputTextState) -> IO CInt
-- C: int GetSelectionStart(const ImGuiInputTextState* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiInputTextState_GetSelectionStart"
  imGuiInputTextState_GetSelectionStart :: (Ptr ImGuiInputTextState) -> IO CInt
-- C: const char* GetText(ImGuiInputTextState* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiInputTextState_GetText"
  imGuiInputTextState_GetText :: (Ptr ImGuiInputTextState) -> IO CString
-- C: bool HasSelection(const ImGuiInputTextState* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiInputTextState_HasSelection"
  imGuiInputTextState_HasSelection :: (Ptr ImGuiInputTextState) -> IO CBool
-- C: void OnCharPressed(ImGuiInputTextState* self, unsigned int c)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiInputTextState_OnCharPressed"
  imGuiInputTextState_OnCharPressed :: (Ptr ImGuiInputTextState) -> CUInt -> IO ()
-- C: void OnKeyPressed(ImGuiInputTextState* self, int key)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiInputTextState_OnKeyPressed"
  imGuiInputTextState_OnKeyPressed :: (Ptr ImGuiInputTextState) -> CInt -> IO ()
-- C: void ReloadUserBufAndKeepSelection(ImGuiInputTextState* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiInputTextState_ReloadUserBufAndKeepSelection"
  imGuiInputTextState_ReloadUserBufAndKeepSelection :: (Ptr ImGuiInputTextState) -> IO ()
-- C: void ReloadUserBufAndMoveToEnd(ImGuiInputTextState* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiInputTextState_ReloadUserBufAndMoveToEnd"
  imGuiInputTextState_ReloadUserBufAndMoveToEnd :: (Ptr ImGuiInputTextState) -> IO ()
-- C: void ReloadUserBufAndSelectAll(ImGuiInputTextState* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiInputTextState_ReloadUserBufAndSelectAll"
  imGuiInputTextState_ReloadUserBufAndSelectAll :: (Ptr ImGuiInputTextState) -> IO ()
-- C: void SelectAll(ImGuiInputTextState* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiInputTextState_SelectAll"
  imGuiInputTextState_SelectAll :: (Ptr ImGuiInputTextState) -> IO ()
-- C: void SetSelection(ImGuiInputTextState* self, int start, int end)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiInputTextState_SetSelection"
  imGuiInputTextState_SetSelection :: (Ptr ImGuiInputTextState) -> CInt -> CInt -> IO ()
