{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.Internal.ImGuiTextIndex where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types hiding (ImDrawListSharedData, ImFontAtlasBuilder, ImFontLoader, ImGuiContext)
import DearImGui.Raw.Internal.Types

#include "dcimgui_nodefaultargfunctions_internal.h"

-- functions

-- C: void append(ImGuiTextIndex* self, const char* base, int old_size, int new_size)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiTextIndex_append"
  imGuiTextIndex_append :: (Ptr ImGuiTextIndex) -> CString -> CInt -> CInt -> IO ()
-- C: void clear(ImGuiTextIndex* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiTextIndex_clear"
  imGuiTextIndex_clear :: (Ptr ImGuiTextIndex) -> IO ()
-- C: int size(ImGuiTextIndex* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiTextIndex_size"
  imGuiTextIndex_size :: (Ptr ImGuiTextIndex) -> IO CInt
