{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.Internal.ImGuiMenuColumns where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types hiding (ImDrawListSharedData, ImFontAtlasBuilder, ImFontLoader, ImGuiContext)
import DearImGui.Raw.Internal.Types

#include "dcimgui_nodefaultargfunctions_internal.h"

-- functions

-- C: void CalcNextTotalWidth(ImGuiMenuColumns* self, bool update_offsets)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiMenuColumns_CalcNextTotalWidth"
  imGuiMenuColumns_CalcNextTotalWidth :: (Ptr ImGuiMenuColumns) -> CBool -> IO ()
-- C: float DeclColumns(ImGuiMenuColumns* self, float w_icon, float w_label, float w_shortcut, float w_mark)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiMenuColumns_DeclColumns"
  imGuiMenuColumns_DeclColumns :: (Ptr ImGuiMenuColumns) -> CFloat -> CFloat -> CFloat -> CFloat -> IO CFloat
-- C: void Update(ImGuiMenuColumns* self, float spacing, bool window_reappearing)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiMenuColumns_Update"
  imGuiMenuColumns_Update :: (Ptr ImGuiMenuColumns) -> CFloat -> CBool -> IO ()
