{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.Internal.ImGuiDockNode where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types hiding (ImDrawListSharedData, ImFontAtlasBuilder, ImFontLoader, ImGuiContext)
import DearImGui.Raw.Internal.Types

#include "dcimgui_nodefaultargfunctions_internal.h"

-- functions

-- C: bool IsCentralNode(const ImGuiDockNode* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiDockNode_IsCentralNode"
  imGuiDockNode_IsCentralNode :: (Ptr ImGuiDockNode) -> IO CBool
-- C: bool IsDockSpace(const ImGuiDockNode* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiDockNode_IsDockSpace"
  imGuiDockNode_IsDockSpace :: (Ptr ImGuiDockNode) -> IO CBool
-- C: bool IsEmpty(const ImGuiDockNode* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiDockNode_IsEmpty"
  imGuiDockNode_IsEmpty :: (Ptr ImGuiDockNode) -> IO CBool
-- C: bool IsFloatingNode(const ImGuiDockNode* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiDockNode_IsFloatingNode"
  imGuiDockNode_IsFloatingNode :: (Ptr ImGuiDockNode) -> IO CBool
-- C: bool IsHiddenTabBar(const ImGuiDockNode* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiDockNode_IsHiddenTabBar"
  imGuiDockNode_IsHiddenTabBar :: (Ptr ImGuiDockNode) -> IO CBool
-- C: bool IsLeafNode(const ImGuiDockNode* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiDockNode_IsLeafNode"
  imGuiDockNode_IsLeafNode :: (Ptr ImGuiDockNode) -> IO CBool
-- C: bool IsNoTabBar(const ImGuiDockNode* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiDockNode_IsNoTabBar"
  imGuiDockNode_IsNoTabBar :: (Ptr ImGuiDockNode) -> IO CBool
-- C: bool IsRootNode(const ImGuiDockNode* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiDockNode_IsRootNode"
  imGuiDockNode_IsRootNode :: (Ptr ImGuiDockNode) -> IO CBool
-- C: bool IsSplitNode(const ImGuiDockNode* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiDockNode_IsSplitNode"
  imGuiDockNode_IsSplitNode :: (Ptr ImGuiDockNode) -> IO CBool
foreign import capi unsafe "DearImGuiWrappers.h ImGuiDockNode_Rect_wrap"
  c_imGuiDockNode_Rect :: (Ptr ImGuiDockNode) -> (Ptr ImRect) -> IO ()

imGuiDockNode_Rect :: (Ptr ImGuiDockNode) -> IO ImRect
imGuiDockNode_Rect self =
  alloca $ \_pOut -> c_imGuiDockNode_Rect self _pOut >> peek _pOut

-- C: void SetLocalFlags(ImGuiDockNode* self, ImGuiDockNodeFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiDockNode_SetLocalFlags"
  imGuiDockNode_SetLocalFlags :: (Ptr ImGuiDockNode) -> ImGuiDockNodeFlags -> IO ()
-- C: void UpdateMergedFlags(ImGuiDockNode* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions_internal.h ImGuiDockNode_UpdateMergedFlags"
  imGuiDockNode_UpdateMergedFlags :: (Ptr ImGuiDockNode) -> IO ()
