{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.Internal.Types where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types hiding (ImDrawListSharedData, ImFontAtlasBuilder, ImFontLoader, ImGuiContext)

#include "dcimgui_nodefaultargfunctions_internal.h"

-- typedefs

type ImBitArrayPtr = Ptr ImU32
type ImFileHandle = Ptr FILE
type ImFontBuilderIO = ImFontLoader
type ImGuiActivateFlags = CInt
type ImGuiContextHookCallback = FunPtr ((Ptr ImGuiContext) -> (Ptr ImGuiContextHook) -> IO ())
type ImGuiDataAuthority = CInt
type ImGuiDebugLogFlags = CInt
type ImGuiDemoMarkerCallback = FunPtr (CString -> CInt -> CString -> IO ())
type ImGuiErrorCallback = FunPtr ((Ptr ImGuiContext) -> (Ptr ()) -> CString -> IO ())
type ImGuiFocusRequestFlags = CInt
type ImGuiItemStatusFlags = CInt
type ImGuiKeyRoutingIndex = ImS16
type ImGuiLayoutType = CInt
type ImGuiLogFlags = CInt
type ImGuiNavMoveFlags = CInt
type ImGuiNavRenderCursorFlags = CInt
type ImGuiNextItemDataFlags = CInt
type ImGuiNextWindowDataFlags = CInt
type ImGuiOldColumnFlags = CInt
type ImGuiScrollFlags = CInt
type ImGuiSeparatorFlags = CInt
type ImGuiTableColumnIdx = ImS16
type ImGuiTableDrawChannelIdx = ImU16
type ImGuiTextFlags = CInt
type ImGuiTooltipFlags = CInt
type ImGuiTypingSelectFlags = CInt
type ImGuiWindowBgClickFlags = CInt
type ImGuiWindowRefreshFlags = CInt
type ImPoolIdx = CInt
type Stbrp_node_im = Stbrp_node

-- structs (opaque)

data FILE
data ImBitArrayForNamedKeys
instance Storable ImBitArrayForNamedKeys where
  sizeOf _    = #{size ImBitArrayForNamedKeys}
  alignment _ = #{alignment ImBitArrayForNamedKeys}
  peek _ = error "ImBitArrayForNamedKeys: opaque struct, peek not supported in v0"
  poke _ _ = error "ImBitArrayForNamedKeys: opaque struct, poke not supported in v0"
data ImBitVector
instance Storable ImBitVector where
  sizeOf _    = #{size ImBitVector}
  alignment _ = #{alignment ImBitVector}
  peek _ = error "ImBitVector: opaque struct, peek not supported in v0"
  poke _ _ = error "ImBitVector: opaque struct, poke not supported in v0"
data ImChunkStream_ImGuiTableSettings
instance Storable ImChunkStream_ImGuiTableSettings where
  sizeOf _    = #{size ImChunkStream_ImGuiTableSettings}
  alignment _ = #{alignment ImChunkStream_ImGuiTableSettings}
  peek _ = error "ImChunkStream_ImGuiTableSettings: opaque struct, peek not supported in v0"
  poke _ _ = error "ImChunkStream_ImGuiTableSettings: opaque struct, poke not supported in v0"
data ImChunkStream_ImGuiWindowSettings
instance Storable ImChunkStream_ImGuiWindowSettings where
  sizeOf _    = #{size ImChunkStream_ImGuiWindowSettings}
  alignment _ = #{alignment ImChunkStream_ImGuiWindowSettings}
  peek _ = error "ImChunkStream_ImGuiWindowSettings: opaque struct, peek not supported in v0"
  poke _ _ = error "ImChunkStream_ImGuiWindowSettings: opaque struct, poke not supported in v0"
data ImDrawDataBuilder
instance Storable ImDrawDataBuilder where
  sizeOf _    = #{size ImDrawDataBuilder}
  alignment _ = #{alignment ImDrawDataBuilder}
  peek _ = error "ImDrawDataBuilder: opaque struct, peek not supported in v0"
  poke _ _ = error "ImDrawDataBuilder: opaque struct, poke not supported in v0"
data ImDrawListSharedData
instance Storable ImDrawListSharedData where
  sizeOf _    = #{size ImDrawListSharedData}
  alignment _ = #{alignment ImDrawListSharedData}
  peek _ = error "ImDrawListSharedData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImDrawListSharedData: opaque struct, poke not supported in v0"
data ImFontAtlasBuilder
instance Storable ImFontAtlasBuilder where
  sizeOf _    = #{size ImFontAtlasBuilder}
  alignment _ = #{alignment ImFontAtlasBuilder}
  peek _ = error "ImFontAtlasBuilder: opaque struct, peek not supported in v0"
  poke _ _ = error "ImFontAtlasBuilder: opaque struct, poke not supported in v0"
data ImFontAtlasPostProcessData
instance Storable ImFontAtlasPostProcessData where
  sizeOf _    = #{size ImFontAtlasPostProcessData}
  alignment _ = #{alignment ImFontAtlasPostProcessData}
  peek _ = error "ImFontAtlasPostProcessData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImFontAtlasPostProcessData: opaque struct, poke not supported in v0"
data ImFontAtlasRectEntry
instance Storable ImFontAtlasRectEntry where
  sizeOf _    = #{size ImFontAtlasRectEntry}
  alignment _ = #{alignment ImFontAtlasRectEntry}
  peek _ = error "ImFontAtlasRectEntry: opaque struct, peek not supported in v0"
  poke _ _ = error "ImFontAtlasRectEntry: opaque struct, poke not supported in v0"
data ImFontLoader
instance Storable ImFontLoader where
  sizeOf _    = #{size ImFontLoader}
  alignment _ = #{alignment ImFontLoader}
  peek _ = error "ImFontLoader: opaque struct, peek not supported in v0"
  poke _ _ = error "ImFontLoader: opaque struct, poke not supported in v0"
data ImFontStackData
instance Storable ImFontStackData where
  sizeOf _    = #{size ImFontStackData}
  alignment _ = #{alignment ImFontStackData}
  peek _ = error "ImFontStackData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImFontStackData: opaque struct, poke not supported in v0"
data ImGuiBoxSelectState
instance Storable ImGuiBoxSelectState where
  sizeOf _    = #{size ImGuiBoxSelectState}
  alignment _ = #{alignment ImGuiBoxSelectState}
  peek _ = error "ImGuiBoxSelectState: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiBoxSelectState: opaque struct, poke not supported in v0"
data ImGuiColorMod
instance Storable ImGuiColorMod where
  sizeOf _    = #{size ImGuiColorMod}
  alignment _ = #{alignment ImGuiColorMod}
  peek _ = error "ImGuiColorMod: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiColorMod: opaque struct, poke not supported in v0"
data ImGuiComboPreviewData
instance Storable ImGuiComboPreviewData where
  sizeOf _    = #{size ImGuiComboPreviewData}
  alignment _ = #{alignment ImGuiComboPreviewData}
  peek _ = error "ImGuiComboPreviewData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiComboPreviewData: opaque struct, poke not supported in v0"
data ImGuiContext
instance Storable ImGuiContext where
  sizeOf _    = #{size ImGuiContext}
  alignment _ = #{alignment ImGuiContext}
  peek _ = error "ImGuiContext: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiContext: opaque struct, poke not supported in v0"
data ImGuiContextHook
instance Storable ImGuiContextHook where
  sizeOf _    = #{size ImGuiContextHook}
  alignment _ = #{alignment ImGuiContextHook}
  peek _ = error "ImGuiContextHook: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiContextHook: opaque struct, poke not supported in v0"
data ImGuiDataTypeInfo
instance Storable ImGuiDataTypeInfo where
  sizeOf _    = #{size ImGuiDataTypeInfo}
  alignment _ = #{alignment ImGuiDataTypeInfo}
  peek _ = error "ImGuiDataTypeInfo: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiDataTypeInfo: opaque struct, poke not supported in v0"
data ImGuiDataTypeStorage
instance Storable ImGuiDataTypeStorage where
  sizeOf _    = #{size ImGuiDataTypeStorage}
  alignment _ = #{alignment ImGuiDataTypeStorage}
  peek _ = error "ImGuiDataTypeStorage: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiDataTypeStorage: opaque struct, poke not supported in v0"
data ImGuiDeactivatedItemData
instance Storable ImGuiDeactivatedItemData where
  sizeOf _    = #{size ImGuiDeactivatedItemData}
  alignment _ = #{alignment ImGuiDeactivatedItemData}
  peek _ = error "ImGuiDeactivatedItemData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiDeactivatedItemData: opaque struct, poke not supported in v0"
data ImGuiDebugAllocEntry
instance Storable ImGuiDebugAllocEntry where
  sizeOf _    = #{size ImGuiDebugAllocEntry}
  alignment _ = #{alignment ImGuiDebugAllocEntry}
  peek _ = error "ImGuiDebugAllocEntry: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiDebugAllocEntry: opaque struct, poke not supported in v0"
data ImGuiDebugAllocInfo
instance Storable ImGuiDebugAllocInfo where
  sizeOf _    = #{size ImGuiDebugAllocInfo}
  alignment _ = #{alignment ImGuiDebugAllocInfo}
  peek _ = error "ImGuiDebugAllocInfo: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiDebugAllocInfo: opaque struct, poke not supported in v0"
data ImGuiDebugItemPathQuery
instance Storable ImGuiDebugItemPathQuery where
  sizeOf _    = #{size ImGuiDebugItemPathQuery}
  alignment _ = #{alignment ImGuiDebugItemPathQuery}
  peek _ = error "ImGuiDebugItemPathQuery: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiDebugItemPathQuery: opaque struct, poke not supported in v0"
data ImGuiDockContext
instance Storable ImGuiDockContext where
  sizeOf _    = #{size ImGuiDockContext}
  alignment _ = #{alignment ImGuiDockContext}
  peek _ = error "ImGuiDockContext: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiDockContext: opaque struct, poke not supported in v0"
data ImGuiDockNode
instance Storable ImGuiDockNode where
  sizeOf _    = #{size ImGuiDockNode}
  alignment _ = #{alignment ImGuiDockNode}
  peek _ = error "ImGuiDockNode: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiDockNode: opaque struct, poke not supported in v0"
data ImGuiDockNodeSettings
data ImGuiDockRequest
data ImGuiErrorRecoveryState
instance Storable ImGuiErrorRecoveryState where
  sizeOf _    = #{size ImGuiErrorRecoveryState}
  alignment _ = #{alignment ImGuiErrorRecoveryState}
  peek _ = error "ImGuiErrorRecoveryState: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiErrorRecoveryState: opaque struct, poke not supported in v0"
data ImGuiFocusScopeData
instance Storable ImGuiFocusScopeData where
  sizeOf _    = #{size ImGuiFocusScopeData}
  alignment _ = #{alignment ImGuiFocusScopeData}
  peek _ = error "ImGuiFocusScopeData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiFocusScopeData: opaque struct, poke not supported in v0"
data ImGuiGroupData
instance Storable ImGuiGroupData where
  sizeOf _    = #{size ImGuiGroupData}
  alignment _ = #{alignment ImGuiGroupData}
  peek _ = error "ImGuiGroupData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiGroupData: opaque struct, poke not supported in v0"
data ImGuiIDStackTool
instance Storable ImGuiIDStackTool where
  sizeOf _    = #{size ImGuiIDStackTool}
  alignment _ = #{alignment ImGuiIDStackTool}
  peek _ = error "ImGuiIDStackTool: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiIDStackTool: opaque struct, poke not supported in v0"
data ImGuiInputEvent
instance Storable ImGuiInputEvent where
  sizeOf _    = #{size ImGuiInputEvent}
  alignment _ = #{alignment ImGuiInputEvent}
  peek _ = error "ImGuiInputEvent: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiInputEvent: opaque struct, poke not supported in v0"
data ImGuiInputEventAppFocused
instance Storable ImGuiInputEventAppFocused where
  sizeOf _    = #{size ImGuiInputEventAppFocused}
  alignment _ = #{alignment ImGuiInputEventAppFocused}
  peek _ = error "ImGuiInputEventAppFocused: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiInputEventAppFocused: opaque struct, poke not supported in v0"
data ImGuiInputEventKey
instance Storable ImGuiInputEventKey where
  sizeOf _    = #{size ImGuiInputEventKey}
  alignment _ = #{alignment ImGuiInputEventKey}
  peek _ = error "ImGuiInputEventKey: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiInputEventKey: opaque struct, poke not supported in v0"
data ImGuiInputEventMouseButton
instance Storable ImGuiInputEventMouseButton where
  sizeOf _    = #{size ImGuiInputEventMouseButton}
  alignment _ = #{alignment ImGuiInputEventMouseButton}
  peek _ = error "ImGuiInputEventMouseButton: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiInputEventMouseButton: opaque struct, poke not supported in v0"
data ImGuiInputEventMousePos
instance Storable ImGuiInputEventMousePos where
  sizeOf _    = #{size ImGuiInputEventMousePos}
  alignment _ = #{alignment ImGuiInputEventMousePos}
  peek _ = error "ImGuiInputEventMousePos: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiInputEventMousePos: opaque struct, poke not supported in v0"
data ImGuiInputEventMouseViewport
instance Storable ImGuiInputEventMouseViewport where
  sizeOf _    = #{size ImGuiInputEventMouseViewport}
  alignment _ = #{alignment ImGuiInputEventMouseViewport}
  peek _ = error "ImGuiInputEventMouseViewport: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiInputEventMouseViewport: opaque struct, poke not supported in v0"
data ImGuiInputEventMouseWheel
instance Storable ImGuiInputEventMouseWheel where
  sizeOf _    = #{size ImGuiInputEventMouseWheel}
  alignment _ = #{alignment ImGuiInputEventMouseWheel}
  peek _ = error "ImGuiInputEventMouseWheel: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiInputEventMouseWheel: opaque struct, poke not supported in v0"
data ImGuiInputEventText
instance Storable ImGuiInputEventText where
  sizeOf _    = #{size ImGuiInputEventText}
  alignment _ = #{alignment ImGuiInputEventText}
  peek _ = error "ImGuiInputEventText: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiInputEventText: opaque struct, poke not supported in v0"
data ImGuiInputTextDeactivateData
data ImGuiInputTextDeactivatedState
instance Storable ImGuiInputTextDeactivatedState where
  sizeOf _    = #{size ImGuiInputTextDeactivatedState}
  alignment _ = #{alignment ImGuiInputTextDeactivatedState}
  peek _ = error "ImGuiInputTextDeactivatedState: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiInputTextDeactivatedState: opaque struct, poke not supported in v0"
data ImGuiInputTextState
instance Storable ImGuiInputTextState where
  sizeOf _    = #{size ImGuiInputTextState}
  alignment _ = #{alignment ImGuiInputTextState}
  peek _ = error "ImGuiInputTextState: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiInputTextState: opaque struct, poke not supported in v0"
data ImGuiKeyOwnerData
instance Storable ImGuiKeyOwnerData where
  sizeOf _    = #{size ImGuiKeyOwnerData}
  alignment _ = #{alignment ImGuiKeyOwnerData}
  peek _ = error "ImGuiKeyOwnerData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiKeyOwnerData: opaque struct, poke not supported in v0"
data ImGuiKeyRoutingData
instance Storable ImGuiKeyRoutingData where
  sizeOf _    = #{size ImGuiKeyRoutingData}
  alignment _ = #{alignment ImGuiKeyRoutingData}
  peek _ = error "ImGuiKeyRoutingData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiKeyRoutingData: opaque struct, poke not supported in v0"
data ImGuiKeyRoutingTable
instance Storable ImGuiKeyRoutingTable where
  sizeOf _    = #{size ImGuiKeyRoutingTable}
  alignment _ = #{alignment ImGuiKeyRoutingTable}
  peek _ = error "ImGuiKeyRoutingTable: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiKeyRoutingTable: opaque struct, poke not supported in v0"
data ImGuiLastItemData
instance Storable ImGuiLastItemData where
  sizeOf _    = #{size ImGuiLastItemData}
  alignment _ = #{alignment ImGuiLastItemData}
  peek _ = error "ImGuiLastItemData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiLastItemData: opaque struct, poke not supported in v0"
data ImGuiListClipperData
instance Storable ImGuiListClipperData where
  sizeOf _    = #{size ImGuiListClipperData}
  alignment _ = #{alignment ImGuiListClipperData}
  peek _ = error "ImGuiListClipperData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiListClipperData: opaque struct, poke not supported in v0"
-- by-value
data {-# CTYPE "dcimgui_nodefaultargfunctions_internal.h" "ImGuiListClipperRange" #-} ImGuiListClipperRange = ImGuiListClipperRange
  { min :: CInt
  , max :: CInt
  , posToIndexConvert :: CBool
  , posToIndexOffsetMin :: ImS8
  , posToIndexOffsetMax :: ImS8
  }
  deriving (Eq, Show)

instance Storable ImGuiListClipperRange where
  sizeOf _    = #{size ImGuiListClipperRange}
  alignment _ = #{alignment ImGuiListClipperRange}
  peek p = ImGuiListClipperRange <$> #{peek ImGuiListClipperRange, Min} p <*> #{peek ImGuiListClipperRange, Max} p <*> #{peek ImGuiListClipperRange, PosToIndexConvert} p <*> #{peek ImGuiListClipperRange, PosToIndexOffsetMin} p <*> #{peek ImGuiListClipperRange, PosToIndexOffsetMax} p
  poke p v = do
    #{poke ImGuiListClipperRange, Min} p v.min
    #{poke ImGuiListClipperRange, Max} p v.max
    #{poke ImGuiListClipperRange, PosToIndexConvert} p v.posToIndexConvert
    #{poke ImGuiListClipperRange, PosToIndexOffsetMin} p v.posToIndexOffsetMin
    #{poke ImGuiListClipperRange, PosToIndexOffsetMax} p v.posToIndexOffsetMax
data ImGuiLocEntry
instance Storable ImGuiLocEntry where
  sizeOf _    = #{size ImGuiLocEntry}
  alignment _ = #{alignment ImGuiLocEntry}
  peek _ = error "ImGuiLocEntry: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiLocEntry: opaque struct, poke not supported in v0"
data ImGuiMenuColumns
instance Storable ImGuiMenuColumns where
  sizeOf _    = #{size ImGuiMenuColumns}
  alignment _ = #{alignment ImGuiMenuColumns}
  peek _ = error "ImGuiMenuColumns: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiMenuColumns: opaque struct, poke not supported in v0"
data ImGuiMetricsConfig
instance Storable ImGuiMetricsConfig where
  sizeOf _    = #{size ImGuiMetricsConfig}
  alignment _ = #{alignment ImGuiMetricsConfig}
  peek _ = error "ImGuiMetricsConfig: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiMetricsConfig: opaque struct, poke not supported in v0"
data ImGuiMultiSelectState
instance Storable ImGuiMultiSelectState where
  sizeOf _    = #{size ImGuiMultiSelectState}
  alignment _ = #{alignment ImGuiMultiSelectState}
  peek _ = error "ImGuiMultiSelectState: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiMultiSelectState: opaque struct, poke not supported in v0"
data ImGuiMultiSelectTempData
instance Storable ImGuiMultiSelectTempData where
  sizeOf _    = #{size ImGuiMultiSelectTempData}
  alignment _ = #{alignment ImGuiMultiSelectTempData}
  peek _ = error "ImGuiMultiSelectTempData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiMultiSelectTempData: opaque struct, poke not supported in v0"
data ImGuiNavItemData
instance Storable ImGuiNavItemData where
  sizeOf _    = #{size ImGuiNavItemData}
  alignment _ = #{alignment ImGuiNavItemData}
  peek _ = error "ImGuiNavItemData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiNavItemData: opaque struct, poke not supported in v0"
data ImGuiNextItemData
instance Storable ImGuiNextItemData where
  sizeOf _    = #{size ImGuiNextItemData}
  alignment _ = #{alignment ImGuiNextItemData}
  peek _ = error "ImGuiNextItemData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiNextItemData: opaque struct, poke not supported in v0"
data ImGuiNextWindowData
instance Storable ImGuiNextWindowData where
  sizeOf _    = #{size ImGuiNextWindowData}
  alignment _ = #{alignment ImGuiNextWindowData}
  peek _ = error "ImGuiNextWindowData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiNextWindowData: opaque struct, poke not supported in v0"
data ImGuiOldColumnData
instance Storable ImGuiOldColumnData where
  sizeOf _    = #{size ImGuiOldColumnData}
  alignment _ = #{alignment ImGuiOldColumnData}
  peek _ = error "ImGuiOldColumnData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiOldColumnData: opaque struct, poke not supported in v0"
data ImGuiOldColumns
instance Storable ImGuiOldColumns where
  sizeOf _    = #{size ImGuiOldColumns}
  alignment _ = #{alignment ImGuiOldColumns}
  peek _ = error "ImGuiOldColumns: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiOldColumns: opaque struct, poke not supported in v0"
data ImGuiPopupData
instance Storable ImGuiPopupData where
  sizeOf _    = #{size ImGuiPopupData}
  alignment _ = #{alignment ImGuiPopupData}
  peek _ = error "ImGuiPopupData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiPopupData: opaque struct, poke not supported in v0"
data ImGuiPtrOrIndex
instance Storable ImGuiPtrOrIndex where
  sizeOf _    = #{size ImGuiPtrOrIndex}
  alignment _ = #{alignment ImGuiPtrOrIndex}
  peek _ = error "ImGuiPtrOrIndex: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiPtrOrIndex: opaque struct, poke not supported in v0"
data ImGuiSettingsHandler
instance Storable ImGuiSettingsHandler where
  sizeOf _    = #{size ImGuiSettingsHandler}
  alignment _ = #{alignment ImGuiSettingsHandler}
  peek _ = error "ImGuiSettingsHandler: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiSettingsHandler: opaque struct, poke not supported in v0"
data ImGuiShrinkWidthItem
instance Storable ImGuiShrinkWidthItem where
  sizeOf _    = #{size ImGuiShrinkWidthItem}
  alignment _ = #{alignment ImGuiShrinkWidthItem}
  peek _ = error "ImGuiShrinkWidthItem: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiShrinkWidthItem: opaque struct, poke not supported in v0"
data ImGuiStackLevelInfo
instance Storable ImGuiStackLevelInfo where
  sizeOf _    = #{size ImGuiStackLevelInfo}
  alignment _ = #{alignment ImGuiStackLevelInfo}
  peek _ = error "ImGuiStackLevelInfo: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiStackLevelInfo: opaque struct, poke not supported in v0"
data ImGuiStyleMod
instance Storable ImGuiStyleMod where
  sizeOf _    = #{size ImGuiStyleMod}
  alignment _ = #{alignment ImGuiStyleMod}
  peek _ = error "ImGuiStyleMod: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiStyleMod: opaque struct, poke not supported in v0"
data ImGuiStyleVarInfo
instance Storable ImGuiStyleVarInfo where
  sizeOf _    = #{size ImGuiStyleVarInfo}
  alignment _ = #{alignment ImGuiStyleVarInfo}
  peek _ = error "ImGuiStyleVarInfo: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiStyleVarInfo: opaque struct, poke not supported in v0"
data ImGuiTabBar
instance Storable ImGuiTabBar where
  sizeOf _    = #{size ImGuiTabBar}
  alignment _ = #{alignment ImGuiTabBar}
  peek _ = error "ImGuiTabBar: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiTabBar: opaque struct, poke not supported in v0"
data ImGuiTabItem
instance Storable ImGuiTabItem where
  sizeOf _    = #{size ImGuiTabItem}
  alignment _ = #{alignment ImGuiTabItem}
  peek _ = error "ImGuiTabItem: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiTabItem: opaque struct, poke not supported in v0"
data ImGuiTable
instance Storable ImGuiTable where
  sizeOf _    = #{size ImGuiTable}
  alignment _ = #{alignment ImGuiTable}
  peek _ = error "ImGuiTable: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiTable: opaque struct, poke not supported in v0"
data ImGuiTableCellData
instance Storable ImGuiTableCellData where
  sizeOf _    = #{size ImGuiTableCellData}
  alignment _ = #{alignment ImGuiTableCellData}
  peek _ = error "ImGuiTableCellData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiTableCellData: opaque struct, poke not supported in v0"
data ImGuiTableColumn
instance Storable ImGuiTableColumn where
  sizeOf _    = #{size ImGuiTableColumn}
  alignment _ = #{alignment ImGuiTableColumn}
  peek _ = error "ImGuiTableColumn: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiTableColumn: opaque struct, poke not supported in v0"
data ImGuiTableColumnSettings
instance Storable ImGuiTableColumnSettings where
  sizeOf _    = #{size ImGuiTableColumnSettings}
  alignment _ = #{alignment ImGuiTableColumnSettings}
  peek _ = error "ImGuiTableColumnSettings: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiTableColumnSettings: opaque struct, poke not supported in v0"
data ImGuiTableColumnsSettings
data ImGuiTableHeaderData
instance Storable ImGuiTableHeaderData where
  sizeOf _    = #{size ImGuiTableHeaderData}
  alignment _ = #{alignment ImGuiTableHeaderData}
  peek _ = error "ImGuiTableHeaderData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiTableHeaderData: opaque struct, poke not supported in v0"
data ImGuiTableInstanceData
instance Storable ImGuiTableInstanceData where
  sizeOf _    = #{size ImGuiTableInstanceData}
  alignment _ = #{alignment ImGuiTableInstanceData}
  peek _ = error "ImGuiTableInstanceData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiTableInstanceData: opaque struct, poke not supported in v0"
data ImGuiTableSettings
instance Storable ImGuiTableSettings where
  sizeOf _    = #{size ImGuiTableSettings}
  alignment _ = #{alignment ImGuiTableSettings}
  peek _ = error "ImGuiTableSettings: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiTableSettings: opaque struct, poke not supported in v0"
data ImGuiTableTempData
instance Storable ImGuiTableTempData where
  sizeOf _    = #{size ImGuiTableTempData}
  alignment _ = #{alignment ImGuiTableTempData}
  peek _ = error "ImGuiTableTempData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiTableTempData: opaque struct, poke not supported in v0"
data ImGuiTextIndex
instance Storable ImGuiTextIndex where
  sizeOf _    = #{size ImGuiTextIndex}
  alignment _ = #{alignment ImGuiTextIndex}
  peek _ = error "ImGuiTextIndex: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiTextIndex: opaque struct, poke not supported in v0"
data ImGuiTreeNodeStackData
instance Storable ImGuiTreeNodeStackData where
  sizeOf _    = #{size ImGuiTreeNodeStackData}
  alignment _ = #{alignment ImGuiTreeNodeStackData}
  peek _ = error "ImGuiTreeNodeStackData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiTreeNodeStackData: opaque struct, poke not supported in v0"
data ImGuiTypingSelectRequest
instance Storable ImGuiTypingSelectRequest where
  sizeOf _    = #{size ImGuiTypingSelectRequest}
  alignment _ = #{alignment ImGuiTypingSelectRequest}
  peek _ = error "ImGuiTypingSelectRequest: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiTypingSelectRequest: opaque struct, poke not supported in v0"
data ImGuiTypingSelectState
instance Storable ImGuiTypingSelectState where
  sizeOf _    = #{size ImGuiTypingSelectState}
  alignment _ = #{alignment ImGuiTypingSelectState}
  peek _ = error "ImGuiTypingSelectState: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiTypingSelectState: opaque struct, poke not supported in v0"
data ImGuiViewportP
instance Storable ImGuiViewportP where
  sizeOf _    = #{size ImGuiViewportP}
  alignment _ = #{alignment ImGuiViewportP}
  peek _ = error "ImGuiViewportP: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiViewportP: opaque struct, poke not supported in v0"
data ImGuiWindow
instance Storable ImGuiWindow where
  sizeOf _    = #{size ImGuiWindow}
  alignment _ = #{alignment ImGuiWindow}
  peek _ = error "ImGuiWindow: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiWindow: opaque struct, poke not supported in v0"
data ImGuiWindowDockStyle
instance Storable ImGuiWindowDockStyle where
  sizeOf _    = #{size ImGuiWindowDockStyle}
  alignment _ = #{alignment ImGuiWindowDockStyle}
  peek _ = error "ImGuiWindowDockStyle: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiWindowDockStyle: opaque struct, poke not supported in v0"
data ImGuiWindowSettings
instance Storable ImGuiWindowSettings where
  sizeOf _    = #{size ImGuiWindowSettings}
  alignment _ = #{alignment ImGuiWindowSettings}
  peek _ = error "ImGuiWindowSettings: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiWindowSettings: opaque struct, poke not supported in v0"
data ImGuiWindowStackData
instance Storable ImGuiWindowStackData where
  sizeOf _    = #{size ImGuiWindowStackData}
  alignment _ = #{alignment ImGuiWindowStackData}
  peek _ = error "ImGuiWindowStackData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiWindowStackData: opaque struct, poke not supported in v0"
data ImGuiWindowTempData
instance Storable ImGuiWindowTempData where
  sizeOf _    = #{size ImGuiWindowTempData}
  alignment _ = #{alignment ImGuiWindowTempData}
  peek _ = error "ImGuiWindowTempData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGuiWindowTempData: opaque struct, poke not supported in v0"
data ImPool_ImGuiMultiSelectState
instance Storable ImPool_ImGuiMultiSelectState where
  sizeOf _    = #{size ImPool_ImGuiMultiSelectState}
  alignment _ = #{alignment ImPool_ImGuiMultiSelectState}
  peek _ = error "ImPool_ImGuiMultiSelectState: opaque struct, peek not supported in v0"
  poke _ _ = error "ImPool_ImGuiMultiSelectState: opaque struct, poke not supported in v0"
data ImPool_ImGuiTabBar
instance Storable ImPool_ImGuiTabBar where
  sizeOf _    = #{size ImPool_ImGuiTabBar}
  alignment _ = #{alignment ImPool_ImGuiTabBar}
  peek _ = error "ImPool_ImGuiTabBar: opaque struct, peek not supported in v0"
  poke _ _ = error "ImPool_ImGuiTabBar: opaque struct, poke not supported in v0"
data ImPool_ImGuiTable
instance Storable ImPool_ImGuiTable where
  sizeOf _    = #{size ImPool_ImGuiTable}
  alignment _ = #{alignment ImPool_ImGuiTable}
  peek _ = error "ImPool_ImGuiTable: opaque struct, peek not supported in v0"
  poke _ _ = error "ImPool_ImGuiTable: opaque struct, poke not supported in v0"
-- by-value
data {-# CTYPE "dcimgui_nodefaultargfunctions_internal.h" "ImRect" #-} ImRect = ImRect
  { min :: ImVec2
  , max :: ImVec2
  }
  deriving (Eq, Show)

instance Storable ImRect where
  sizeOf _    = #{size ImRect}
  alignment _ = #{alignment ImRect}
  peek p = ImRect <$> #{peek ImRect, Min} p <*> #{peek ImRect, Max} p
  poke p v = do
    #{poke ImRect, Min} p v.min
    #{poke ImRect, Max} p v.max
data ImSpan_ImGuiTableCellData
instance Storable ImSpan_ImGuiTableCellData where
  sizeOf _    = #{size ImSpan_ImGuiTableCellData}
  alignment _ = #{alignment ImSpan_ImGuiTableCellData}
  peek _ = error "ImSpan_ImGuiTableCellData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImSpan_ImGuiTableCellData: opaque struct, poke not supported in v0"
data ImSpan_ImGuiTableColumn
instance Storable ImSpan_ImGuiTableColumn where
  sizeOf _    = #{size ImSpan_ImGuiTableColumn}
  alignment _ = #{alignment ImSpan_ImGuiTableColumn}
  peek _ = error "ImSpan_ImGuiTableColumn: opaque struct, peek not supported in v0"
  poke _ _ = error "ImSpan_ImGuiTableColumn: opaque struct, poke not supported in v0"
data ImSpan_ImGuiTableColumnIdx
instance Storable ImSpan_ImGuiTableColumnIdx where
  sizeOf _    = #{size ImSpan_ImGuiTableColumnIdx}
  alignment _ = #{alignment ImSpan_ImGuiTableColumnIdx}
  peek _ = error "ImSpan_ImGuiTableColumnIdx: opaque struct, peek not supported in v0"
  poke _ _ = error "ImSpan_ImGuiTableColumnIdx: opaque struct, poke not supported in v0"
data ImStableVector_ImFontBaked_32
instance Storable ImStableVector_ImFontBaked_32 where
  sizeOf _    = #{size ImStableVector_ImFontBaked_32}
  alignment _ = #{alignment ImStableVector_ImFontBaked_32}
  peek _ = error "ImStableVector_ImFontBaked_32: opaque struct, peek not supported in v0"
  poke _ _ = error "ImStableVector_ImFontBaked_32: opaque struct, poke not supported in v0"
data ImStb_STB_TexteditState
-- by-value
data {-# CTYPE "dcimgui_nodefaultargfunctions_internal.h" "ImVec1" #-} ImVec1 = ImVec1
  { x :: CFloat
  }
  deriving (Eq, Show)

instance Storable ImVec1 where
  sizeOf _    = #{size ImVec1}
  alignment _ = #{alignment ImVec1}
  peek p = ImVec1 <$> #{peek ImVec1, x} p
  poke p v = do
    #{poke ImVec1, x} p v.x
-- by-value
data {-# CTYPE "dcimgui_nodefaultargfunctions_internal.h" "ImVec2i" #-} ImVec2i = ImVec2i
  { x :: CInt
  , y :: CInt
  }
  deriving (Eq, Show)

instance Storable ImVec2i where
  sizeOf _    = #{size ImVec2i}
  alignment _ = #{alignment ImVec2i}
  peek p = ImVec2i <$> #{peek ImVec2i, x} p <*> #{peek ImVec2i, y} p
  poke p v = do
    #{poke ImVec2i, x} p v.x
    #{poke ImVec2i, y} p v.y
-- by-value
data {-# CTYPE "dcimgui_nodefaultargfunctions_internal.h" "ImVec2ih" #-} ImVec2ih = ImVec2ih
  { x :: CShort
  , y :: CShort
  }
  deriving (Eq, Show)

instance Storable ImVec2ih where
  sizeOf _    = #{size ImVec2ih}
  alignment _ = #{alignment ImVec2ih}
  peek p = ImVec2ih <$> #{peek ImVec2ih, x} p <*> #{peek ImVec2ih, y} p
  poke p v = do
    #{poke ImVec2ih, x} p v.x
    #{poke ImVec2ih, y} p v.y
data ImVector_ImFontAtlasPtr
instance Storable ImVector_ImFontAtlasPtr where
  sizeOf _    = #{size ImVector_ImFontAtlasPtr}
  alignment _ = #{alignment ImVector_ImFontAtlasPtr}
  peek _ = error "ImVector_ImFontAtlasPtr: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImFontAtlasPtr: opaque struct, poke not supported in v0"
data ImVector_ImFontAtlasRectEntry
instance Storable ImVector_ImFontAtlasRectEntry where
  sizeOf _    = #{size ImVector_ImFontAtlasRectEntry}
  alignment _ = #{alignment ImVector_ImFontAtlasRectEntry}
  peek _ = error "ImVector_ImFontAtlasRectEntry: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImFontAtlasRectEntry: opaque struct, poke not supported in v0"
data ImVector_ImFontBakedPtr
instance Storable ImVector_ImFontBakedPtr where
  sizeOf _    = #{size ImVector_ImFontBakedPtr}
  alignment _ = #{alignment ImVector_ImFontBakedPtr}
  peek _ = error "ImVector_ImFontBakedPtr: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImFontBakedPtr: opaque struct, poke not supported in v0"
data ImVector_ImFontStackData
instance Storable ImVector_ImFontStackData where
  sizeOf _    = #{size ImVector_ImFontStackData}
  alignment _ = #{alignment ImVector_ImFontStackData}
  peek _ = error "ImVector_ImFontStackData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImFontStackData: opaque struct, poke not supported in v0"
data ImVector_ImGuiColorMod
instance Storable ImVector_ImGuiColorMod where
  sizeOf _    = #{size ImVector_ImGuiColorMod}
  alignment _ = #{alignment ImVector_ImGuiColorMod}
  peek _ = error "ImVector_ImGuiColorMod: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiColorMod: opaque struct, poke not supported in v0"
data ImVector_ImGuiContextHook
instance Storable ImVector_ImGuiContextHook where
  sizeOf _    = #{size ImVector_ImGuiContextHook}
  alignment _ = #{alignment ImVector_ImGuiContextHook}
  peek _ = error "ImVector_ImGuiContextHook: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiContextHook: opaque struct, poke not supported in v0"
data ImVector_ImGuiDockNodeSettings
instance Storable ImVector_ImGuiDockNodeSettings where
  sizeOf _    = #{size ImVector_ImGuiDockNodeSettings}
  alignment _ = #{alignment ImVector_ImGuiDockNodeSettings}
  peek _ = error "ImVector_ImGuiDockNodeSettings: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiDockNodeSettings: opaque struct, poke not supported in v0"
data ImVector_ImGuiDockRequest
instance Storable ImVector_ImGuiDockRequest where
  sizeOf _    = #{size ImVector_ImGuiDockRequest}
  alignment _ = #{alignment ImVector_ImGuiDockRequest}
  peek _ = error "ImVector_ImGuiDockRequest: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiDockRequest: opaque struct, poke not supported in v0"
data ImVector_ImGuiFocusScopeData
instance Storable ImVector_ImGuiFocusScopeData where
  sizeOf _    = #{size ImVector_ImGuiFocusScopeData}
  alignment _ = #{alignment ImVector_ImGuiFocusScopeData}
  peek _ = error "ImVector_ImGuiFocusScopeData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiFocusScopeData: opaque struct, poke not supported in v0"
data ImVector_ImGuiGroupData
instance Storable ImVector_ImGuiGroupData where
  sizeOf _    = #{size ImVector_ImGuiGroupData}
  alignment _ = #{alignment ImVector_ImGuiGroupData}
  peek _ = error "ImVector_ImGuiGroupData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiGroupData: opaque struct, poke not supported in v0"
data ImVector_ImGuiID
instance Storable ImVector_ImGuiID where
  sizeOf _    = #{size ImVector_ImGuiID}
  alignment _ = #{alignment ImVector_ImGuiID}
  peek _ = error "ImVector_ImGuiID: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiID: opaque struct, poke not supported in v0"
data ImVector_ImGuiInputEvent
instance Storable ImVector_ImGuiInputEvent where
  sizeOf _    = #{size ImVector_ImGuiInputEvent}
  alignment _ = #{alignment ImVector_ImGuiInputEvent}
  peek _ = error "ImVector_ImGuiInputEvent: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiInputEvent: opaque struct, poke not supported in v0"
data ImVector_ImGuiItemFlags
instance Storable ImVector_ImGuiItemFlags where
  sizeOf _    = #{size ImVector_ImGuiItemFlags}
  alignment _ = #{alignment ImVector_ImGuiItemFlags}
  peek _ = error "ImVector_ImGuiItemFlags: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiItemFlags: opaque struct, poke not supported in v0"
data ImVector_ImGuiKeyRoutingData
instance Storable ImVector_ImGuiKeyRoutingData where
  sizeOf _    = #{size ImVector_ImGuiKeyRoutingData}
  alignment _ = #{alignment ImVector_ImGuiKeyRoutingData}
  peek _ = error "ImVector_ImGuiKeyRoutingData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiKeyRoutingData: opaque struct, poke not supported in v0"
data ImVector_ImGuiListClipperData
instance Storable ImVector_ImGuiListClipperData where
  sizeOf _    = #{size ImVector_ImGuiListClipperData}
  alignment _ = #{alignment ImVector_ImGuiListClipperData}
  peek _ = error "ImVector_ImGuiListClipperData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiListClipperData: opaque struct, poke not supported in v0"
data ImVector_ImGuiListClipperRange
instance Storable ImVector_ImGuiListClipperRange where
  sizeOf _    = #{size ImVector_ImGuiListClipperRange}
  alignment _ = #{alignment ImVector_ImGuiListClipperRange}
  peek _ = error "ImVector_ImGuiListClipperRange: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiListClipperRange: opaque struct, poke not supported in v0"
data ImVector_ImGuiMultiSelectState
instance Storable ImVector_ImGuiMultiSelectState where
  sizeOf _    = #{size ImVector_ImGuiMultiSelectState}
  alignment _ = #{alignment ImVector_ImGuiMultiSelectState}
  peek _ = error "ImVector_ImGuiMultiSelectState: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiMultiSelectState: opaque struct, poke not supported in v0"
data ImVector_ImGuiMultiSelectTempData
instance Storable ImVector_ImGuiMultiSelectTempData where
  sizeOf _    = #{size ImVector_ImGuiMultiSelectTempData}
  alignment _ = #{alignment ImVector_ImGuiMultiSelectTempData}
  peek _ = error "ImVector_ImGuiMultiSelectTempData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiMultiSelectTempData: opaque struct, poke not supported in v0"
data ImVector_ImGuiOldColumnData
instance Storable ImVector_ImGuiOldColumnData where
  sizeOf _    = #{size ImVector_ImGuiOldColumnData}
  alignment _ = #{alignment ImVector_ImGuiOldColumnData}
  peek _ = error "ImVector_ImGuiOldColumnData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiOldColumnData: opaque struct, poke not supported in v0"
data ImVector_ImGuiOldColumns
instance Storable ImVector_ImGuiOldColumns where
  sizeOf _    = #{size ImVector_ImGuiOldColumns}
  alignment _ = #{alignment ImVector_ImGuiOldColumns}
  peek _ = error "ImVector_ImGuiOldColumns: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiOldColumns: opaque struct, poke not supported in v0"
data ImVector_ImGuiPopupData
instance Storable ImVector_ImGuiPopupData where
  sizeOf _    = #{size ImVector_ImGuiPopupData}
  alignment _ = #{alignment ImVector_ImGuiPopupData}
  peek _ = error "ImVector_ImGuiPopupData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiPopupData: opaque struct, poke not supported in v0"
data ImVector_ImGuiPtrOrIndex
instance Storable ImVector_ImGuiPtrOrIndex where
  sizeOf _    = #{size ImVector_ImGuiPtrOrIndex}
  alignment _ = #{alignment ImVector_ImGuiPtrOrIndex}
  peek _ = error "ImVector_ImGuiPtrOrIndex: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiPtrOrIndex: opaque struct, poke not supported in v0"
data ImVector_ImGuiSettingsHandler
instance Storable ImVector_ImGuiSettingsHandler where
  sizeOf _    = #{size ImVector_ImGuiSettingsHandler}
  alignment _ = #{alignment ImVector_ImGuiSettingsHandler}
  peek _ = error "ImVector_ImGuiSettingsHandler: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiSettingsHandler: opaque struct, poke not supported in v0"
data ImVector_ImGuiShrinkWidthItem
instance Storable ImVector_ImGuiShrinkWidthItem where
  sizeOf _    = #{size ImVector_ImGuiShrinkWidthItem}
  alignment _ = #{alignment ImVector_ImGuiShrinkWidthItem}
  peek _ = error "ImVector_ImGuiShrinkWidthItem: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiShrinkWidthItem: opaque struct, poke not supported in v0"
data ImVector_ImGuiStackLevelInfo
instance Storable ImVector_ImGuiStackLevelInfo where
  sizeOf _    = #{size ImVector_ImGuiStackLevelInfo}
  alignment _ = #{alignment ImVector_ImGuiStackLevelInfo}
  peek _ = error "ImVector_ImGuiStackLevelInfo: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiStackLevelInfo: opaque struct, poke not supported in v0"
data ImVector_ImGuiStyleMod
instance Storable ImVector_ImGuiStyleMod where
  sizeOf _    = #{size ImVector_ImGuiStyleMod}
  alignment _ = #{alignment ImVector_ImGuiStyleMod}
  peek _ = error "ImVector_ImGuiStyleMod: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiStyleMod: opaque struct, poke not supported in v0"
data ImVector_ImGuiTabBar
instance Storable ImVector_ImGuiTabBar where
  sizeOf _    = #{size ImVector_ImGuiTabBar}
  alignment _ = #{alignment ImVector_ImGuiTabBar}
  peek _ = error "ImVector_ImGuiTabBar: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiTabBar: opaque struct, poke not supported in v0"
data ImVector_ImGuiTabItem
instance Storable ImVector_ImGuiTabItem where
  sizeOf _    = #{size ImVector_ImGuiTabItem}
  alignment _ = #{alignment ImVector_ImGuiTabItem}
  peek _ = error "ImVector_ImGuiTabItem: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiTabItem: opaque struct, poke not supported in v0"
data ImVector_ImGuiTable
instance Storable ImVector_ImGuiTable where
  sizeOf _    = #{size ImVector_ImGuiTable}
  alignment _ = #{alignment ImVector_ImGuiTable}
  peek _ = error "ImVector_ImGuiTable: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiTable: opaque struct, poke not supported in v0"
data ImVector_ImGuiTableColumnSortSpecs
instance Storable ImVector_ImGuiTableColumnSortSpecs where
  sizeOf _    = #{size ImVector_ImGuiTableColumnSortSpecs}
  alignment _ = #{alignment ImVector_ImGuiTableColumnSortSpecs}
  peek _ = error "ImVector_ImGuiTableColumnSortSpecs: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiTableColumnSortSpecs: opaque struct, poke not supported in v0"
data ImVector_ImGuiTableHeaderData
instance Storable ImVector_ImGuiTableHeaderData where
  sizeOf _    = #{size ImVector_ImGuiTableHeaderData}
  alignment _ = #{alignment ImVector_ImGuiTableHeaderData}
  peek _ = error "ImVector_ImGuiTableHeaderData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiTableHeaderData: opaque struct, poke not supported in v0"
data ImVector_ImGuiTableInstanceData
instance Storable ImVector_ImGuiTableInstanceData where
  sizeOf _    = #{size ImVector_ImGuiTableInstanceData}
  alignment _ = #{alignment ImVector_ImGuiTableInstanceData}
  peek _ = error "ImVector_ImGuiTableInstanceData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiTableInstanceData: opaque struct, poke not supported in v0"
data ImVector_ImGuiTableTempData
instance Storable ImVector_ImGuiTableTempData where
  sizeOf _    = #{size ImVector_ImGuiTableTempData}
  alignment _ = #{alignment ImVector_ImGuiTableTempData}
  peek _ = error "ImVector_ImGuiTableTempData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiTableTempData: opaque struct, poke not supported in v0"
data ImVector_ImGuiTreeNodeStackData
instance Storable ImVector_ImGuiTreeNodeStackData where
  sizeOf _    = #{size ImVector_ImGuiTreeNodeStackData}
  alignment _ = #{alignment ImVector_ImGuiTreeNodeStackData}
  peek _ = error "ImVector_ImGuiTreeNodeStackData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiTreeNodeStackData: opaque struct, poke not supported in v0"
data ImVector_ImGuiViewportPPtr
instance Storable ImVector_ImGuiViewportPPtr where
  sizeOf _    = #{size ImVector_ImGuiViewportPPtr}
  alignment _ = #{alignment ImVector_ImGuiViewportPPtr}
  peek _ = error "ImVector_ImGuiViewportPPtr: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiViewportPPtr: opaque struct, poke not supported in v0"
data ImVector_ImGuiWindowPtr
instance Storable ImVector_ImGuiWindowPtr where
  sizeOf _    = #{size ImVector_ImGuiWindowPtr}
  alignment _ = #{alignment ImVector_ImGuiWindowPtr}
  peek _ = error "ImVector_ImGuiWindowPtr: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiWindowPtr: opaque struct, poke not supported in v0"
data ImVector_ImGuiWindowStackData
instance Storable ImVector_ImGuiWindowStackData where
  sizeOf _    = #{size ImVector_ImGuiWindowStackData}
  alignment _ = #{alignment ImVector_ImGuiWindowStackData}
  peek _ = error "ImVector_ImGuiWindowStackData: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGuiWindowStackData: opaque struct, poke not supported in v0"
data ImVector_const_charPtr
instance Storable ImVector_const_charPtr where
  sizeOf _    = #{size ImVector_const_charPtr}
  alignment _ = #{alignment ImVector_const_charPtr}
  peek _ = error "ImVector_const_charPtr: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_const_charPtr: opaque struct, poke not supported in v0"
data ImVector_int
instance Storable ImVector_int where
  sizeOf _    = #{size ImVector_int}
  alignment _ = #{alignment ImVector_int}
  peek _ = error "ImVector_int: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_int: opaque struct, poke not supported in v0"
data ImVector_stbrp_node_im
instance Storable ImVector_stbrp_node_im where
  sizeOf _    = #{size ImVector_stbrp_node_im}
  alignment _ = #{alignment ImVector_stbrp_node_im}
  peek _ = error "ImVector_stbrp_node_im: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_stbrp_node_im: opaque struct, poke not supported in v0"
data ImVector_unsigned_char
instance Storable ImVector_unsigned_char where
  sizeOf _    = #{size ImVector_unsigned_char}
  alignment _ = #{alignment ImVector_unsigned_char}
  peek _ = error "ImVector_unsigned_char: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_unsigned_char: opaque struct, poke not supported in v0"
data Stbrp_context_opaque
instance Storable Stbrp_context_opaque where
  sizeOf _    = #{size stbrp_context_opaque}
  alignment _ = #{alignment stbrp_context_opaque}
  peek _ = error "Stbrp_context_opaque: opaque struct, peek not supported in v0"
  poke _ _ = error "Stbrp_context_opaque: opaque struct, poke not supported in v0"
data Stbrp_node

-- enums

type ImDrawTextFlags_ = CInt
pattern ImDrawTextFlags_None :: ImDrawTextFlags_
pattern ImDrawTextFlags_None = #{const ImDrawTextFlags_None}
pattern ImDrawTextFlags_CpuFineClip :: ImDrawTextFlags_
pattern ImDrawTextFlags_CpuFineClip = #{const ImDrawTextFlags_CpuFineClip}
pattern ImDrawTextFlags_WrapKeepBlanks :: ImDrawTextFlags_
pattern ImDrawTextFlags_WrapKeepBlanks = #{const ImDrawTextFlags_WrapKeepBlanks}
pattern ImDrawTextFlags_StopOnNewLine :: ImDrawTextFlags_
pattern ImDrawTextFlags_StopOnNewLine = #{const ImDrawTextFlags_StopOnNewLine}
type ImGuiActivateFlags_ = CInt
pattern ImGuiActivateFlags_None :: ImGuiActivateFlags_
pattern ImGuiActivateFlags_None = #{const ImGuiActivateFlags_None}
pattern ImGuiActivateFlags_PreferInput :: ImGuiActivateFlags_
pattern ImGuiActivateFlags_PreferInput = #{const ImGuiActivateFlags_PreferInput}
pattern ImGuiActivateFlags_PreferTweak :: ImGuiActivateFlags_
pattern ImGuiActivateFlags_PreferTweak = #{const ImGuiActivateFlags_PreferTweak}
pattern ImGuiActivateFlags_TryToPreserveState :: ImGuiActivateFlags_
pattern ImGuiActivateFlags_TryToPreserveState = #{const ImGuiActivateFlags_TryToPreserveState}
pattern ImGuiActivateFlags_FromTabbing :: ImGuiActivateFlags_
pattern ImGuiActivateFlags_FromTabbing = #{const ImGuiActivateFlags_FromTabbing}
pattern ImGuiActivateFlags_FromShortcut :: ImGuiActivateFlags_
pattern ImGuiActivateFlags_FromShortcut = #{const ImGuiActivateFlags_FromShortcut}
pattern ImGuiActivateFlags_FromFocusApi :: ImGuiActivateFlags_
pattern ImGuiActivateFlags_FromFocusApi = #{const ImGuiActivateFlags_FromFocusApi}
type ImGuiAxis = CInt
pattern ImGuiAxis_None :: ImGuiAxis
pattern ImGuiAxis_None = #{const ImGuiAxis_None}
pattern ImGuiAxis_X :: ImGuiAxis
pattern ImGuiAxis_X = #{const ImGuiAxis_X}
pattern ImGuiAxis_Y :: ImGuiAxis
pattern ImGuiAxis_Y = #{const ImGuiAxis_Y}
type ImGuiButtonFlagsPrivate_ = CInt
pattern ImGuiButtonFlags_PressedOnClick :: ImGuiButtonFlagsPrivate_
pattern ImGuiButtonFlags_PressedOnClick = #{const ImGuiButtonFlags_PressedOnClick}
pattern ImGuiButtonFlags_PressedOnClickRelease :: ImGuiButtonFlagsPrivate_
pattern ImGuiButtonFlags_PressedOnClickRelease = #{const ImGuiButtonFlags_PressedOnClickRelease}
pattern ImGuiButtonFlags_PressedOnClickReleaseAnywhere :: ImGuiButtonFlagsPrivate_
pattern ImGuiButtonFlags_PressedOnClickReleaseAnywhere = #{const ImGuiButtonFlags_PressedOnClickReleaseAnywhere}
pattern ImGuiButtonFlags_PressedOnRelease :: ImGuiButtonFlagsPrivate_
pattern ImGuiButtonFlags_PressedOnRelease = #{const ImGuiButtonFlags_PressedOnRelease}
pattern ImGuiButtonFlags_PressedOnDoubleClick :: ImGuiButtonFlagsPrivate_
pattern ImGuiButtonFlags_PressedOnDoubleClick = #{const ImGuiButtonFlags_PressedOnDoubleClick}
pattern ImGuiButtonFlags_PressedOnDragDropHold :: ImGuiButtonFlagsPrivate_
pattern ImGuiButtonFlags_PressedOnDragDropHold = #{const ImGuiButtonFlags_PressedOnDragDropHold}
pattern ImGuiButtonFlags_FlattenChildren :: ImGuiButtonFlagsPrivate_
pattern ImGuiButtonFlags_FlattenChildren = #{const ImGuiButtonFlags_FlattenChildren}
pattern ImGuiButtonFlags_AlignTextBaseLine :: ImGuiButtonFlagsPrivate_
pattern ImGuiButtonFlags_AlignTextBaseLine = #{const ImGuiButtonFlags_AlignTextBaseLine}
pattern ImGuiButtonFlags_NoKeyModsAllowed :: ImGuiButtonFlagsPrivate_
pattern ImGuiButtonFlags_NoKeyModsAllowed = #{const ImGuiButtonFlags_NoKeyModsAllowed}
pattern ImGuiButtonFlags_NoHoldingActiveId :: ImGuiButtonFlagsPrivate_
pattern ImGuiButtonFlags_NoHoldingActiveId = #{const ImGuiButtonFlags_NoHoldingActiveId}
pattern ImGuiButtonFlags_NoNavFocus :: ImGuiButtonFlagsPrivate_
pattern ImGuiButtonFlags_NoNavFocus = #{const ImGuiButtonFlags_NoNavFocus}
pattern ImGuiButtonFlags_NoHoveredOnFocus :: ImGuiButtonFlagsPrivate_
pattern ImGuiButtonFlags_NoHoveredOnFocus = #{const ImGuiButtonFlags_NoHoveredOnFocus}
pattern ImGuiButtonFlags_NoSetKeyOwner :: ImGuiButtonFlagsPrivate_
pattern ImGuiButtonFlags_NoSetKeyOwner = #{const ImGuiButtonFlags_NoSetKeyOwner}
pattern ImGuiButtonFlags_NoTestKeyOwner :: ImGuiButtonFlagsPrivate_
pattern ImGuiButtonFlags_NoTestKeyOwner = #{const ImGuiButtonFlags_NoTestKeyOwner}
pattern ImGuiButtonFlags_NoFocus :: ImGuiButtonFlagsPrivate_
pattern ImGuiButtonFlags_NoFocus = #{const ImGuiButtonFlags_NoFocus}
pattern ImGuiButtonFlags_PressedOnMask_ :: ImGuiButtonFlagsPrivate_
pattern ImGuiButtonFlags_PressedOnMask_ = #{const ImGuiButtonFlags_PressedOnMask_}
pattern ImGuiButtonFlags_PressedOnDefault_ :: ImGuiButtonFlagsPrivate_
pattern ImGuiButtonFlags_PressedOnDefault_ = #{const ImGuiButtonFlags_PressedOnDefault_}
type ImGuiComboFlagsPrivate_ = CInt
pattern ImGuiComboFlags_CustomPreview :: ImGuiComboFlagsPrivate_
pattern ImGuiComboFlags_CustomPreview = #{const ImGuiComboFlags_CustomPreview}
type ImGuiContextHookType = CInt
pattern ImGuiContextHookType_NewFramePre :: ImGuiContextHookType
pattern ImGuiContextHookType_NewFramePre = #{const ImGuiContextHookType_NewFramePre}
pattern ImGuiContextHookType_NewFramePost :: ImGuiContextHookType
pattern ImGuiContextHookType_NewFramePost = #{const ImGuiContextHookType_NewFramePost}
pattern ImGuiContextHookType_EndFramePre :: ImGuiContextHookType
pattern ImGuiContextHookType_EndFramePre = #{const ImGuiContextHookType_EndFramePre}
pattern ImGuiContextHookType_EndFramePost :: ImGuiContextHookType
pattern ImGuiContextHookType_EndFramePost = #{const ImGuiContextHookType_EndFramePost}
pattern ImGuiContextHookType_RenderPre :: ImGuiContextHookType
pattern ImGuiContextHookType_RenderPre = #{const ImGuiContextHookType_RenderPre}
pattern ImGuiContextHookType_RenderPost :: ImGuiContextHookType
pattern ImGuiContextHookType_RenderPost = #{const ImGuiContextHookType_RenderPost}
pattern ImGuiContextHookType_Shutdown :: ImGuiContextHookType
pattern ImGuiContextHookType_Shutdown = #{const ImGuiContextHookType_Shutdown}
pattern ImGuiContextHookType_PendingRemoval_ :: ImGuiContextHookType
pattern ImGuiContextHookType_PendingRemoval_ = #{const ImGuiContextHookType_PendingRemoval_}
type ImGuiDataAuthority_ = CInt
pattern ImGuiDataAuthority_Auto :: ImGuiDataAuthority_
pattern ImGuiDataAuthority_Auto = #{const ImGuiDataAuthority_Auto}
pattern ImGuiDataAuthority_DockNode :: ImGuiDataAuthority_
pattern ImGuiDataAuthority_DockNode = #{const ImGuiDataAuthority_DockNode}
pattern ImGuiDataAuthority_Window :: ImGuiDataAuthority_
pattern ImGuiDataAuthority_Window = #{const ImGuiDataAuthority_Window}
type ImGuiDataTypePrivate_ = CInt
pattern ImGuiDataType_Pointer :: ImGuiDataTypePrivate_
pattern ImGuiDataType_Pointer = #{const ImGuiDataType_Pointer}
pattern ImGuiDataType_ID :: ImGuiDataTypePrivate_
pattern ImGuiDataType_ID = #{const ImGuiDataType_ID}
type ImGuiDebugLogFlags_ = CInt
pattern ImGuiDebugLogFlags_None :: ImGuiDebugLogFlags_
pattern ImGuiDebugLogFlags_None = #{const ImGuiDebugLogFlags_None}
pattern ImGuiDebugLogFlags_EventError :: ImGuiDebugLogFlags_
pattern ImGuiDebugLogFlags_EventError = #{const ImGuiDebugLogFlags_EventError}
pattern ImGuiDebugLogFlags_EventActiveId :: ImGuiDebugLogFlags_
pattern ImGuiDebugLogFlags_EventActiveId = #{const ImGuiDebugLogFlags_EventActiveId}
pattern ImGuiDebugLogFlags_EventFocus :: ImGuiDebugLogFlags_
pattern ImGuiDebugLogFlags_EventFocus = #{const ImGuiDebugLogFlags_EventFocus}
pattern ImGuiDebugLogFlags_EventPopup :: ImGuiDebugLogFlags_
pattern ImGuiDebugLogFlags_EventPopup = #{const ImGuiDebugLogFlags_EventPopup}
pattern ImGuiDebugLogFlags_EventNav :: ImGuiDebugLogFlags_
pattern ImGuiDebugLogFlags_EventNav = #{const ImGuiDebugLogFlags_EventNav}
pattern ImGuiDebugLogFlags_EventClipper :: ImGuiDebugLogFlags_
pattern ImGuiDebugLogFlags_EventClipper = #{const ImGuiDebugLogFlags_EventClipper}
pattern ImGuiDebugLogFlags_EventSelection :: ImGuiDebugLogFlags_
pattern ImGuiDebugLogFlags_EventSelection = #{const ImGuiDebugLogFlags_EventSelection}
pattern ImGuiDebugLogFlags_EventIO :: ImGuiDebugLogFlags_
pattern ImGuiDebugLogFlags_EventIO = #{const ImGuiDebugLogFlags_EventIO}
pattern ImGuiDebugLogFlags_EventFont :: ImGuiDebugLogFlags_
pattern ImGuiDebugLogFlags_EventFont = #{const ImGuiDebugLogFlags_EventFont}
pattern ImGuiDebugLogFlags_EventInputRouting :: ImGuiDebugLogFlags_
pattern ImGuiDebugLogFlags_EventInputRouting = #{const ImGuiDebugLogFlags_EventInputRouting}
pattern ImGuiDebugLogFlags_EventDocking :: ImGuiDebugLogFlags_
pattern ImGuiDebugLogFlags_EventDocking = #{const ImGuiDebugLogFlags_EventDocking}
pattern ImGuiDebugLogFlags_EventViewport :: ImGuiDebugLogFlags_
pattern ImGuiDebugLogFlags_EventViewport = #{const ImGuiDebugLogFlags_EventViewport}
pattern ImGuiDebugLogFlags_EventMask_ :: ImGuiDebugLogFlags_
pattern ImGuiDebugLogFlags_EventMask_ = #{const ImGuiDebugLogFlags_EventMask_}
pattern ImGuiDebugLogFlags_OutputToTTY :: ImGuiDebugLogFlags_
pattern ImGuiDebugLogFlags_OutputToTTY = #{const ImGuiDebugLogFlags_OutputToTTY}
pattern ImGuiDebugLogFlags_OutputToDebugger :: ImGuiDebugLogFlags_
pattern ImGuiDebugLogFlags_OutputToDebugger = #{const ImGuiDebugLogFlags_OutputToDebugger}
pattern ImGuiDebugLogFlags_OutputToTestEngine :: ImGuiDebugLogFlags_
pattern ImGuiDebugLogFlags_OutputToTestEngine = #{const ImGuiDebugLogFlags_OutputToTestEngine}
type ImGuiDockNodeFlagsPrivate_ = CInt
pattern ImGuiDockNodeFlags_DockSpace :: ImGuiDockNodeFlagsPrivate_
pattern ImGuiDockNodeFlags_DockSpace = #{const ImGuiDockNodeFlags_DockSpace}
pattern ImGuiDockNodeFlags_CentralNode :: ImGuiDockNodeFlagsPrivate_
pattern ImGuiDockNodeFlags_CentralNode = #{const ImGuiDockNodeFlags_CentralNode}
pattern ImGuiDockNodeFlags_NoTabBar :: ImGuiDockNodeFlagsPrivate_
pattern ImGuiDockNodeFlags_NoTabBar = #{const ImGuiDockNodeFlags_NoTabBar}
pattern ImGuiDockNodeFlags_HiddenTabBar :: ImGuiDockNodeFlagsPrivate_
pattern ImGuiDockNodeFlags_HiddenTabBar = #{const ImGuiDockNodeFlags_HiddenTabBar}
pattern ImGuiDockNodeFlags_NoWindowMenuButton :: ImGuiDockNodeFlagsPrivate_
pattern ImGuiDockNodeFlags_NoWindowMenuButton = #{const ImGuiDockNodeFlags_NoWindowMenuButton}
pattern ImGuiDockNodeFlags_NoCloseButton :: ImGuiDockNodeFlagsPrivate_
pattern ImGuiDockNodeFlags_NoCloseButton = #{const ImGuiDockNodeFlags_NoCloseButton}
pattern ImGuiDockNodeFlags_NoResizeX :: ImGuiDockNodeFlagsPrivate_
pattern ImGuiDockNodeFlags_NoResizeX = #{const ImGuiDockNodeFlags_NoResizeX}
pattern ImGuiDockNodeFlags_NoResizeY :: ImGuiDockNodeFlagsPrivate_
pattern ImGuiDockNodeFlags_NoResizeY = #{const ImGuiDockNodeFlags_NoResizeY}
pattern ImGuiDockNodeFlags_DockedWindowsInFocusRoute :: ImGuiDockNodeFlagsPrivate_
pattern ImGuiDockNodeFlags_DockedWindowsInFocusRoute = #{const ImGuiDockNodeFlags_DockedWindowsInFocusRoute}
pattern ImGuiDockNodeFlags_NoDockingSplitOther :: ImGuiDockNodeFlagsPrivate_
pattern ImGuiDockNodeFlags_NoDockingSplitOther = #{const ImGuiDockNodeFlags_NoDockingSplitOther}
pattern ImGuiDockNodeFlags_NoDockingOverMe :: ImGuiDockNodeFlagsPrivate_
pattern ImGuiDockNodeFlags_NoDockingOverMe = #{const ImGuiDockNodeFlags_NoDockingOverMe}
pattern ImGuiDockNodeFlags_NoDockingOverOther :: ImGuiDockNodeFlagsPrivate_
pattern ImGuiDockNodeFlags_NoDockingOverOther = #{const ImGuiDockNodeFlags_NoDockingOverOther}
pattern ImGuiDockNodeFlags_NoDockingOverEmpty :: ImGuiDockNodeFlagsPrivate_
pattern ImGuiDockNodeFlags_NoDockingOverEmpty = #{const ImGuiDockNodeFlags_NoDockingOverEmpty}
pattern ImGuiDockNodeFlags_NoDocking :: ImGuiDockNodeFlagsPrivate_
pattern ImGuiDockNodeFlags_NoDocking = #{const ImGuiDockNodeFlags_NoDocking}
pattern ImGuiDockNodeFlags_SharedFlagsInheritMask_ :: ImGuiDockNodeFlagsPrivate_
pattern ImGuiDockNodeFlags_SharedFlagsInheritMask_ = #{const ImGuiDockNodeFlags_SharedFlagsInheritMask_}
pattern ImGuiDockNodeFlags_NoResizeFlagsMask_ :: ImGuiDockNodeFlagsPrivate_
pattern ImGuiDockNodeFlags_NoResizeFlagsMask_ = #{const ImGuiDockNodeFlags_NoResizeFlagsMask_}
pattern ImGuiDockNodeFlags_LocalFlagsTransferMask_ :: ImGuiDockNodeFlagsPrivate_
pattern ImGuiDockNodeFlags_LocalFlagsTransferMask_ = #{const ImGuiDockNodeFlags_LocalFlagsTransferMask_}
pattern ImGuiDockNodeFlags_SavedFlagsMask_ :: ImGuiDockNodeFlagsPrivate_
pattern ImGuiDockNodeFlags_SavedFlagsMask_ = #{const ImGuiDockNodeFlags_SavedFlagsMask_}
type ImGuiDockNodeState = CInt
pattern ImGuiDockNodeState_Unknown :: ImGuiDockNodeState
pattern ImGuiDockNodeState_Unknown = #{const ImGuiDockNodeState_Unknown}
pattern ImGuiDockNodeState_HostWindowHiddenBecauseSingleWindow :: ImGuiDockNodeState
pattern ImGuiDockNodeState_HostWindowHiddenBecauseSingleWindow = #{const ImGuiDockNodeState_HostWindowHiddenBecauseSingleWindow}
pattern ImGuiDockNodeState_HostWindowHiddenBecauseWindowsAreResizing :: ImGuiDockNodeState
pattern ImGuiDockNodeState_HostWindowHiddenBecauseWindowsAreResizing = #{const ImGuiDockNodeState_HostWindowHiddenBecauseWindowsAreResizing}
pattern ImGuiDockNodeState_HostWindowVisible :: ImGuiDockNodeState
pattern ImGuiDockNodeState_HostWindowVisible = #{const ImGuiDockNodeState_HostWindowVisible}
type ImGuiFocusRequestFlags_ = CInt
pattern ImGuiFocusRequestFlags_None :: ImGuiFocusRequestFlags_
pattern ImGuiFocusRequestFlags_None = #{const ImGuiFocusRequestFlags_None}
pattern ImGuiFocusRequestFlags_RestoreFocusedChild :: ImGuiFocusRequestFlags_
pattern ImGuiFocusRequestFlags_RestoreFocusedChild = #{const ImGuiFocusRequestFlags_RestoreFocusedChild}
pattern ImGuiFocusRequestFlags_UnlessBelowModal :: ImGuiFocusRequestFlags_
pattern ImGuiFocusRequestFlags_UnlessBelowModal = #{const ImGuiFocusRequestFlags_UnlessBelowModal}
type ImGuiHoveredFlagsPrivate_ = CInt
pattern ImGuiHoveredFlags_DelayMask_ :: ImGuiHoveredFlagsPrivate_
pattern ImGuiHoveredFlags_DelayMask_ = #{const ImGuiHoveredFlags_DelayMask_}
pattern ImGuiHoveredFlags_AllowedMaskForIsWindowHovered :: ImGuiHoveredFlagsPrivate_
pattern ImGuiHoveredFlags_AllowedMaskForIsWindowHovered = #{const ImGuiHoveredFlags_AllowedMaskForIsWindowHovered}
pattern ImGuiHoveredFlags_AllowedMaskForIsItemHovered :: ImGuiHoveredFlagsPrivate_
pattern ImGuiHoveredFlags_AllowedMaskForIsItemHovered = #{const ImGuiHoveredFlags_AllowedMaskForIsItemHovered}
type ImGuiInputEventType = CInt
pattern ImGuiInputEventType_None :: ImGuiInputEventType
pattern ImGuiInputEventType_None = #{const ImGuiInputEventType_None}
pattern ImGuiInputEventType_MousePos :: ImGuiInputEventType
pattern ImGuiInputEventType_MousePos = #{const ImGuiInputEventType_MousePos}
pattern ImGuiInputEventType_MouseWheel :: ImGuiInputEventType
pattern ImGuiInputEventType_MouseWheel = #{const ImGuiInputEventType_MouseWheel}
pattern ImGuiInputEventType_MouseButton :: ImGuiInputEventType
pattern ImGuiInputEventType_MouseButton = #{const ImGuiInputEventType_MouseButton}
pattern ImGuiInputEventType_MouseViewport :: ImGuiInputEventType
pattern ImGuiInputEventType_MouseViewport = #{const ImGuiInputEventType_MouseViewport}
pattern ImGuiInputEventType_Key :: ImGuiInputEventType
pattern ImGuiInputEventType_Key = #{const ImGuiInputEventType_Key}
pattern ImGuiInputEventType_Text :: ImGuiInputEventType
pattern ImGuiInputEventType_Text = #{const ImGuiInputEventType_Text}
pattern ImGuiInputEventType_Focus :: ImGuiInputEventType
pattern ImGuiInputEventType_Focus = #{const ImGuiInputEventType_Focus}
pattern ImGuiInputEventType_COUNT :: ImGuiInputEventType
pattern ImGuiInputEventType_COUNT = #{const ImGuiInputEventType_COUNT}
type ImGuiInputFlagsPrivate_ = CInt
pattern ImGuiInputFlags_RepeatRateDefault :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_RepeatRateDefault = #{const ImGuiInputFlags_RepeatRateDefault}
pattern ImGuiInputFlags_RepeatRateNavMove :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_RepeatRateNavMove = #{const ImGuiInputFlags_RepeatRateNavMove}
pattern ImGuiInputFlags_RepeatRateNavTweak :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_RepeatRateNavTweak = #{const ImGuiInputFlags_RepeatRateNavTweak}
pattern ImGuiInputFlags_RepeatUntilRelease :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_RepeatUntilRelease = #{const ImGuiInputFlags_RepeatUntilRelease}
pattern ImGuiInputFlags_RepeatUntilKeyModsChange :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_RepeatUntilKeyModsChange = #{const ImGuiInputFlags_RepeatUntilKeyModsChange}
pattern ImGuiInputFlags_RepeatUntilKeyModsChangeFromNone :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_RepeatUntilKeyModsChangeFromNone = #{const ImGuiInputFlags_RepeatUntilKeyModsChangeFromNone}
pattern ImGuiInputFlags_RepeatUntilOtherKeyPress :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_RepeatUntilOtherKeyPress = #{const ImGuiInputFlags_RepeatUntilOtherKeyPress}
pattern ImGuiInputFlags_LockThisFrame :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_LockThisFrame = #{const ImGuiInputFlags_LockThisFrame}
pattern ImGuiInputFlags_LockUntilRelease :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_LockUntilRelease = #{const ImGuiInputFlags_LockUntilRelease}
pattern ImGuiInputFlags_CondHovered :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_CondHovered = #{const ImGuiInputFlags_CondHovered}
pattern ImGuiInputFlags_CondActive :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_CondActive = #{const ImGuiInputFlags_CondActive}
pattern ImGuiInputFlags_CondDefault_ :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_CondDefault_ = #{const ImGuiInputFlags_CondDefault_}
pattern ImGuiInputFlags_RepeatRateMask_ :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_RepeatRateMask_ = #{const ImGuiInputFlags_RepeatRateMask_}
pattern ImGuiInputFlags_RepeatUntilMask_ :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_RepeatUntilMask_ = #{const ImGuiInputFlags_RepeatUntilMask_}
pattern ImGuiInputFlags_RepeatMask_ :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_RepeatMask_ = #{const ImGuiInputFlags_RepeatMask_}
pattern ImGuiInputFlags_CondMask_ :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_CondMask_ = #{const ImGuiInputFlags_CondMask_}
pattern ImGuiInputFlags_RouteTypeMask_ :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_RouteTypeMask_ = #{const ImGuiInputFlags_RouteTypeMask_}
pattern ImGuiInputFlags_RouteOptionsMask_ :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_RouteOptionsMask_ = #{const ImGuiInputFlags_RouteOptionsMask_}
pattern ImGuiInputFlags_SupportedByIsKeyPressed :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_SupportedByIsKeyPressed = #{const ImGuiInputFlags_SupportedByIsKeyPressed}
pattern ImGuiInputFlags_SupportedByIsMouseClicked :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_SupportedByIsMouseClicked = #{const ImGuiInputFlags_SupportedByIsMouseClicked}
pattern ImGuiInputFlags_SupportedByShortcut :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_SupportedByShortcut = #{const ImGuiInputFlags_SupportedByShortcut}
pattern ImGuiInputFlags_SupportedBySetNextItemShortcut :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_SupportedBySetNextItemShortcut = #{const ImGuiInputFlags_SupportedBySetNextItemShortcut}
pattern ImGuiInputFlags_SupportedBySetKeyOwner :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_SupportedBySetKeyOwner = #{const ImGuiInputFlags_SupportedBySetKeyOwner}
pattern ImGuiInputFlags_SupportedBySetItemKeyOwner :: ImGuiInputFlagsPrivate_
pattern ImGuiInputFlags_SupportedBySetItemKeyOwner = #{const ImGuiInputFlags_SupportedBySetItemKeyOwner}
type ImGuiInputSource = CInt
pattern ImGuiInputSource_None :: ImGuiInputSource
pattern ImGuiInputSource_None = #{const ImGuiInputSource_None}
pattern ImGuiInputSource_Mouse :: ImGuiInputSource
pattern ImGuiInputSource_Mouse = #{const ImGuiInputSource_Mouse}
pattern ImGuiInputSource_Keyboard :: ImGuiInputSource
pattern ImGuiInputSource_Keyboard = #{const ImGuiInputSource_Keyboard}
pattern ImGuiInputSource_Gamepad :: ImGuiInputSource
pattern ImGuiInputSource_Gamepad = #{const ImGuiInputSource_Gamepad}
pattern ImGuiInputSource_COUNT :: ImGuiInputSource
pattern ImGuiInputSource_COUNT = #{const ImGuiInputSource_COUNT}
type ImGuiInputTextFlagsPrivate_ = CInt
pattern ImGuiInputTextFlags_Multiline :: ImGuiInputTextFlagsPrivate_
pattern ImGuiInputTextFlags_Multiline = #{const ImGuiInputTextFlags_Multiline}
pattern ImGuiInputTextFlags_TempInput :: ImGuiInputTextFlagsPrivate_
pattern ImGuiInputTextFlags_TempInput = #{const ImGuiInputTextFlags_TempInput}
pattern ImGuiInputTextFlags_LocalizeDecimalPoint :: ImGuiInputTextFlagsPrivate_
pattern ImGuiInputTextFlags_LocalizeDecimalPoint = #{const ImGuiInputTextFlags_LocalizeDecimalPoint}
type ImGuiItemFlagsPrivate_ = CInt
pattern ImGuiItemFlags_ReadOnly :: ImGuiItemFlagsPrivate_
pattern ImGuiItemFlags_ReadOnly = #{const ImGuiItemFlags_ReadOnly}
pattern ImGuiItemFlags_MixedValue :: ImGuiItemFlagsPrivate_
pattern ImGuiItemFlags_MixedValue = #{const ImGuiItemFlags_MixedValue}
pattern ImGuiItemFlags_NoWindowHoverableCheck :: ImGuiItemFlagsPrivate_
pattern ImGuiItemFlags_NoWindowHoverableCheck = #{const ImGuiItemFlags_NoWindowHoverableCheck}
pattern ImGuiItemFlags_AllowOverlap :: ImGuiItemFlagsPrivate_
pattern ImGuiItemFlags_AllowOverlap = #{const ImGuiItemFlags_AllowOverlap}
pattern ImGuiItemFlags_NoNavDisableMouseHover :: ImGuiItemFlagsPrivate_
pattern ImGuiItemFlags_NoNavDisableMouseHover = #{const ImGuiItemFlags_NoNavDisableMouseHover}
pattern ImGuiItemFlags_NoMarkEdited :: ImGuiItemFlagsPrivate_
pattern ImGuiItemFlags_NoMarkEdited = #{const ImGuiItemFlags_NoMarkEdited}
pattern ImGuiItemFlags_NoFocus :: ImGuiItemFlagsPrivate_
pattern ImGuiItemFlags_NoFocus = #{const ImGuiItemFlags_NoFocus}
pattern ImGuiItemFlags_Inputable :: ImGuiItemFlagsPrivate_
pattern ImGuiItemFlags_Inputable = #{const ImGuiItemFlags_Inputable}
pattern ImGuiItemFlags_HasSelectionUserData :: ImGuiItemFlagsPrivate_
pattern ImGuiItemFlags_HasSelectionUserData = #{const ImGuiItemFlags_HasSelectionUserData}
pattern ImGuiItemFlags_IsMultiSelect :: ImGuiItemFlagsPrivate_
pattern ImGuiItemFlags_IsMultiSelect = #{const ImGuiItemFlags_IsMultiSelect}
pattern ImGuiItemFlags_Default_ :: ImGuiItemFlagsPrivate_
pattern ImGuiItemFlags_Default_ = #{const ImGuiItemFlags_Default_}
type ImGuiItemStatusFlags_ = CInt
pattern ImGuiItemStatusFlags_None :: ImGuiItemStatusFlags_
pattern ImGuiItemStatusFlags_None = #{const ImGuiItemStatusFlags_None}
pattern ImGuiItemStatusFlags_HoveredRect :: ImGuiItemStatusFlags_
pattern ImGuiItemStatusFlags_HoveredRect = #{const ImGuiItemStatusFlags_HoveredRect}
pattern ImGuiItemStatusFlags_HasDisplayRect :: ImGuiItemStatusFlags_
pattern ImGuiItemStatusFlags_HasDisplayRect = #{const ImGuiItemStatusFlags_HasDisplayRect}
pattern ImGuiItemStatusFlags_Edited :: ImGuiItemStatusFlags_
pattern ImGuiItemStatusFlags_Edited = #{const ImGuiItemStatusFlags_Edited}
pattern ImGuiItemStatusFlags_ToggledSelection :: ImGuiItemStatusFlags_
pattern ImGuiItemStatusFlags_ToggledSelection = #{const ImGuiItemStatusFlags_ToggledSelection}
pattern ImGuiItemStatusFlags_ToggledOpen :: ImGuiItemStatusFlags_
pattern ImGuiItemStatusFlags_ToggledOpen = #{const ImGuiItemStatusFlags_ToggledOpen}
pattern ImGuiItemStatusFlags_HasDeactivated :: ImGuiItemStatusFlags_
pattern ImGuiItemStatusFlags_HasDeactivated = #{const ImGuiItemStatusFlags_HasDeactivated}
pattern ImGuiItemStatusFlags_Deactivated :: ImGuiItemStatusFlags_
pattern ImGuiItemStatusFlags_Deactivated = #{const ImGuiItemStatusFlags_Deactivated}
pattern ImGuiItemStatusFlags_HoveredWindow :: ImGuiItemStatusFlags_
pattern ImGuiItemStatusFlags_HoveredWindow = #{const ImGuiItemStatusFlags_HoveredWindow}
pattern ImGuiItemStatusFlags_Visible :: ImGuiItemStatusFlags_
pattern ImGuiItemStatusFlags_Visible = #{const ImGuiItemStatusFlags_Visible}
pattern ImGuiItemStatusFlags_HasClipRect :: ImGuiItemStatusFlags_
pattern ImGuiItemStatusFlags_HasClipRect = #{const ImGuiItemStatusFlags_HasClipRect}
pattern ImGuiItemStatusFlags_HasShortcut :: ImGuiItemStatusFlags_
pattern ImGuiItemStatusFlags_HasShortcut = #{const ImGuiItemStatusFlags_HasShortcut}
type ImGuiLayoutType_ = CInt
pattern ImGuiLayoutType_Horizontal :: ImGuiLayoutType_
pattern ImGuiLayoutType_Horizontal = #{const ImGuiLayoutType_Horizontal}
pattern ImGuiLayoutType_Vertical :: ImGuiLayoutType_
pattern ImGuiLayoutType_Vertical = #{const ImGuiLayoutType_Vertical}
type ImGuiLocKey = CInt
pattern ImGuiLocKey_VersionStr :: ImGuiLocKey
pattern ImGuiLocKey_VersionStr = #{const ImGuiLocKey_VersionStr}
pattern ImGuiLocKey_TableSizeOne :: ImGuiLocKey
pattern ImGuiLocKey_TableSizeOne = #{const ImGuiLocKey_TableSizeOne}
pattern ImGuiLocKey_TableSizeAllFit :: ImGuiLocKey
pattern ImGuiLocKey_TableSizeAllFit = #{const ImGuiLocKey_TableSizeAllFit}
pattern ImGuiLocKey_TableSizeAllDefault :: ImGuiLocKey
pattern ImGuiLocKey_TableSizeAllDefault = #{const ImGuiLocKey_TableSizeAllDefault}
pattern ImGuiLocKey_TableResetOrder :: ImGuiLocKey
pattern ImGuiLocKey_TableResetOrder = #{const ImGuiLocKey_TableResetOrder}
pattern ImGuiLocKey_WindowingMainMenuBar :: ImGuiLocKey
pattern ImGuiLocKey_WindowingMainMenuBar = #{const ImGuiLocKey_WindowingMainMenuBar}
pattern ImGuiLocKey_WindowingPopup :: ImGuiLocKey
pattern ImGuiLocKey_WindowingPopup = #{const ImGuiLocKey_WindowingPopup}
pattern ImGuiLocKey_WindowingUntitled :: ImGuiLocKey
pattern ImGuiLocKey_WindowingUntitled = #{const ImGuiLocKey_WindowingUntitled}
pattern ImGuiLocKey_OpenLink_s :: ImGuiLocKey
pattern ImGuiLocKey_OpenLink_s = #{const ImGuiLocKey_OpenLink_s}
pattern ImGuiLocKey_CopyLink :: ImGuiLocKey
pattern ImGuiLocKey_CopyLink = #{const ImGuiLocKey_CopyLink}
pattern ImGuiLocKey_DockingHideTabBar :: ImGuiLocKey
pattern ImGuiLocKey_DockingHideTabBar = #{const ImGuiLocKey_DockingHideTabBar}
pattern ImGuiLocKey_DockingHoldShiftToDock :: ImGuiLocKey
pattern ImGuiLocKey_DockingHoldShiftToDock = #{const ImGuiLocKey_DockingHoldShiftToDock}
pattern ImGuiLocKey_DockingDragToUndockOrMoveNode :: ImGuiLocKey
pattern ImGuiLocKey_DockingDragToUndockOrMoveNode = #{const ImGuiLocKey_DockingDragToUndockOrMoveNode}
pattern ImGuiLocKey_COUNT :: ImGuiLocKey
pattern ImGuiLocKey_COUNT = #{const ImGuiLocKey_COUNT}
type ImGuiLogFlags_ = CInt
pattern ImGuiLogFlags_None :: ImGuiLogFlags_
pattern ImGuiLogFlags_None = #{const ImGuiLogFlags_None}
pattern ImGuiLogFlags_OutputTTY :: ImGuiLogFlags_
pattern ImGuiLogFlags_OutputTTY = #{const ImGuiLogFlags_OutputTTY}
pattern ImGuiLogFlags_OutputFile :: ImGuiLogFlags_
pattern ImGuiLogFlags_OutputFile = #{const ImGuiLogFlags_OutputFile}
pattern ImGuiLogFlags_OutputBuffer :: ImGuiLogFlags_
pattern ImGuiLogFlags_OutputBuffer = #{const ImGuiLogFlags_OutputBuffer}
pattern ImGuiLogFlags_OutputClipboard :: ImGuiLogFlags_
pattern ImGuiLogFlags_OutputClipboard = #{const ImGuiLogFlags_OutputClipboard}
pattern ImGuiLogFlags_OutputMask_ :: ImGuiLogFlags_
pattern ImGuiLogFlags_OutputMask_ = #{const ImGuiLogFlags_OutputMask_}
type ImGuiNavLayer = CInt
pattern ImGuiNavLayer_Main :: ImGuiNavLayer
pattern ImGuiNavLayer_Main = #{const ImGuiNavLayer_Main}
pattern ImGuiNavLayer_Menu :: ImGuiNavLayer
pattern ImGuiNavLayer_Menu = #{const ImGuiNavLayer_Menu}
pattern ImGuiNavLayer_COUNT :: ImGuiNavLayer
pattern ImGuiNavLayer_COUNT = #{const ImGuiNavLayer_COUNT}
type ImGuiNavMoveFlags_ = CInt
pattern ImGuiNavMoveFlags_None :: ImGuiNavMoveFlags_
pattern ImGuiNavMoveFlags_None = #{const ImGuiNavMoveFlags_None}
pattern ImGuiNavMoveFlags_LoopX :: ImGuiNavMoveFlags_
pattern ImGuiNavMoveFlags_LoopX = #{const ImGuiNavMoveFlags_LoopX}
pattern ImGuiNavMoveFlags_LoopY :: ImGuiNavMoveFlags_
pattern ImGuiNavMoveFlags_LoopY = #{const ImGuiNavMoveFlags_LoopY}
pattern ImGuiNavMoveFlags_WrapX :: ImGuiNavMoveFlags_
pattern ImGuiNavMoveFlags_WrapX = #{const ImGuiNavMoveFlags_WrapX}
pattern ImGuiNavMoveFlags_WrapY :: ImGuiNavMoveFlags_
pattern ImGuiNavMoveFlags_WrapY = #{const ImGuiNavMoveFlags_WrapY}
pattern ImGuiNavMoveFlags_WrapMask_ :: ImGuiNavMoveFlags_
pattern ImGuiNavMoveFlags_WrapMask_ = #{const ImGuiNavMoveFlags_WrapMask_}
pattern ImGuiNavMoveFlags_AllowCurrentNavId :: ImGuiNavMoveFlags_
pattern ImGuiNavMoveFlags_AllowCurrentNavId = #{const ImGuiNavMoveFlags_AllowCurrentNavId}
pattern ImGuiNavMoveFlags_AlsoScoreVisibleSet :: ImGuiNavMoveFlags_
pattern ImGuiNavMoveFlags_AlsoScoreVisibleSet = #{const ImGuiNavMoveFlags_AlsoScoreVisibleSet}
pattern ImGuiNavMoveFlags_ScrollToEdgeY :: ImGuiNavMoveFlags_
pattern ImGuiNavMoveFlags_ScrollToEdgeY = #{const ImGuiNavMoveFlags_ScrollToEdgeY}
pattern ImGuiNavMoveFlags_Forwarded :: ImGuiNavMoveFlags_
pattern ImGuiNavMoveFlags_Forwarded = #{const ImGuiNavMoveFlags_Forwarded}
pattern ImGuiNavMoveFlags_DebugNoResult :: ImGuiNavMoveFlags_
pattern ImGuiNavMoveFlags_DebugNoResult = #{const ImGuiNavMoveFlags_DebugNoResult}
pattern ImGuiNavMoveFlags_FocusApi :: ImGuiNavMoveFlags_
pattern ImGuiNavMoveFlags_FocusApi = #{const ImGuiNavMoveFlags_FocusApi}
pattern ImGuiNavMoveFlags_IsTabbing :: ImGuiNavMoveFlags_
pattern ImGuiNavMoveFlags_IsTabbing = #{const ImGuiNavMoveFlags_IsTabbing}
pattern ImGuiNavMoveFlags_IsPageMove :: ImGuiNavMoveFlags_
pattern ImGuiNavMoveFlags_IsPageMove = #{const ImGuiNavMoveFlags_IsPageMove}
pattern ImGuiNavMoveFlags_Activate :: ImGuiNavMoveFlags_
pattern ImGuiNavMoveFlags_Activate = #{const ImGuiNavMoveFlags_Activate}
pattern ImGuiNavMoveFlags_NoSelect :: ImGuiNavMoveFlags_
pattern ImGuiNavMoveFlags_NoSelect = #{const ImGuiNavMoveFlags_NoSelect}
pattern ImGuiNavMoveFlags_NoSetNavCursorVisible :: ImGuiNavMoveFlags_
pattern ImGuiNavMoveFlags_NoSetNavCursorVisible = #{const ImGuiNavMoveFlags_NoSetNavCursorVisible}
pattern ImGuiNavMoveFlags_NoClearActiveId :: ImGuiNavMoveFlags_
pattern ImGuiNavMoveFlags_NoClearActiveId = #{const ImGuiNavMoveFlags_NoClearActiveId}
type ImGuiNavRenderCursorFlags_ = CInt
pattern ImGuiNavRenderCursorFlags_None :: ImGuiNavRenderCursorFlags_
pattern ImGuiNavRenderCursorFlags_None = #{const ImGuiNavRenderCursorFlags_None}
pattern ImGuiNavRenderCursorFlags_Compact :: ImGuiNavRenderCursorFlags_
pattern ImGuiNavRenderCursorFlags_Compact = #{const ImGuiNavRenderCursorFlags_Compact}
pattern ImGuiNavRenderCursorFlags_AlwaysDraw :: ImGuiNavRenderCursorFlags_
pattern ImGuiNavRenderCursorFlags_AlwaysDraw = #{const ImGuiNavRenderCursorFlags_AlwaysDraw}
pattern ImGuiNavRenderCursorFlags_NoRounding :: ImGuiNavRenderCursorFlags_
pattern ImGuiNavRenderCursorFlags_NoRounding = #{const ImGuiNavRenderCursorFlags_NoRounding}
pattern ImGuiNavHighlightFlags_None :: ImGuiNavRenderCursorFlags_
pattern ImGuiNavHighlightFlags_None = #{const ImGuiNavHighlightFlags_None}
pattern ImGuiNavHighlightFlags_Compact :: ImGuiNavRenderCursorFlags_
pattern ImGuiNavHighlightFlags_Compact = #{const ImGuiNavHighlightFlags_Compact}
pattern ImGuiNavHighlightFlags_AlwaysDraw :: ImGuiNavRenderCursorFlags_
pattern ImGuiNavHighlightFlags_AlwaysDraw = #{const ImGuiNavHighlightFlags_AlwaysDraw}
pattern ImGuiNavHighlightFlags_NoRounding :: ImGuiNavRenderCursorFlags_
pattern ImGuiNavHighlightFlags_NoRounding = #{const ImGuiNavHighlightFlags_NoRounding}
type ImGuiNextItemDataFlags_ = CInt
pattern ImGuiNextItemDataFlags_None :: ImGuiNextItemDataFlags_
pattern ImGuiNextItemDataFlags_None = #{const ImGuiNextItemDataFlags_None}
pattern ImGuiNextItemDataFlags_HasWidth :: ImGuiNextItemDataFlags_
pattern ImGuiNextItemDataFlags_HasWidth = #{const ImGuiNextItemDataFlags_HasWidth}
pattern ImGuiNextItemDataFlags_HasOpen :: ImGuiNextItemDataFlags_
pattern ImGuiNextItemDataFlags_HasOpen = #{const ImGuiNextItemDataFlags_HasOpen}
pattern ImGuiNextItemDataFlags_HasShortcut :: ImGuiNextItemDataFlags_
pattern ImGuiNextItemDataFlags_HasShortcut = #{const ImGuiNextItemDataFlags_HasShortcut}
pattern ImGuiNextItemDataFlags_HasRefVal :: ImGuiNextItemDataFlags_
pattern ImGuiNextItemDataFlags_HasRefVal = #{const ImGuiNextItemDataFlags_HasRefVal}
pattern ImGuiNextItemDataFlags_HasStorageID :: ImGuiNextItemDataFlags_
pattern ImGuiNextItemDataFlags_HasStorageID = #{const ImGuiNextItemDataFlags_HasStorageID}
pattern ImGuiNextItemDataFlags_HasColorMarker :: ImGuiNextItemDataFlags_
pattern ImGuiNextItemDataFlags_HasColorMarker = #{const ImGuiNextItemDataFlags_HasColorMarker}
type ImGuiNextWindowDataFlags_ = CInt
pattern ImGuiNextWindowDataFlags_None :: ImGuiNextWindowDataFlags_
pattern ImGuiNextWindowDataFlags_None = #{const ImGuiNextWindowDataFlags_None}
pattern ImGuiNextWindowDataFlags_HasPos :: ImGuiNextWindowDataFlags_
pattern ImGuiNextWindowDataFlags_HasPos = #{const ImGuiNextWindowDataFlags_HasPos}
pattern ImGuiNextWindowDataFlags_HasSize :: ImGuiNextWindowDataFlags_
pattern ImGuiNextWindowDataFlags_HasSize = #{const ImGuiNextWindowDataFlags_HasSize}
pattern ImGuiNextWindowDataFlags_HasContentSize :: ImGuiNextWindowDataFlags_
pattern ImGuiNextWindowDataFlags_HasContentSize = #{const ImGuiNextWindowDataFlags_HasContentSize}
pattern ImGuiNextWindowDataFlags_HasCollapsed :: ImGuiNextWindowDataFlags_
pattern ImGuiNextWindowDataFlags_HasCollapsed = #{const ImGuiNextWindowDataFlags_HasCollapsed}
pattern ImGuiNextWindowDataFlags_HasSizeConstraint :: ImGuiNextWindowDataFlags_
pattern ImGuiNextWindowDataFlags_HasSizeConstraint = #{const ImGuiNextWindowDataFlags_HasSizeConstraint}
pattern ImGuiNextWindowDataFlags_HasFocus :: ImGuiNextWindowDataFlags_
pattern ImGuiNextWindowDataFlags_HasFocus = #{const ImGuiNextWindowDataFlags_HasFocus}
pattern ImGuiNextWindowDataFlags_HasBgAlpha :: ImGuiNextWindowDataFlags_
pattern ImGuiNextWindowDataFlags_HasBgAlpha = #{const ImGuiNextWindowDataFlags_HasBgAlpha}
pattern ImGuiNextWindowDataFlags_HasScroll :: ImGuiNextWindowDataFlags_
pattern ImGuiNextWindowDataFlags_HasScroll = #{const ImGuiNextWindowDataFlags_HasScroll}
pattern ImGuiNextWindowDataFlags_HasWindowFlags :: ImGuiNextWindowDataFlags_
pattern ImGuiNextWindowDataFlags_HasWindowFlags = #{const ImGuiNextWindowDataFlags_HasWindowFlags}
pattern ImGuiNextWindowDataFlags_HasChildFlags :: ImGuiNextWindowDataFlags_
pattern ImGuiNextWindowDataFlags_HasChildFlags = #{const ImGuiNextWindowDataFlags_HasChildFlags}
pattern ImGuiNextWindowDataFlags_HasRefreshPolicy :: ImGuiNextWindowDataFlags_
pattern ImGuiNextWindowDataFlags_HasRefreshPolicy = #{const ImGuiNextWindowDataFlags_HasRefreshPolicy}
pattern ImGuiNextWindowDataFlags_HasViewport :: ImGuiNextWindowDataFlags_
pattern ImGuiNextWindowDataFlags_HasViewport = #{const ImGuiNextWindowDataFlags_HasViewport}
pattern ImGuiNextWindowDataFlags_HasDock :: ImGuiNextWindowDataFlags_
pattern ImGuiNextWindowDataFlags_HasDock = #{const ImGuiNextWindowDataFlags_HasDock}
pattern ImGuiNextWindowDataFlags_HasWindowClass :: ImGuiNextWindowDataFlags_
pattern ImGuiNextWindowDataFlags_HasWindowClass = #{const ImGuiNextWindowDataFlags_HasWindowClass}
type ImGuiOldColumnFlags_ = CInt
pattern ImGuiOldColumnFlags_None :: ImGuiOldColumnFlags_
pattern ImGuiOldColumnFlags_None = #{const ImGuiOldColumnFlags_None}
pattern ImGuiOldColumnFlags_NoBorder :: ImGuiOldColumnFlags_
pattern ImGuiOldColumnFlags_NoBorder = #{const ImGuiOldColumnFlags_NoBorder}
pattern ImGuiOldColumnFlags_NoResize :: ImGuiOldColumnFlags_
pattern ImGuiOldColumnFlags_NoResize = #{const ImGuiOldColumnFlags_NoResize}
pattern ImGuiOldColumnFlags_NoPreserveWidths :: ImGuiOldColumnFlags_
pattern ImGuiOldColumnFlags_NoPreserveWidths = #{const ImGuiOldColumnFlags_NoPreserveWidths}
pattern ImGuiOldColumnFlags_NoForceWithinWindow :: ImGuiOldColumnFlags_
pattern ImGuiOldColumnFlags_NoForceWithinWindow = #{const ImGuiOldColumnFlags_NoForceWithinWindow}
pattern ImGuiOldColumnFlags_GrowParentContentsSize :: ImGuiOldColumnFlags_
pattern ImGuiOldColumnFlags_GrowParentContentsSize = #{const ImGuiOldColumnFlags_GrowParentContentsSize}
type ImGuiPlotType = CInt
pattern ImGuiPlotType_Lines :: ImGuiPlotType
pattern ImGuiPlotType_Lines = #{const ImGuiPlotType_Lines}
pattern ImGuiPlotType_Histogram :: ImGuiPlotType
pattern ImGuiPlotType_Histogram = #{const ImGuiPlotType_Histogram}
type ImGuiPopupPositionPolicy = CInt
pattern ImGuiPopupPositionPolicy_Default :: ImGuiPopupPositionPolicy
pattern ImGuiPopupPositionPolicy_Default = #{const ImGuiPopupPositionPolicy_Default}
pattern ImGuiPopupPositionPolicy_ComboBox :: ImGuiPopupPositionPolicy
pattern ImGuiPopupPositionPolicy_ComboBox = #{const ImGuiPopupPositionPolicy_ComboBox}
pattern ImGuiPopupPositionPolicy_Tooltip :: ImGuiPopupPositionPolicy
pattern ImGuiPopupPositionPolicy_Tooltip = #{const ImGuiPopupPositionPolicy_Tooltip}
type ImGuiScrollFlags_ = CInt
pattern ImGuiScrollFlags_None :: ImGuiScrollFlags_
pattern ImGuiScrollFlags_None = #{const ImGuiScrollFlags_None}
pattern ImGuiScrollFlags_KeepVisibleEdgeX :: ImGuiScrollFlags_
pattern ImGuiScrollFlags_KeepVisibleEdgeX = #{const ImGuiScrollFlags_KeepVisibleEdgeX}
pattern ImGuiScrollFlags_KeepVisibleEdgeY :: ImGuiScrollFlags_
pattern ImGuiScrollFlags_KeepVisibleEdgeY = #{const ImGuiScrollFlags_KeepVisibleEdgeY}
pattern ImGuiScrollFlags_KeepVisibleCenterX :: ImGuiScrollFlags_
pattern ImGuiScrollFlags_KeepVisibleCenterX = #{const ImGuiScrollFlags_KeepVisibleCenterX}
pattern ImGuiScrollFlags_KeepVisibleCenterY :: ImGuiScrollFlags_
pattern ImGuiScrollFlags_KeepVisibleCenterY = #{const ImGuiScrollFlags_KeepVisibleCenterY}
pattern ImGuiScrollFlags_AlwaysCenterX :: ImGuiScrollFlags_
pattern ImGuiScrollFlags_AlwaysCenterX = #{const ImGuiScrollFlags_AlwaysCenterX}
pattern ImGuiScrollFlags_AlwaysCenterY :: ImGuiScrollFlags_
pattern ImGuiScrollFlags_AlwaysCenterY = #{const ImGuiScrollFlags_AlwaysCenterY}
pattern ImGuiScrollFlags_NoScrollParent :: ImGuiScrollFlags_
pattern ImGuiScrollFlags_NoScrollParent = #{const ImGuiScrollFlags_NoScrollParent}
pattern ImGuiScrollFlags_MaskX_ :: ImGuiScrollFlags_
pattern ImGuiScrollFlags_MaskX_ = #{const ImGuiScrollFlags_MaskX_}
pattern ImGuiScrollFlags_MaskY_ :: ImGuiScrollFlags_
pattern ImGuiScrollFlags_MaskY_ = #{const ImGuiScrollFlags_MaskY_}
type ImGuiSelectableFlagsPrivate_ = CInt
pattern ImGuiSelectableFlags_NoHoldingActiveID :: ImGuiSelectableFlagsPrivate_
pattern ImGuiSelectableFlags_NoHoldingActiveID = #{const ImGuiSelectableFlags_NoHoldingActiveID}
pattern ImGuiSelectableFlags_SelectOnClick :: ImGuiSelectableFlagsPrivate_
pattern ImGuiSelectableFlags_SelectOnClick = #{const ImGuiSelectableFlags_SelectOnClick}
pattern ImGuiSelectableFlags_SelectOnRelease :: ImGuiSelectableFlagsPrivate_
pattern ImGuiSelectableFlags_SelectOnRelease = #{const ImGuiSelectableFlags_SelectOnRelease}
pattern ImGuiSelectableFlags_SpanAvailWidth :: ImGuiSelectableFlagsPrivate_
pattern ImGuiSelectableFlags_SpanAvailWidth = #{const ImGuiSelectableFlags_SpanAvailWidth}
pattern ImGuiSelectableFlags_SetNavIdOnHover :: ImGuiSelectableFlagsPrivate_
pattern ImGuiSelectableFlags_SetNavIdOnHover = #{const ImGuiSelectableFlags_SetNavIdOnHover}
pattern ImGuiSelectableFlags_NoPadWithHalfSpacing :: ImGuiSelectableFlagsPrivate_
pattern ImGuiSelectableFlags_NoPadWithHalfSpacing = #{const ImGuiSelectableFlags_NoPadWithHalfSpacing}
pattern ImGuiSelectableFlags_NoSetKeyOwner :: ImGuiSelectableFlagsPrivate_
pattern ImGuiSelectableFlags_NoSetKeyOwner = #{const ImGuiSelectableFlags_NoSetKeyOwner}
type ImGuiSeparatorFlags_ = CInt
pattern ImGuiSeparatorFlags_None :: ImGuiSeparatorFlags_
pattern ImGuiSeparatorFlags_None = #{const ImGuiSeparatorFlags_None}
pattern ImGuiSeparatorFlags_Horizontal :: ImGuiSeparatorFlags_
pattern ImGuiSeparatorFlags_Horizontal = #{const ImGuiSeparatorFlags_Horizontal}
pattern ImGuiSeparatorFlags_Vertical :: ImGuiSeparatorFlags_
pattern ImGuiSeparatorFlags_Vertical = #{const ImGuiSeparatorFlags_Vertical}
pattern ImGuiSeparatorFlags_SpanAllColumns :: ImGuiSeparatorFlags_
pattern ImGuiSeparatorFlags_SpanAllColumns = #{const ImGuiSeparatorFlags_SpanAllColumns}
type ImGuiSliderFlagsPrivate_ = CInt
pattern ImGuiSliderFlags_Vertical :: ImGuiSliderFlagsPrivate_
pattern ImGuiSliderFlags_Vertical = #{const ImGuiSliderFlags_Vertical}
pattern ImGuiSliderFlags_ReadOnly :: ImGuiSliderFlagsPrivate_
pattern ImGuiSliderFlags_ReadOnly = #{const ImGuiSliderFlags_ReadOnly}
type ImGuiTabBarFlagsPrivate_ = CInt
pattern ImGuiTabBarFlags_DockNode :: ImGuiTabBarFlagsPrivate_
pattern ImGuiTabBarFlags_DockNode = #{const ImGuiTabBarFlags_DockNode}
pattern ImGuiTabBarFlags_IsFocused :: ImGuiTabBarFlagsPrivate_
pattern ImGuiTabBarFlags_IsFocused = #{const ImGuiTabBarFlags_IsFocused}
pattern ImGuiTabBarFlags_SaveSettings :: ImGuiTabBarFlagsPrivate_
pattern ImGuiTabBarFlags_SaveSettings = #{const ImGuiTabBarFlags_SaveSettings}
type ImGuiTabItemFlagsPrivate_ = CInt
pattern ImGuiTabItemFlags_SectionMask_ :: ImGuiTabItemFlagsPrivate_
pattern ImGuiTabItemFlags_SectionMask_ = #{const ImGuiTabItemFlags_SectionMask_}
pattern ImGuiTabItemFlags_NoCloseButton :: ImGuiTabItemFlagsPrivate_
pattern ImGuiTabItemFlags_NoCloseButton = #{const ImGuiTabItemFlags_NoCloseButton}
pattern ImGuiTabItemFlags_Button :: ImGuiTabItemFlagsPrivate_
pattern ImGuiTabItemFlags_Button = #{const ImGuiTabItemFlags_Button}
pattern ImGuiTabItemFlags_Invisible :: ImGuiTabItemFlagsPrivate_
pattern ImGuiTabItemFlags_Invisible = #{const ImGuiTabItemFlags_Invisible}
pattern ImGuiTabItemFlags_Unsorted :: ImGuiTabItemFlagsPrivate_
pattern ImGuiTabItemFlags_Unsorted = #{const ImGuiTabItemFlags_Unsorted}
type ImGuiTextFlags_ = CInt
pattern ImGuiTextFlags_None :: ImGuiTextFlags_
pattern ImGuiTextFlags_None = #{const ImGuiTextFlags_None}
pattern ImGuiTextFlags_NoWidthForLargeClippedText :: ImGuiTextFlags_
pattern ImGuiTextFlags_NoWidthForLargeClippedText = #{const ImGuiTextFlags_NoWidthForLargeClippedText}
type ImGuiTooltipFlags_ = CInt
pattern ImGuiTooltipFlags_None :: ImGuiTooltipFlags_
pattern ImGuiTooltipFlags_None = #{const ImGuiTooltipFlags_None}
pattern ImGuiTooltipFlags_OverridePrevious :: ImGuiTooltipFlags_
pattern ImGuiTooltipFlags_OverridePrevious = #{const ImGuiTooltipFlags_OverridePrevious}
type ImGuiTreeNodeFlagsPrivate_ = CInt
pattern ImGuiTreeNodeFlags_NoNavFocus :: ImGuiTreeNodeFlagsPrivate_
pattern ImGuiTreeNodeFlags_NoNavFocus = #{const ImGuiTreeNodeFlags_NoNavFocus}
pattern ImGuiTreeNodeFlags_ClipLabelForTrailingButton :: ImGuiTreeNodeFlagsPrivate_
pattern ImGuiTreeNodeFlags_ClipLabelForTrailingButton = #{const ImGuiTreeNodeFlags_ClipLabelForTrailingButton}
pattern ImGuiTreeNodeFlags_UpsideDownArrow :: ImGuiTreeNodeFlagsPrivate_
pattern ImGuiTreeNodeFlags_UpsideDownArrow = #{const ImGuiTreeNodeFlags_UpsideDownArrow}
pattern ImGuiTreeNodeFlags_OpenOnMask_ :: ImGuiTreeNodeFlagsPrivate_
pattern ImGuiTreeNodeFlags_OpenOnMask_ = #{const ImGuiTreeNodeFlags_OpenOnMask_}
pattern ImGuiTreeNodeFlags_DrawLinesMask_ :: ImGuiTreeNodeFlagsPrivate_
pattern ImGuiTreeNodeFlags_DrawLinesMask_ = #{const ImGuiTreeNodeFlags_DrawLinesMask_}
type ImGuiTypingSelectFlags_ = CInt
pattern ImGuiTypingSelectFlags_None :: ImGuiTypingSelectFlags_
pattern ImGuiTypingSelectFlags_None = #{const ImGuiTypingSelectFlags_None}
pattern ImGuiTypingSelectFlags_AllowBackspace :: ImGuiTypingSelectFlags_
pattern ImGuiTypingSelectFlags_AllowBackspace = #{const ImGuiTypingSelectFlags_AllowBackspace}
pattern ImGuiTypingSelectFlags_AllowSingleCharMode :: ImGuiTypingSelectFlags_
pattern ImGuiTypingSelectFlags_AllowSingleCharMode = #{const ImGuiTypingSelectFlags_AllowSingleCharMode}
type ImGuiWindowBgClickFlags_ = CInt
pattern ImGuiWindowBgClickFlags_None :: ImGuiWindowBgClickFlags_
pattern ImGuiWindowBgClickFlags_None = #{const ImGuiWindowBgClickFlags_None}
pattern ImGuiWindowBgClickFlags_Move :: ImGuiWindowBgClickFlags_
pattern ImGuiWindowBgClickFlags_Move = #{const ImGuiWindowBgClickFlags_Move}
type ImGuiWindowDockStyleCol = CInt
pattern ImGuiWindowDockStyleCol_Text :: ImGuiWindowDockStyleCol
pattern ImGuiWindowDockStyleCol_Text = #{const ImGuiWindowDockStyleCol_Text}
pattern ImGuiWindowDockStyleCol_TabHovered :: ImGuiWindowDockStyleCol
pattern ImGuiWindowDockStyleCol_TabHovered = #{const ImGuiWindowDockStyleCol_TabHovered}
pattern ImGuiWindowDockStyleCol_TabFocused :: ImGuiWindowDockStyleCol
pattern ImGuiWindowDockStyleCol_TabFocused = #{const ImGuiWindowDockStyleCol_TabFocused}
pattern ImGuiWindowDockStyleCol_TabSelected :: ImGuiWindowDockStyleCol
pattern ImGuiWindowDockStyleCol_TabSelected = #{const ImGuiWindowDockStyleCol_TabSelected}
pattern ImGuiWindowDockStyleCol_TabSelectedOverline :: ImGuiWindowDockStyleCol
pattern ImGuiWindowDockStyleCol_TabSelectedOverline = #{const ImGuiWindowDockStyleCol_TabSelectedOverline}
pattern ImGuiWindowDockStyleCol_TabDimmed :: ImGuiWindowDockStyleCol
pattern ImGuiWindowDockStyleCol_TabDimmed = #{const ImGuiWindowDockStyleCol_TabDimmed}
pattern ImGuiWindowDockStyleCol_TabDimmedSelected :: ImGuiWindowDockStyleCol
pattern ImGuiWindowDockStyleCol_TabDimmedSelected = #{const ImGuiWindowDockStyleCol_TabDimmedSelected}
pattern ImGuiWindowDockStyleCol_TabDimmedSelectedOverline :: ImGuiWindowDockStyleCol
pattern ImGuiWindowDockStyleCol_TabDimmedSelectedOverline = #{const ImGuiWindowDockStyleCol_TabDimmedSelectedOverline}
pattern ImGuiWindowDockStyleCol_UnsavedMarker :: ImGuiWindowDockStyleCol
pattern ImGuiWindowDockStyleCol_UnsavedMarker = #{const ImGuiWindowDockStyleCol_UnsavedMarker}
pattern ImGuiWindowDockStyleCol_COUNT :: ImGuiWindowDockStyleCol
pattern ImGuiWindowDockStyleCol_COUNT = #{const ImGuiWindowDockStyleCol_COUNT}
type ImGuiWindowRefreshFlags_ = CInt
pattern ImGuiWindowRefreshFlags_None :: ImGuiWindowRefreshFlags_
pattern ImGuiWindowRefreshFlags_None = #{const ImGuiWindowRefreshFlags_None}
pattern ImGuiWindowRefreshFlags_TryToAvoidRefresh :: ImGuiWindowRefreshFlags_
pattern ImGuiWindowRefreshFlags_TryToAvoidRefresh = #{const ImGuiWindowRefreshFlags_TryToAvoidRefresh}
pattern ImGuiWindowRefreshFlags_RefreshOnHover :: ImGuiWindowRefreshFlags_
pattern ImGuiWindowRefreshFlags_RefreshOnHover = #{const ImGuiWindowRefreshFlags_RefreshOnHover}
pattern ImGuiWindowRefreshFlags_RefreshOnFocus :: ImGuiWindowRefreshFlags_
pattern ImGuiWindowRefreshFlags_RefreshOnFocus = #{const ImGuiWindowRefreshFlags_RefreshOnFocus}
type ImWcharClass = CInt
pattern ImWcharClass_Blank :: ImWcharClass
pattern ImWcharClass_Blank = #{const ImWcharClass_Blank}
pattern ImWcharClass_Punct :: ImWcharClass
pattern ImWcharClass_Punct = #{const ImWcharClass_Punct}
pattern ImWcharClass_Other :: ImWcharClass
pattern ImWcharClass_Other = #{const ImWcharClass_Other}

-- defines

pattern DOCKING_HOST_DRAW_CHANNEL_BG :: CInt
pattern DOCKING_HOST_DRAW_CHANNEL_BG = #{const DOCKING_HOST_DRAW_CHANNEL_BG}
pattern DOCKING_HOST_DRAW_CHANNEL_FG :: CInt
pattern DOCKING_HOST_DRAW_CHANNEL_FG = #{const DOCKING_HOST_DRAW_CHANNEL_FG}
pattern IMGUI_FONT_SIZE_MAX :: CInt
pattern IMGUI_FONT_SIZE_MAX = #{const IMGUI_FONT_SIZE_MAX}
pattern IMGUI_FONT_SIZE_THRESHOLD_FOR_LOADADVANCEXONLYMODE :: CInt
pattern IMGUI_FONT_SIZE_THRESHOLD_FOR_LOADADVANCEXONLYMODE = #{const IMGUI_FONT_SIZE_THRESHOLD_FOR_LOADADVANCEXONLYMODE}
pattern IMGUI_TABLE_MAX_COLUMNS :: CInt
pattern IMGUI_TABLE_MAX_COLUMNS = #{const IMGUI_TABLE_MAX_COLUMNS}
pattern IMGUI_WINDOW_HARD_MIN_SIZE :: CInt
pattern IMGUI_WINDOW_HARD_MIN_SIZE = #{const IMGUI_WINDOW_HARD_MIN_SIZE}
pattern IMSTB_TEXTEDIT_GETWIDTH_NEWLINE :: CInt
pattern IMSTB_TEXTEDIT_GETWIDTH_NEWLINE = #{const IMSTB_TEXTEDIT_GETWIDTH_NEWLINE}
pattern IMSTB_TEXTEDIT_UNDOCHARCOUNT :: CInt
pattern IMSTB_TEXTEDIT_UNDOCHARCOUNT = #{const IMSTB_TEXTEDIT_UNDOCHARCOUNT}
pattern IMSTB_TEXTEDIT_UNDOSTATECOUNT :: CInt
pattern IMSTB_TEXTEDIT_UNDOSTATECOUNT = #{const IMSTB_TEXTEDIT_UNDOSTATECOUNT}
pattern IM_DRAWLIST_ARCFAST_TABLE_SIZE :: CInt
pattern IM_DRAWLIST_ARCFAST_TABLE_SIZE = #{const IM_DRAWLIST_ARCFAST_TABLE_SIZE}
pattern IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MAX :: CInt
pattern IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MAX = #{const IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MAX}
pattern IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MIN :: CInt
pattern IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MIN = #{const IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MIN}
pattern IM_PI :: CInt
pattern IM_PI = #{const IM_PI}
pattern IM_TABSIZE :: CInt
pattern IM_TABSIZE = #{const IM_TABSIZE}
pattern ImFontAtlasRectId_GenerationMask_ :: CInt
pattern ImFontAtlasRectId_GenerationMask_ = #{const ImFontAtlasRectId_GenerationMask_}
pattern ImFontAtlasRectId_GenerationShift_ :: CInt
pattern ImFontAtlasRectId_GenerationShift_ = #{const ImFontAtlasRectId_GenerationShift_}
pattern ImFontAtlasRectId_IndexMask_ :: CInt
pattern ImFontAtlasRectId_IndexMask_ = #{const ImFontAtlasRectId_IndexMask_}
pattern ImGuiKey_LegacyNativeKey_BEGIN :: CInt
pattern ImGuiKey_LegacyNativeKey_BEGIN = #{const ImGuiKey_LegacyNativeKey_BEGIN}
pattern ImGuiKey_LegacyNativeKey_END :: CInt
pattern ImGuiKey_LegacyNativeKey_END = #{const ImGuiKey_LegacyNativeKey_END}
