{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.Impl.SDLRenderer2 where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types
import DearImGui.Raw.Impl.SDLRenderer2.Types

#include "dcimgui_impl_sdlrenderer2.h"

-- functions

-- C: void ImGui_ImplSDLRenderer2_CreateDeviceObjects()
foreign import capi unsafe "dcimgui_impl_sdlrenderer2.h cImGui_ImplSDLRenderer2_CreateDeviceObjects"
  cImGui_ImplSDLRenderer2_CreateDeviceObjects :: IO ()
-- C: void ImGui_ImplSDLRenderer2_DestroyDeviceObjects()
foreign import capi unsafe "dcimgui_impl_sdlrenderer2.h cImGui_ImplSDLRenderer2_DestroyDeviceObjects"
  cImGui_ImplSDLRenderer2_DestroyDeviceObjects :: IO ()
-- C: bool ImGui_ImplSDLRenderer2_Init(SDL_Renderer* renderer)
foreign import capi unsafe "dcimgui_impl_sdlrenderer2.h cImGui_ImplSDLRenderer2_Init"
  cImGui_ImplSDLRenderer2_Init :: (Ptr SDL_Renderer) -> IO CBool
-- C: void ImGui_ImplSDLRenderer2_NewFrame()
foreign import capi unsafe "dcimgui_impl_sdlrenderer2.h cImGui_ImplSDLRenderer2_NewFrame"
  cImGui_ImplSDLRenderer2_NewFrame :: IO ()
-- C: void ImGui_ImplSDLRenderer2_RenderDrawData(ImDrawData* draw_data, SDL_Renderer* renderer)
foreign import capi unsafe "dcimgui_impl_sdlrenderer2.h cImGui_ImplSDLRenderer2_RenderDrawData"
  cImGui_ImplSDLRenderer2_RenderDrawData :: (Ptr ImDrawData) -> (Ptr SDL_Renderer) -> IO ()
-- C: void ImGui_ImplSDLRenderer2_Shutdown()
foreign import capi unsafe "dcimgui_impl_sdlrenderer2.h cImGui_ImplSDLRenderer2_Shutdown"
  cImGui_ImplSDLRenderer2_Shutdown :: IO ()
-- C: void ImGui_ImplSDLRenderer2_UpdateTexture(ImTextureData* tex)
foreign import capi unsafe "dcimgui_impl_sdlrenderer2.h cImGui_ImplSDLRenderer2_UpdateTexture"
  cImGui_ImplSDLRenderer2_UpdateTexture :: (Ptr ImTextureData) -> IO ()
