{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.Impl.Allegro5 where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types
import DearImGui.Raw.Impl.Allegro5.Types

#include "dcimgui_impl_allegro5.h"

-- functions

-- C: bool ImGui_ImplAllegro5_CreateDeviceObjects()
foreign import capi unsafe "dcimgui_impl_allegro5.h cImGui_ImplAllegro5_CreateDeviceObjects"
  cImGui_ImplAllegro5_CreateDeviceObjects :: IO CBool
-- C: bool ImGui_ImplAllegro5_Init(ALLEGRO_DISPLAY* display)
foreign import capi unsafe "dcimgui_impl_allegro5.h cImGui_ImplAllegro5_Init"
  cImGui_ImplAllegro5_Init :: (Ptr ALLEGRO_DISPLAY) -> IO CBool
-- C: void ImGui_ImplAllegro5_InvalidateDeviceObjects()
foreign import capi unsafe "dcimgui_impl_allegro5.h cImGui_ImplAllegro5_InvalidateDeviceObjects"
  cImGui_ImplAllegro5_InvalidateDeviceObjects :: IO ()
-- C: void ImGui_ImplAllegro5_NewFrame()
foreign import capi unsafe "dcimgui_impl_allegro5.h cImGui_ImplAllegro5_NewFrame"
  cImGui_ImplAllegro5_NewFrame :: IO ()
-- C: bool ImGui_ImplAllegro5_ProcessEvent(ALLEGRO_EVENT* event)
foreign import capi unsafe "dcimgui_impl_allegro5.h cImGui_ImplAllegro5_ProcessEvent"
  cImGui_ImplAllegro5_ProcessEvent :: (Ptr ALLEGRO_EVENT) -> IO CBool
-- C: void ImGui_ImplAllegro5_RenderDrawData(ImDrawData* draw_data)
foreign import capi unsafe "dcimgui_impl_allegro5.h cImGui_ImplAllegro5_RenderDrawData"
  cImGui_ImplAllegro5_RenderDrawData :: (Ptr ImDrawData) -> IO ()
-- C: void ImGui_ImplAllegro5_SetDisplay(ALLEGRO_DISPLAY* display)
foreign import capi unsafe "dcimgui_impl_allegro5.h cImGui_ImplAllegro5_SetDisplay"
  cImGui_ImplAllegro5_SetDisplay :: (Ptr ALLEGRO_DISPLAY) -> IO ()
-- C: void ImGui_ImplAllegro5_Shutdown()
foreign import capi unsafe "dcimgui_impl_allegro5.h cImGui_ImplAllegro5_Shutdown"
  cImGui_ImplAllegro5_Shutdown :: IO ()
-- C: void ImGui_ImplAllegro5_UpdateTexture(ImTextureData* tex)
foreign import capi unsafe "dcimgui_impl_allegro5.h cImGui_ImplAllegro5_UpdateTexture"
  cImGui_ImplAllegro5_UpdateTexture :: (Ptr ImTextureData) -> IO ()
