{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.Impl.SDLGPU3.Types where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types

#include "dcimgui_impl_sdlgpu3.h"

-- structs (opaque)

data SDL_GPUCommandBuffer
data SDL_GPUDevice
data SDL_GPUGraphicsPipeline
data SDL_GPUPresentMode
data SDL_GPURenderPass
data SDL_GPUSampleCount
data SDL_GPUSampler
data SDL_GPUSwapchainComposition
data SDL_GPUTextureFormat
data ImGui_ImplSDLGPU3_InitInfo
instance Storable ImGui_ImplSDLGPU3_InitInfo where
  sizeOf _    = #{size ImGui_ImplSDLGPU3_InitInfo}
  alignment _ = #{alignment ImGui_ImplSDLGPU3_InitInfo}
  peek _ = error "ImGui_ImplSDLGPU3_InitInfo: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGui_ImplSDLGPU3_InitInfo: opaque struct, poke not supported in v0"
data ImGui_ImplSDLGPU3_RenderState
instance Storable ImGui_ImplSDLGPU3_RenderState where
  sizeOf _    = #{size ImGui_ImplSDLGPU3_RenderState}
  alignment _ = #{alignment ImGui_ImplSDLGPU3_RenderState}
  peek _ = error "ImGui_ImplSDLGPU3_RenderState: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGui_ImplSDLGPU3_RenderState: opaque struct, poke not supported in v0"
