{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.Impl.Vulkan.Types where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types
import Vulkan.Core10
import Vulkan.Core10.Handles
import Vulkan.Extensions

#include "dcimgui_impl_vulkan.h"

-- structs (opaque)

data VkAllocationCallbacks
data VkAttachmentDescription
data VkClearValue
data VkPipelineRenderingCreateInfoKHR
data VkShaderModuleCreateInfo
data VkSurfaceFormatKHR
data ImGui_ImplVulkanH_Frame
instance Storable ImGui_ImplVulkanH_Frame where
  sizeOf _    = #{size ImGui_ImplVulkanH_Frame}
  alignment _ = #{alignment ImGui_ImplVulkanH_Frame}
  peek _ = error "ImGui_ImplVulkanH_Frame: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGui_ImplVulkanH_Frame: opaque struct, poke not supported in v0"
data ImGui_ImplVulkanH_FrameSemaphores
instance Storable ImGui_ImplVulkanH_FrameSemaphores where
  sizeOf _    = #{size ImGui_ImplVulkanH_FrameSemaphores}
  alignment _ = #{alignment ImGui_ImplVulkanH_FrameSemaphores}
  peek _ = error "ImGui_ImplVulkanH_FrameSemaphores: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGui_ImplVulkanH_FrameSemaphores: opaque struct, poke not supported in v0"
data ImGui_ImplVulkanH_Window
instance Storable ImGui_ImplVulkanH_Window where
  sizeOf _    = #{size ImGui_ImplVulkanH_Window}
  alignment _ = #{alignment ImGui_ImplVulkanH_Window}
  peek _ = error "ImGui_ImplVulkanH_Window: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGui_ImplVulkanH_Window: opaque struct, poke not supported in v0"
data ImGui_ImplVulkan_InitInfo
instance Storable ImGui_ImplVulkan_InitInfo where
  sizeOf _    = #{size ImGui_ImplVulkan_InitInfo}
  alignment _ = #{alignment ImGui_ImplVulkan_InitInfo}
  peek _ = error "ImGui_ImplVulkan_InitInfo: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGui_ImplVulkan_InitInfo: opaque struct, poke not supported in v0"
data ImGui_ImplVulkan_PipelineInfo
instance Storable ImGui_ImplVulkan_PipelineInfo where
  sizeOf _    = #{size ImGui_ImplVulkan_PipelineInfo}
  alignment _ = #{alignment ImGui_ImplVulkan_PipelineInfo}
  peek _ = error "ImGui_ImplVulkan_PipelineInfo: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGui_ImplVulkan_PipelineInfo: opaque struct, poke not supported in v0"
data ImGui_ImplVulkan_RenderState
instance Storable ImGui_ImplVulkan_RenderState where
  sizeOf _    = #{size ImGui_ImplVulkan_RenderState}
  alignment _ = #{alignment ImGui_ImplVulkan_RenderState}
  peek _ = error "ImGui_ImplVulkan_RenderState: opaque struct, peek not supported in v0"
  poke _ _ = error "ImGui_ImplVulkan_RenderState: opaque struct, poke not supported in v0"
data ImVector_ImGui_ImplVulkanH_Frame
instance Storable ImVector_ImGui_ImplVulkanH_Frame where
  sizeOf _    = #{size ImVector_ImGui_ImplVulkanH_Frame}
  alignment _ = #{alignment ImVector_ImGui_ImplVulkanH_Frame}
  peek _ = error "ImVector_ImGui_ImplVulkanH_Frame: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGui_ImplVulkanH_Frame: opaque struct, poke not supported in v0"
data ImVector_ImGui_ImplVulkanH_FrameSemaphores
instance Storable ImVector_ImGui_ImplVulkanH_FrameSemaphores where
  sizeOf _    = #{size ImVector_ImGui_ImplVulkanH_FrameSemaphores}
  alignment _ = #{alignment ImVector_ImGui_ImplVulkanH_FrameSemaphores}
  peek _ = error "ImVector_ImGui_ImplVulkanH_FrameSemaphores: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_ImGui_ImplVulkanH_FrameSemaphores: opaque struct, poke not supported in v0"
data ImVector_VkDynamicState
instance Storable ImVector_VkDynamicState where
  sizeOf _    = #{size ImVector_VkDynamicState}
  alignment _ = #{alignment ImVector_VkDynamicState}
  peek _ = error "ImVector_VkDynamicState: opaque struct, peek not supported in v0"
  poke _ _ = error "ImVector_VkDynamicState: opaque struct, poke not supported in v0"

-- defines

pattern IMGUI_IMPL_VULKAN_MINIMUM_IMAGE_SAMPLER_POOL_SIZE :: CInt
pattern IMGUI_IMPL_VULKAN_MINIMUM_IMAGE_SAMPLER_POOL_SIZE = #{const IMGUI_IMPL_VULKAN_MINIMUM_IMAGE_SAMPLER_POOL_SIZE}
