// Generated by dear-bindings-ffi. Do not edit.
#ifndef DEAR_IMGUI_WRAPPERS_H
#define DEAR_IMGUI_WRAPPERS_H

#include "dcimgui_nodefaultargfunctions.h"

#ifdef __cplusplus
extern "C" {
#endif

void ImDrawList__PathArcToFastEx_wrap(ImDrawList* self, ImVec2 const* center, float radius, int a_min_sample, int a_max_sample, int a_step);
void ImDrawList__PathArcToN_wrap(ImDrawList* self, ImVec2 const* center, float radius, float a_min, float a_max, int num_segments);
void ImDrawList__SetTexture_wrap(ImDrawList* self, ImTextureRef const* tex_ref);
void ImColor_HSV_wrap(float h, float s, float v, float a, ImColor* _out);
void ImDrawData_ScaleClipRects_wrap(ImDrawData* self, ImVec2 const* fb_scale);
void ImDrawList_AddBezierCubic_wrap(ImDrawList* self, ImVec2 const* p1, ImVec2 const* p2, ImVec2 const* p3, ImVec2 const* p4, ImU32 col, float thickness, int num_segments);
void ImDrawList_AddBezierQuadratic_wrap(ImDrawList* self, ImVec2 const* p1, ImVec2 const* p2, ImVec2 const* p3, ImU32 col, float thickness, int num_segments);
void ImDrawList_AddCircle_wrap(ImDrawList* self, ImVec2 const* center, float radius, ImU32 col, int num_segments, float thickness);
void ImDrawList_AddCircleFilled_wrap(ImDrawList* self, ImVec2 const* center, float radius, ImU32 col, int num_segments);
void ImDrawList_AddEllipse_wrap(ImDrawList* self, ImVec2 const* center, ImVec2 const* radius, ImU32 col, float rot, int num_segments, float thickness);
void ImDrawList_AddEllipseFilled_wrap(ImDrawList* self, ImVec2 const* center, ImVec2 const* radius, ImU32 col, float rot, int num_segments);
void ImDrawList_AddImage_wrap(ImDrawList* self, ImTextureRef const* tex_ref, ImVec2 const* p_min, ImVec2 const* p_max, ImVec2 const* uv_min, ImVec2 const* uv_max, ImU32 col);
void ImDrawList_AddImageQuad_wrap(ImDrawList* self, ImTextureRef const* tex_ref, ImVec2 const* p1, ImVec2 const* p2, ImVec2 const* p3, ImVec2 const* p4, ImVec2 const* uv1, ImVec2 const* uv2, ImVec2 const* uv3, ImVec2 const* uv4, ImU32 col);
void ImDrawList_AddImageRounded_wrap(ImDrawList* self, ImTextureRef const* tex_ref, ImVec2 const* p_min, ImVec2 const* p_max, ImVec2 const* uv_min, ImVec2 const* uv_max, ImU32 col, float rounding, ImDrawFlags flags);
void ImDrawList_AddLine_wrap(ImDrawList* self, ImVec2 const* p1, ImVec2 const* p2, ImU32 col, float thickness);
void ImDrawList_AddNgon_wrap(ImDrawList* self, ImVec2 const* center, float radius, ImU32 col, int num_segments, float thickness);
void ImDrawList_AddNgonFilled_wrap(ImDrawList* self, ImVec2 const* center, float radius, ImU32 col, int num_segments);
void ImDrawList_AddQuad_wrap(ImDrawList* self, ImVec2 const* p1, ImVec2 const* p2, ImVec2 const* p3, ImVec2 const* p4, ImU32 col, float thickness);
void ImDrawList_AddQuadFilled_wrap(ImDrawList* self, ImVec2 const* p1, ImVec2 const* p2, ImVec2 const* p3, ImVec2 const* p4, ImU32 col);
void ImDrawList_AddRect_wrap(ImDrawList* self, ImVec2 const* p_min, ImVec2 const* p_max, ImU32 col, float rounding, ImDrawFlags flags, float thickness);
void ImDrawList_AddRectFilled_wrap(ImDrawList* self, ImVec2 const* p_min, ImVec2 const* p_max, ImU32 col, float rounding, ImDrawFlags flags);
void ImDrawList_AddRectFilledMultiColor_wrap(ImDrawList* self, ImVec2 const* p_min, ImVec2 const* p_max, ImU32 col_upr_left, ImU32 col_upr_right, ImU32 col_bot_right, ImU32 col_bot_left);
void ImDrawList_AddText_wrap(ImDrawList* self, ImVec2 const* pos, ImU32 col, const char* text_begin, const char* text_end);
void ImDrawList_AddTextImFontPtr_wrap(ImDrawList* self, ImFont* font, float font_size, ImVec2 const* pos, ImU32 col, const char* text_begin, const char* text_end, float wrap_width, const ImVec4* cpu_fine_clip_rect);
void ImDrawList_AddTriangle_wrap(ImDrawList* self, ImVec2 const* p1, ImVec2 const* p2, ImVec2 const* p3, ImU32 col, float thickness);
void ImDrawList_AddTriangleFilled_wrap(ImDrawList* self, ImVec2 const* p1, ImVec2 const* p2, ImVec2 const* p3, ImU32 col);
void ImDrawList_GetClipRectMax_wrap(const ImDrawList* self, ImVec2* _out);
void ImDrawList_GetClipRectMin_wrap(const ImDrawList* self, ImVec2* _out);
void ImDrawList_PathArcTo_wrap(ImDrawList* self, ImVec2 const* center, float radius, float a_min, float a_max, int num_segments);
void ImDrawList_PathArcToFast_wrap(ImDrawList* self, ImVec2 const* center, float radius, int a_min_of_12, int a_max_of_12);
void ImDrawList_PathBezierCubicCurveTo_wrap(ImDrawList* self, ImVec2 const* p2, ImVec2 const* p3, ImVec2 const* p4, int num_segments);
void ImDrawList_PathBezierQuadraticCurveTo_wrap(ImDrawList* self, ImVec2 const* p2, ImVec2 const* p3, int num_segments);
void ImDrawList_PathEllipticalArcTo_wrap(ImDrawList* self, ImVec2 const* center, ImVec2 const* radius, float rot, float a_min, float a_max, int num_segments);
void ImDrawList_PathLineTo_wrap(ImDrawList* self, ImVec2 const* pos);
void ImDrawList_PathLineToMergeDuplicate_wrap(ImDrawList* self, ImVec2 const* pos);
void ImDrawList_PathRect_wrap(ImDrawList* self, ImVec2 const* rect_min, ImVec2 const* rect_max, float rounding, ImDrawFlags flags);
void ImDrawList_PrimQuadUV_wrap(ImDrawList* self, ImVec2 const* a, ImVec2 const* b, ImVec2 const* c, ImVec2 const* d, ImVec2 const* uv_a, ImVec2 const* uv_b, ImVec2 const* uv_c, ImVec2 const* uv_d, ImU32 col);
void ImDrawList_PrimRect_wrap(ImDrawList* self, ImVec2 const* a, ImVec2 const* b, ImU32 col);
void ImDrawList_PrimRectUV_wrap(ImDrawList* self, ImVec2 const* a, ImVec2 const* b, ImVec2 const* uv_a, ImVec2 const* uv_b, ImU32 col);
void ImDrawList_PrimVtx_wrap(ImDrawList* self, ImVec2 const* pos, ImVec2 const* uv, ImU32 col);
void ImDrawList_PrimWriteVtx_wrap(ImDrawList* self, ImVec2 const* pos, ImVec2 const* uv, ImU32 col);
void ImDrawList_PushClipRect_wrap(ImDrawList* self, ImVec2 const* clip_rect_min, ImVec2 const* clip_rect_max, bool intersect_with_current_clip_rect);
void ImDrawList_PushTexture_wrap(ImDrawList* self, ImTextureRef const* tex_ref);
void ImDrawList_PushTextureID_wrap(ImDrawList* self, ImTextureRef const* tex_ref);
void ImFont_CalcTextSizeA_wrap(ImFont* self, float size, float max_width, float wrap_width, const char* text_begin, const char* text_end, const char** out_remaining, ImVec2* _out);
void ImFont_RenderChar_wrap(ImFont* self, ImDrawList* draw_list, float size, ImVec2 const* pos, ImU32 col, ImWchar c, const ImVec4* cpu_fine_clip);
void ImFont_RenderText_wrap(ImFont* self, ImDrawList* draw_list, float size, ImVec2 const* pos, ImU32 col, ImVec4 const* clip_rect, const char* text_begin, const char* text_end, float wrap_width, ImDrawTextFlags flags);
ImFontAtlasRectId ImFontAtlas_AddCustomRectFontGlyph_wrap(ImFontAtlas* self, ImFont* font, ImWchar codepoint, int w, int h, float advance_x, ImVec2 const* offset);
ImFontAtlasRectId ImFontAtlas_AddCustomRectFontGlyphForSize_wrap(ImFontAtlas* self, ImFont* font, float font_size, ImWchar codepoint, int w, int h, float advance_x, ImVec2 const* offset);
void ImFontAtlas_SetTexIDImTextureRef_wrap(ImFontAtlas* self, ImTextureRef const* id);
bool ImGui_BeginChild_wrap(const char* str_id, ImVec2 const* size, ImGuiChildFlags child_flags, ImGuiWindowFlags window_flags);
bool ImGui_BeginChildID_wrap(ImGuiID id, ImVec2 const* size, ImGuiChildFlags child_flags, ImGuiWindowFlags window_flags);
bool ImGui_BeginListBox_wrap(const char* label, ImVec2 const* size);
bool ImGui_BeginTable_wrap(const char* str_id, int columns, ImGuiTableFlags flags, ImVec2 const* outer_size, float inner_width);
bool ImGui_Button_wrap(const char* label, ImVec2 const* size);
void ImGui_CalcTextSize_wrap(const char* text, const char* text_end, bool hide_text_after_double_hash, float wrap_width, ImVec2* _out);
bool ImGui_ColorButton_wrap(const char* desc_id, ImVec4 const* col, ImGuiColorEditFlags flags, ImVec2 const* size);
ImU32 ImGui_ColorConvertFloat4ToU32_wrap(ImVec4 const* in);
void ImGui_ColorConvertU32ToFloat4_wrap(ImU32 in, ImVec4* _out);
void ImGui_Dummy_wrap(ImVec2 const* size);
ImU32 ImGui_GetColorU32ImVec4_wrap(ImVec4 const* col);
void ImGui_GetContentRegionAvail_wrap(ImVec2* _out);
void ImGui_GetContentRegionMax_wrap(ImVec2* _out);
void ImGui_GetCursorPos_wrap(ImVec2* _out);
void ImGui_GetCursorScreenPos_wrap(ImVec2* _out);
void ImGui_GetCursorStartPos_wrap(ImVec2* _out);
void ImGui_GetFontTexUvWhitePixel_wrap(ImVec2* _out);
void ImGui_GetItemRectMax_wrap(ImVec2* _out);
void ImGui_GetItemRectMin_wrap(ImVec2* _out);
void ImGui_GetItemRectSize_wrap(ImVec2* _out);
void ImGui_GetMouseDragDelta_wrap(ImGuiMouseButton button, float lock_threshold, ImVec2* _out);
void ImGui_GetMousePos_wrap(ImVec2* _out);
void ImGui_GetMousePosOnOpeningCurrentPopup_wrap(ImVec2* _out);
void ImGui_GetWindowContentRegionMax_wrap(ImVec2* _out);
void ImGui_GetWindowContentRegionMin_wrap(ImVec2* _out);
void ImGui_GetWindowPos_wrap(ImVec2* _out);
void ImGui_GetWindowSize_wrap(ImVec2* _out);
void ImGui_Image_wrap(ImTextureRef const* tex_ref, ImVec2 const* image_size, ImVec2 const* uv0, ImVec2 const* uv1);
bool ImGui_ImageButton_wrap(const char* str_id, ImTextureRef const* tex_ref, ImVec2 const* image_size, ImVec2 const* uv0, ImVec2 const* uv1, ImVec4 const* bg_col, ImVec4 const* tint_col);
void ImGui_ImageImVec4_wrap(ImTextureRef const* tex_ref, ImVec2 const* image_size, ImVec2 const* uv0, ImVec2 const* uv1, ImVec4 const* tint_col, ImVec4 const* border_col);
void ImGui_ImageWithBg_wrap(ImTextureRef const* tex_ref, ImVec2 const* image_size, ImVec2 const* uv0, ImVec2 const* uv1, ImVec4 const* bg_col, ImVec4 const* tint_col);
bool ImGui_InputTextMultiline_wrap(const char* label, char* buf, size_t buf_size, ImVec2 const* size, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback, void* user_data);
bool ImGui_InvisibleButton_wrap(const char* str_id, ImVec2 const* size, ImGuiButtonFlags flags);
bool ImGui_IsMouseHoveringRect_wrap(ImVec2 const* r_min, ImVec2 const* r_max, bool clip);
bool ImGui_IsRectVisible_wrap(ImVec2 const* rect_min, ImVec2 const* rect_max);
bool ImGui_IsRectVisibleBySize_wrap(ImVec2 const* size);
void ImGui_PlotHistogram_wrap(const char* label, const float* values, int values_count, int values_offset, const char* overlay_text, float scale_min, float scale_max, ImVec2 const* graph_size, int stride);
void ImGui_PlotHistogramCallback_wrap(const char* label, float (*values_getter)(void* data, int idx), void* data, int values_count, int values_offset, const char* overlay_text, float scale_min, float scale_max, ImVec2 const* graph_size);
void ImGui_PlotLines_wrap(const char* label, const float* values, int values_count, int values_offset, const char* overlay_text, float scale_min, float scale_max, ImVec2 const* graph_size, int stride);
void ImGui_PlotLinesCallback_wrap(const char* label, float (*values_getter)(void* data, int idx), void* data, int values_count, int values_offset, const char* overlay_text, float scale_min, float scale_max, ImVec2 const* graph_size);
void ImGui_ProgressBar_wrap(float fraction, ImVec2 const* size_arg, const char* overlay);
void ImGui_PushClipRect_wrap(ImVec2 const* clip_rect_min, ImVec2 const* clip_rect_max, bool intersect_with_current_clip_rect);
void ImGui_PushStyleColorImVec4_wrap(ImGuiCol idx, ImVec4 const* col);
void ImGui_PushStyleVarImVec2_wrap(ImGuiStyleVar idx, ImVec2 const* val);
bool ImGui_Selectable_wrap(const char* label, bool selected, ImGuiSelectableFlags flags, ImVec2 const* size);
bool ImGui_SelectableBoolPtr_wrap(const char* label, bool* p_selected, ImGuiSelectableFlags flags, ImVec2 const* size);
void ImGui_SetCursorPos_wrap(ImVec2 const* local_pos);
void ImGui_SetCursorScreenPos_wrap(ImVec2 const* pos);
void ImGui_SetNextWindowContentSize_wrap(ImVec2 const* size);
void ImGui_SetNextWindowPos_wrap(ImVec2 const* pos, ImGuiCond cond, ImVec2 const* pivot);
void ImGui_SetNextWindowScroll_wrap(ImVec2 const* scroll);
void ImGui_SetNextWindowSize_wrap(ImVec2 const* size, ImGuiCond cond);
void ImGui_SetNextWindowSizeConstraints_wrap(ImVec2 const* size_min, ImVec2 const* size_max, ImGuiSizeCallback custom_callback, void* custom_callback_data);
void ImGui_SetWindowPos_wrap(ImVec2 const* pos, ImGuiCond cond);
void ImGui_SetWindowPosStr_wrap(const char* name, ImVec2 const* pos, ImGuiCond cond);
void ImGui_SetWindowSize_wrap(ImVec2 const* size, ImGuiCond cond);
void ImGui_SetWindowSizeStr_wrap(const char* name, ImVec2 const* size, ImGuiCond cond);
bool ImGui_VSliderFloat_wrap(const char* label, ImVec2 const* size, float* v, float v_min, float v_max, const char* format, ImGuiSliderFlags flags);
bool ImGui_VSliderInt_wrap(const char* label, ImVec2 const* size, int* v, int v_min, int v_max, const char* format, ImGuiSliderFlags flags);
bool ImGui_VSliderScalar_wrap(const char* label, ImVec2 const* size, ImGuiDataType data_type, void* p_data, const void* p_min, const void* p_max, const char* format, ImGuiSliderFlags flags);
void ImGuiViewport_GetCenter_wrap(const ImGuiViewport* self, ImVec2* _out);
void ImGuiViewport_GetWorkCenter_wrap(const ImGuiViewport* self, ImVec2* _out);
void ImTextureData_GetTexRef_wrap(ImTextureData* self, ImTextureRef* _out);

#ifdef __cplusplus
}
#endif

#endif
