// Generated by dear-bindings-ffi. Do not edit.
#include "DearImGuiWrappers.h"

extern "C" void ImDrawList__PathArcToFastEx_wrap(ImDrawList* self, ImVec2 const* center, float radius, int a_min_sample, int a_max_sample, int a_step) {
    ImDrawList__PathArcToFastEx(self, *center, radius, a_min_sample, a_max_sample, a_step);
}

extern "C" void ImDrawList__PathArcToN_wrap(ImDrawList* self, ImVec2 const* center, float radius, float a_min, float a_max, int num_segments) {
    ImDrawList__PathArcToN(self, *center, radius, a_min, a_max, num_segments);
}

extern "C" void ImDrawList__SetTexture_wrap(ImDrawList* self, ImTextureRef const* tex_ref) {
    ImDrawList__SetTexture(self, *tex_ref);
}

extern "C" void ImColor_HSV_wrap(float h, float s, float v, float a, ImColor* _out) {
    *_out = ImColor_HSV(h, s, v, a);
}

extern "C" void ImDrawData_ScaleClipRects_wrap(ImDrawData* self, ImVec2 const* fb_scale) {
    ImDrawData_ScaleClipRects(self, *fb_scale);
}

extern "C" void ImDrawList_AddBezierCubic_wrap(ImDrawList* self, ImVec2 const* p1, ImVec2 const* p2, ImVec2 const* p3, ImVec2 const* p4, ImU32 col, float thickness, int num_segments) {
    ImDrawList_AddBezierCubic(self, *p1, *p2, *p3, *p4, col, thickness, num_segments);
}

extern "C" void ImDrawList_AddBezierQuadratic_wrap(ImDrawList* self, ImVec2 const* p1, ImVec2 const* p2, ImVec2 const* p3, ImU32 col, float thickness, int num_segments) {
    ImDrawList_AddBezierQuadratic(self, *p1, *p2, *p3, col, thickness, num_segments);
}

extern "C" void ImDrawList_AddCircle_wrap(ImDrawList* self, ImVec2 const* center, float radius, ImU32 col, int num_segments, float thickness) {
    ImDrawList_AddCircle(self, *center, radius, col, num_segments, thickness);
}

extern "C" void ImDrawList_AddCircleFilled_wrap(ImDrawList* self, ImVec2 const* center, float radius, ImU32 col, int num_segments) {
    ImDrawList_AddCircleFilled(self, *center, radius, col, num_segments);
}

extern "C" void ImDrawList_AddEllipse_wrap(ImDrawList* self, ImVec2 const* center, ImVec2 const* radius, ImU32 col, float rot, int num_segments, float thickness) {
    ImDrawList_AddEllipse(self, *center, *radius, col, rot, num_segments, thickness);
}

extern "C" void ImDrawList_AddEllipseFilled_wrap(ImDrawList* self, ImVec2 const* center, ImVec2 const* radius, ImU32 col, float rot, int num_segments) {
    ImDrawList_AddEllipseFilled(self, *center, *radius, col, rot, num_segments);
}

extern "C" void ImDrawList_AddImage_wrap(ImDrawList* self, ImTextureRef const* tex_ref, ImVec2 const* p_min, ImVec2 const* p_max, ImVec2 const* uv_min, ImVec2 const* uv_max, ImU32 col) {
    ImDrawList_AddImage(self, *tex_ref, *p_min, *p_max, *uv_min, *uv_max, col);
}

extern "C" void ImDrawList_AddImageQuad_wrap(ImDrawList* self, ImTextureRef const* tex_ref, ImVec2 const* p1, ImVec2 const* p2, ImVec2 const* p3, ImVec2 const* p4, ImVec2 const* uv1, ImVec2 const* uv2, ImVec2 const* uv3, ImVec2 const* uv4, ImU32 col) {
    ImDrawList_AddImageQuad(self, *tex_ref, *p1, *p2, *p3, *p4, *uv1, *uv2, *uv3, *uv4, col);
}

extern "C" void ImDrawList_AddImageRounded_wrap(ImDrawList* self, ImTextureRef const* tex_ref, ImVec2 const* p_min, ImVec2 const* p_max, ImVec2 const* uv_min, ImVec2 const* uv_max, ImU32 col, float rounding, ImDrawFlags flags) {
    ImDrawList_AddImageRounded(self, *tex_ref, *p_min, *p_max, *uv_min, *uv_max, col, rounding, flags);
}

extern "C" void ImDrawList_AddLine_wrap(ImDrawList* self, ImVec2 const* p1, ImVec2 const* p2, ImU32 col, float thickness) {
    ImDrawList_AddLine(self, *p1, *p2, col, thickness);
}

extern "C" void ImDrawList_AddNgon_wrap(ImDrawList* self, ImVec2 const* center, float radius, ImU32 col, int num_segments, float thickness) {
    ImDrawList_AddNgon(self, *center, radius, col, num_segments, thickness);
}

extern "C" void ImDrawList_AddNgonFilled_wrap(ImDrawList* self, ImVec2 const* center, float radius, ImU32 col, int num_segments) {
    ImDrawList_AddNgonFilled(self, *center, radius, col, num_segments);
}

extern "C" void ImDrawList_AddQuad_wrap(ImDrawList* self, ImVec2 const* p1, ImVec2 const* p2, ImVec2 const* p3, ImVec2 const* p4, ImU32 col, float thickness) {
    ImDrawList_AddQuad(self, *p1, *p2, *p3, *p4, col, thickness);
}

extern "C" void ImDrawList_AddQuadFilled_wrap(ImDrawList* self, ImVec2 const* p1, ImVec2 const* p2, ImVec2 const* p3, ImVec2 const* p4, ImU32 col) {
    ImDrawList_AddQuadFilled(self, *p1, *p2, *p3, *p4, col);
}

extern "C" void ImDrawList_AddRect_wrap(ImDrawList* self, ImVec2 const* p_min, ImVec2 const* p_max, ImU32 col, float rounding, ImDrawFlags flags, float thickness) {
    ImDrawList_AddRect(self, *p_min, *p_max, col, rounding, flags, thickness);
}

extern "C" void ImDrawList_AddRectFilled_wrap(ImDrawList* self, ImVec2 const* p_min, ImVec2 const* p_max, ImU32 col, float rounding, ImDrawFlags flags) {
    ImDrawList_AddRectFilled(self, *p_min, *p_max, col, rounding, flags);
}

extern "C" void ImDrawList_AddRectFilledMultiColor_wrap(ImDrawList* self, ImVec2 const* p_min, ImVec2 const* p_max, ImU32 col_upr_left, ImU32 col_upr_right, ImU32 col_bot_right, ImU32 col_bot_left) {
    ImDrawList_AddRectFilledMultiColor(self, *p_min, *p_max, col_upr_left, col_upr_right, col_bot_right, col_bot_left);
}

extern "C" void ImDrawList_AddText_wrap(ImDrawList* self, ImVec2 const* pos, ImU32 col, const char* text_begin, const char* text_end) {
    ImDrawList_AddText(self, *pos, col, text_begin, text_end);
}

extern "C" void ImDrawList_AddTextImFontPtr_wrap(ImDrawList* self, ImFont* font, float font_size, ImVec2 const* pos, ImU32 col, const char* text_begin, const char* text_end, float wrap_width, const ImVec4* cpu_fine_clip_rect) {
    ImDrawList_AddTextImFontPtr(self, font, font_size, *pos, col, text_begin, text_end, wrap_width, cpu_fine_clip_rect);
}

extern "C" void ImDrawList_AddTriangle_wrap(ImDrawList* self, ImVec2 const* p1, ImVec2 const* p2, ImVec2 const* p3, ImU32 col, float thickness) {
    ImDrawList_AddTriangle(self, *p1, *p2, *p3, col, thickness);
}

extern "C" void ImDrawList_AddTriangleFilled_wrap(ImDrawList* self, ImVec2 const* p1, ImVec2 const* p2, ImVec2 const* p3, ImU32 col) {
    ImDrawList_AddTriangleFilled(self, *p1, *p2, *p3, col);
}

extern "C" void ImDrawList_GetClipRectMax_wrap(const ImDrawList* self, ImVec2* _out) {
    *_out = ImDrawList_GetClipRectMax(self);
}

extern "C" void ImDrawList_GetClipRectMin_wrap(const ImDrawList* self, ImVec2* _out) {
    *_out = ImDrawList_GetClipRectMin(self);
}

extern "C" void ImDrawList_PathArcTo_wrap(ImDrawList* self, ImVec2 const* center, float radius, float a_min, float a_max, int num_segments) {
    ImDrawList_PathArcTo(self, *center, radius, a_min, a_max, num_segments);
}

extern "C" void ImDrawList_PathArcToFast_wrap(ImDrawList* self, ImVec2 const* center, float radius, int a_min_of_12, int a_max_of_12) {
    ImDrawList_PathArcToFast(self, *center, radius, a_min_of_12, a_max_of_12);
}

extern "C" void ImDrawList_PathBezierCubicCurveTo_wrap(ImDrawList* self, ImVec2 const* p2, ImVec2 const* p3, ImVec2 const* p4, int num_segments) {
    ImDrawList_PathBezierCubicCurveTo(self, *p2, *p3, *p4, num_segments);
}

extern "C" void ImDrawList_PathBezierQuadraticCurveTo_wrap(ImDrawList* self, ImVec2 const* p2, ImVec2 const* p3, int num_segments) {
    ImDrawList_PathBezierQuadraticCurveTo(self, *p2, *p3, num_segments);
}

extern "C" void ImDrawList_PathEllipticalArcTo_wrap(ImDrawList* self, ImVec2 const* center, ImVec2 const* radius, float rot, float a_min, float a_max, int num_segments) {
    ImDrawList_PathEllipticalArcTo(self, *center, *radius, rot, a_min, a_max, num_segments);
}

extern "C" void ImDrawList_PathLineTo_wrap(ImDrawList* self, ImVec2 const* pos) {
    ImDrawList_PathLineTo(self, *pos);
}

extern "C" void ImDrawList_PathLineToMergeDuplicate_wrap(ImDrawList* self, ImVec2 const* pos) {
    ImDrawList_PathLineToMergeDuplicate(self, *pos);
}

extern "C" void ImDrawList_PathRect_wrap(ImDrawList* self, ImVec2 const* rect_min, ImVec2 const* rect_max, float rounding, ImDrawFlags flags) {
    ImDrawList_PathRect(self, *rect_min, *rect_max, rounding, flags);
}

extern "C" void ImDrawList_PrimQuadUV_wrap(ImDrawList* self, ImVec2 const* a, ImVec2 const* b, ImVec2 const* c, ImVec2 const* d, ImVec2 const* uv_a, ImVec2 const* uv_b, ImVec2 const* uv_c, ImVec2 const* uv_d, ImU32 col) {
    ImDrawList_PrimQuadUV(self, *a, *b, *c, *d, *uv_a, *uv_b, *uv_c, *uv_d, col);
}

extern "C" void ImDrawList_PrimRect_wrap(ImDrawList* self, ImVec2 const* a, ImVec2 const* b, ImU32 col) {
    ImDrawList_PrimRect(self, *a, *b, col);
}

extern "C" void ImDrawList_PrimRectUV_wrap(ImDrawList* self, ImVec2 const* a, ImVec2 const* b, ImVec2 const* uv_a, ImVec2 const* uv_b, ImU32 col) {
    ImDrawList_PrimRectUV(self, *a, *b, *uv_a, *uv_b, col);
}

extern "C" void ImDrawList_PrimVtx_wrap(ImDrawList* self, ImVec2 const* pos, ImVec2 const* uv, ImU32 col) {
    ImDrawList_PrimVtx(self, *pos, *uv, col);
}

extern "C" void ImDrawList_PrimWriteVtx_wrap(ImDrawList* self, ImVec2 const* pos, ImVec2 const* uv, ImU32 col) {
    ImDrawList_PrimWriteVtx(self, *pos, *uv, col);
}

extern "C" void ImDrawList_PushClipRect_wrap(ImDrawList* self, ImVec2 const* clip_rect_min, ImVec2 const* clip_rect_max, bool intersect_with_current_clip_rect) {
    ImDrawList_PushClipRect(self, *clip_rect_min, *clip_rect_max, intersect_with_current_clip_rect);
}

extern "C" void ImDrawList_PushTexture_wrap(ImDrawList* self, ImTextureRef const* tex_ref) {
    ImDrawList_PushTexture(self, *tex_ref);
}

extern "C" void ImDrawList_PushTextureID_wrap(ImDrawList* self, ImTextureRef const* tex_ref) {
    ImDrawList_PushTextureID(self, *tex_ref);
}

extern "C" void ImFont_CalcTextSizeA_wrap(ImFont* self, float size, float max_width, float wrap_width, const char* text_begin, const char* text_end, const char** out_remaining, ImVec2* _out) {
    *_out = ImFont_CalcTextSizeA(self, size, max_width, wrap_width, text_begin, text_end, out_remaining);
}

extern "C" void ImFont_RenderChar_wrap(ImFont* self, ImDrawList* draw_list, float size, ImVec2 const* pos, ImU32 col, ImWchar c, const ImVec4* cpu_fine_clip) {
    ImFont_RenderChar(self, draw_list, size, *pos, col, c, cpu_fine_clip);
}

extern "C" void ImFont_RenderText_wrap(ImFont* self, ImDrawList* draw_list, float size, ImVec2 const* pos, ImU32 col, ImVec4 const* clip_rect, const char* text_begin, const char* text_end, float wrap_width, ImDrawTextFlags flags) {
    ImFont_RenderText(self, draw_list, size, *pos, col, *clip_rect, text_begin, text_end, wrap_width, flags);
}

extern "C" ImFontAtlasRectId ImFontAtlas_AddCustomRectFontGlyph_wrap(ImFontAtlas* self, ImFont* font, ImWchar codepoint, int w, int h, float advance_x, ImVec2 const* offset) {
    return ImFontAtlas_AddCustomRectFontGlyph(self, font, codepoint, w, h, advance_x, *offset);
}

extern "C" ImFontAtlasRectId ImFontAtlas_AddCustomRectFontGlyphForSize_wrap(ImFontAtlas* self, ImFont* font, float font_size, ImWchar codepoint, int w, int h, float advance_x, ImVec2 const* offset) {
    return ImFontAtlas_AddCustomRectFontGlyphForSize(self, font, font_size, codepoint, w, h, advance_x, *offset);
}

extern "C" void ImFontAtlas_SetTexIDImTextureRef_wrap(ImFontAtlas* self, ImTextureRef const* id) {
    ImFontAtlas_SetTexIDImTextureRef(self, *id);
}

extern "C" bool ImGui_BeginChild_wrap(const char* str_id, ImVec2 const* size, ImGuiChildFlags child_flags, ImGuiWindowFlags window_flags) {
    return ImGui_BeginChild(str_id, *size, child_flags, window_flags);
}

extern "C" bool ImGui_BeginChildID_wrap(ImGuiID id, ImVec2 const* size, ImGuiChildFlags child_flags, ImGuiWindowFlags window_flags) {
    return ImGui_BeginChildID(id, *size, child_flags, window_flags);
}

extern "C" bool ImGui_BeginListBox_wrap(const char* label, ImVec2 const* size) {
    return ImGui_BeginListBox(label, *size);
}

extern "C" bool ImGui_BeginTable_wrap(const char* str_id, int columns, ImGuiTableFlags flags, ImVec2 const* outer_size, float inner_width) {
    return ImGui_BeginTable(str_id, columns, flags, *outer_size, inner_width);
}

extern "C" bool ImGui_Button_wrap(const char* label, ImVec2 const* size) {
    return ImGui_Button(label, *size);
}

extern "C" void ImGui_CalcTextSize_wrap(const char* text, const char* text_end, bool hide_text_after_double_hash, float wrap_width, ImVec2* _out) {
    *_out = ImGui_CalcTextSize(text, text_end, hide_text_after_double_hash, wrap_width);
}

extern "C" bool ImGui_ColorButton_wrap(const char* desc_id, ImVec4 const* col, ImGuiColorEditFlags flags, ImVec2 const* size) {
    return ImGui_ColorButton(desc_id, *col, flags, *size);
}

extern "C" ImU32 ImGui_ColorConvertFloat4ToU32_wrap(ImVec4 const* in) {
    return ImGui_ColorConvertFloat4ToU32(*in);
}

extern "C" void ImGui_ColorConvertU32ToFloat4_wrap(ImU32 in, ImVec4* _out) {
    *_out = ImGui_ColorConvertU32ToFloat4(in);
}

extern "C" void ImGui_Dummy_wrap(ImVec2 const* size) {
    ImGui_Dummy(*size);
}

extern "C" ImU32 ImGui_GetColorU32ImVec4_wrap(ImVec4 const* col) {
    return ImGui_GetColorU32ImVec4(*col);
}

extern "C" void ImGui_GetContentRegionAvail_wrap(ImVec2* _out) {
    *_out = ImGui_GetContentRegionAvail();
}

extern "C" void ImGui_GetContentRegionMax_wrap(ImVec2* _out) {
    *_out = ImGui_GetContentRegionMax();
}

extern "C" void ImGui_GetCursorPos_wrap(ImVec2* _out) {
    *_out = ImGui_GetCursorPos();
}

extern "C" void ImGui_GetCursorScreenPos_wrap(ImVec2* _out) {
    *_out = ImGui_GetCursorScreenPos();
}

extern "C" void ImGui_GetCursorStartPos_wrap(ImVec2* _out) {
    *_out = ImGui_GetCursorStartPos();
}

extern "C" void ImGui_GetFontTexUvWhitePixel_wrap(ImVec2* _out) {
    *_out = ImGui_GetFontTexUvWhitePixel();
}

extern "C" void ImGui_GetItemRectMax_wrap(ImVec2* _out) {
    *_out = ImGui_GetItemRectMax();
}

extern "C" void ImGui_GetItemRectMin_wrap(ImVec2* _out) {
    *_out = ImGui_GetItemRectMin();
}

extern "C" void ImGui_GetItemRectSize_wrap(ImVec2* _out) {
    *_out = ImGui_GetItemRectSize();
}

extern "C" void ImGui_GetMouseDragDelta_wrap(ImGuiMouseButton button, float lock_threshold, ImVec2* _out) {
    *_out = ImGui_GetMouseDragDelta(button, lock_threshold);
}

extern "C" void ImGui_GetMousePos_wrap(ImVec2* _out) {
    *_out = ImGui_GetMousePos();
}

extern "C" void ImGui_GetMousePosOnOpeningCurrentPopup_wrap(ImVec2* _out) {
    *_out = ImGui_GetMousePosOnOpeningCurrentPopup();
}

extern "C" void ImGui_GetWindowContentRegionMax_wrap(ImVec2* _out) {
    *_out = ImGui_GetWindowContentRegionMax();
}

extern "C" void ImGui_GetWindowContentRegionMin_wrap(ImVec2* _out) {
    *_out = ImGui_GetWindowContentRegionMin();
}

extern "C" void ImGui_GetWindowPos_wrap(ImVec2* _out) {
    *_out = ImGui_GetWindowPos();
}

extern "C" void ImGui_GetWindowSize_wrap(ImVec2* _out) {
    *_out = ImGui_GetWindowSize();
}

extern "C" void ImGui_Image_wrap(ImTextureRef const* tex_ref, ImVec2 const* image_size, ImVec2 const* uv0, ImVec2 const* uv1) {
    ImGui_Image(*tex_ref, *image_size, *uv0, *uv1);
}

extern "C" bool ImGui_ImageButton_wrap(const char* str_id, ImTextureRef const* tex_ref, ImVec2 const* image_size, ImVec2 const* uv0, ImVec2 const* uv1, ImVec4 const* bg_col, ImVec4 const* tint_col) {
    return ImGui_ImageButton(str_id, *tex_ref, *image_size, *uv0, *uv1, *bg_col, *tint_col);
}

extern "C" void ImGui_ImageImVec4_wrap(ImTextureRef const* tex_ref, ImVec2 const* image_size, ImVec2 const* uv0, ImVec2 const* uv1, ImVec4 const* tint_col, ImVec4 const* border_col) {
    ImGui_ImageImVec4(*tex_ref, *image_size, *uv0, *uv1, *tint_col, *border_col);
}

extern "C" void ImGui_ImageWithBg_wrap(ImTextureRef const* tex_ref, ImVec2 const* image_size, ImVec2 const* uv0, ImVec2 const* uv1, ImVec4 const* bg_col, ImVec4 const* tint_col) {
    ImGui_ImageWithBg(*tex_ref, *image_size, *uv0, *uv1, *bg_col, *tint_col);
}

extern "C" bool ImGui_InputTextMultiline_wrap(const char* label, char* buf, size_t buf_size, ImVec2 const* size, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback, void* user_data) {
    return ImGui_InputTextMultiline(label, buf, buf_size, *size, flags, callback, user_data);
}

extern "C" bool ImGui_InvisibleButton_wrap(const char* str_id, ImVec2 const* size, ImGuiButtonFlags flags) {
    return ImGui_InvisibleButton(str_id, *size, flags);
}

extern "C" bool ImGui_IsMouseHoveringRect_wrap(ImVec2 const* r_min, ImVec2 const* r_max, bool clip) {
    return ImGui_IsMouseHoveringRect(*r_min, *r_max, clip);
}

extern "C" bool ImGui_IsRectVisible_wrap(ImVec2 const* rect_min, ImVec2 const* rect_max) {
    return ImGui_IsRectVisible(*rect_min, *rect_max);
}

extern "C" bool ImGui_IsRectVisibleBySize_wrap(ImVec2 const* size) {
    return ImGui_IsRectVisibleBySize(*size);
}

extern "C" void ImGui_PlotHistogram_wrap(const char* label, const float* values, int values_count, int values_offset, const char* overlay_text, float scale_min, float scale_max, ImVec2 const* graph_size, int stride) {
    ImGui_PlotHistogram(label, values, values_count, values_offset, overlay_text, scale_min, scale_max, *graph_size, stride);
}

extern "C" void ImGui_PlotHistogramCallback_wrap(const char* label, float (*values_getter)(void* data, int idx), void* data, int values_count, int values_offset, const char* overlay_text, float scale_min, float scale_max, ImVec2 const* graph_size) {
    ImGui_PlotHistogramCallback(label, values_getter, data, values_count, values_offset, overlay_text, scale_min, scale_max, *graph_size);
}

extern "C" void ImGui_PlotLines_wrap(const char* label, const float* values, int values_count, int values_offset, const char* overlay_text, float scale_min, float scale_max, ImVec2 const* graph_size, int stride) {
    ImGui_PlotLines(label, values, values_count, values_offset, overlay_text, scale_min, scale_max, *graph_size, stride);
}

extern "C" void ImGui_PlotLinesCallback_wrap(const char* label, float (*values_getter)(void* data, int idx), void* data, int values_count, int values_offset, const char* overlay_text, float scale_min, float scale_max, ImVec2 const* graph_size) {
    ImGui_PlotLinesCallback(label, values_getter, data, values_count, values_offset, overlay_text, scale_min, scale_max, *graph_size);
}

extern "C" void ImGui_ProgressBar_wrap(float fraction, ImVec2 const* size_arg, const char* overlay) {
    ImGui_ProgressBar(fraction, *size_arg, overlay);
}

extern "C" void ImGui_PushClipRect_wrap(ImVec2 const* clip_rect_min, ImVec2 const* clip_rect_max, bool intersect_with_current_clip_rect) {
    ImGui_PushClipRect(*clip_rect_min, *clip_rect_max, intersect_with_current_clip_rect);
}

extern "C" void ImGui_PushStyleColorImVec4_wrap(ImGuiCol idx, ImVec4 const* col) {
    ImGui_PushStyleColorImVec4(idx, *col);
}

extern "C" void ImGui_PushStyleVarImVec2_wrap(ImGuiStyleVar idx, ImVec2 const* val) {
    ImGui_PushStyleVarImVec2(idx, *val);
}

extern "C" bool ImGui_Selectable_wrap(const char* label, bool selected, ImGuiSelectableFlags flags, ImVec2 const* size) {
    return ImGui_Selectable(label, selected, flags, *size);
}

extern "C" bool ImGui_SelectableBoolPtr_wrap(const char* label, bool* p_selected, ImGuiSelectableFlags flags, ImVec2 const* size) {
    return ImGui_SelectableBoolPtr(label, p_selected, flags, *size);
}

extern "C" void ImGui_SetCursorPos_wrap(ImVec2 const* local_pos) {
    ImGui_SetCursorPos(*local_pos);
}

extern "C" void ImGui_SetCursorScreenPos_wrap(ImVec2 const* pos) {
    ImGui_SetCursorScreenPos(*pos);
}

extern "C" void ImGui_SetNextWindowContentSize_wrap(ImVec2 const* size) {
    ImGui_SetNextWindowContentSize(*size);
}

extern "C" void ImGui_SetNextWindowPos_wrap(ImVec2 const* pos, ImGuiCond cond, ImVec2 const* pivot) {
    ImGui_SetNextWindowPos(*pos, cond, *pivot);
}

extern "C" void ImGui_SetNextWindowScroll_wrap(ImVec2 const* scroll) {
    ImGui_SetNextWindowScroll(*scroll);
}

extern "C" void ImGui_SetNextWindowSize_wrap(ImVec2 const* size, ImGuiCond cond) {
    ImGui_SetNextWindowSize(*size, cond);
}

extern "C" void ImGui_SetNextWindowSizeConstraints_wrap(ImVec2 const* size_min, ImVec2 const* size_max, ImGuiSizeCallback custom_callback, void* custom_callback_data) {
    ImGui_SetNextWindowSizeConstraints(*size_min, *size_max, custom_callback, custom_callback_data);
}

extern "C" void ImGui_SetWindowPos_wrap(ImVec2 const* pos, ImGuiCond cond) {
    ImGui_SetWindowPos(*pos, cond);
}

extern "C" void ImGui_SetWindowPosStr_wrap(const char* name, ImVec2 const* pos, ImGuiCond cond) {
    ImGui_SetWindowPosStr(name, *pos, cond);
}

extern "C" void ImGui_SetWindowSize_wrap(ImVec2 const* size, ImGuiCond cond) {
    ImGui_SetWindowSize(*size, cond);
}

extern "C" void ImGui_SetWindowSizeStr_wrap(const char* name, ImVec2 const* size, ImGuiCond cond) {
    ImGui_SetWindowSizeStr(name, *size, cond);
}

extern "C" bool ImGui_VSliderFloat_wrap(const char* label, ImVec2 const* size, float* v, float v_min, float v_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_VSliderFloat(label, *size, v, v_min, v_max, format, flags);
}

extern "C" bool ImGui_VSliderInt_wrap(const char* label, ImVec2 const* size, int* v, int v_min, int v_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_VSliderInt(label, *size, v, v_min, v_max, format, flags);
}

extern "C" bool ImGui_VSliderScalar_wrap(const char* label, ImVec2 const* size, ImGuiDataType data_type, void* p_data, const void* p_min, const void* p_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_VSliderScalar(label, *size, data_type, p_data, p_min, p_max, format, flags);
}

extern "C" void ImGuiViewport_GetCenter_wrap(const ImGuiViewport* self, ImVec2* _out) {
    *_out = ImGuiViewport_GetCenter(self);
}

extern "C" void ImGuiViewport_GetWorkCenter_wrap(const ImGuiViewport* self, ImVec2* _out) {
    *_out = ImGuiViewport_GetWorkCenter(self);
}

extern "C" void ImTextureData_GetTexRef_wrap(ImTextureData* self, ImTextureRef* _out) {
    *_out = ImTextureData_GetTexRef(self);
}

