// Generated by dear-bindings-ffi. Do not edit.
#ifndef DEAR_IMGUI_WRAPPERS_H
#define DEAR_IMGUI_WRAPPERS_H

#include "dcimgui_impl_vulkan.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

#endif
