{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.ImColor where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types

#include "dcimgui_nodefaultargfunctions.h"

-- functions

foreign import capi unsafe "DearImGuiWrappers.h ImColor_HSV_wrap"
  c_imColor_HSV :: CFloat -> CFloat -> CFloat -> CFloat -> (Ptr ImColor) -> IO ()

imColor_HSV :: CFloat -> CFloat -> CFloat -> CFloat -> IO ImColor
imColor_HSV h s v a =
  alloca $ \_pOut -> c_imColor_HSV h s v a _pOut >> peek _pOut

-- C: void SetHSV(ImColor* self, float h, float s, float v, float a)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImColor_SetHSV"
  imColor_SetHSV :: (Ptr ImColor) -> CFloat -> CFloat -> CFloat -> CFloat -> IO ()
