{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.ImGuiViewport where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types

#include "dcimgui_nodefaultargfunctions.h"

-- functions

foreign import capi unsafe "DearImGuiWrappers.h ImGuiViewport_GetCenter_wrap"
  c_imGuiViewport_GetCenter :: (Ptr ImGuiViewport) -> (Ptr ImVec2) -> IO ()

imGuiViewport_GetCenter :: (Ptr ImGuiViewport) -> IO ImVec2
imGuiViewport_GetCenter self =
  alloca $ \_pOut -> c_imGuiViewport_GetCenter self _pOut >> peek _pOut

-- C: const char* GetDebugName(const ImGuiViewport* self)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGuiViewport_GetDebugName"
  imGuiViewport_GetDebugName :: (Ptr ImGuiViewport) -> IO CString
foreign import capi unsafe "DearImGuiWrappers.h ImGuiViewport_GetWorkCenter_wrap"
  c_imGuiViewport_GetWorkCenter :: (Ptr ImGuiViewport) -> (Ptr ImVec2) -> IO ()

imGuiViewport_GetWorkCenter :: (Ptr ImGuiViewport) -> IO ImVec2
imGuiViewport_GetWorkCenter self =
  alloca $ \_pOut -> c_imGuiViewport_GetWorkCenter self _pOut >> peek _pOut

