{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.ImGui where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types

#include "dcimgui_nodefaultargfunctions.h"

-- functions

-- C: const ImGuiPayload* ImGui::AcceptDragDropPayload(const char* type, ImGuiDragDropFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_AcceptDragDropPayload"
  imGui_AcceptDragDropPayload :: CString -> ImGuiDragDropFlags -> IO (Ptr ImGuiPayload)
-- C: void ImGui::AlignTextToFramePadding()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_AlignTextToFramePadding"
  imGui_AlignTextToFramePadding :: IO ()
-- C: bool ImGui::ArrowButton(const char* str_id, ImGuiDir dir)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_ArrowButton"
  imGui_ArrowButton :: CString -> ImGuiDir -> IO CBool
-- C: bool ImGui::Begin(const char* name, bool* p_open, ImGuiWindowFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_Begin"
  imGui_Begin :: CString -> (Ptr CBool) -> ImGuiWindowFlags -> IO CBool
foreign import capi unsafe "DearImGuiWrappers.h ImGui_BeginChild_wrap"
  c_imGui_BeginChild :: CString -> (Ptr ImVec2) -> ImGuiChildFlags -> ImGuiWindowFlags -> IO CBool

imGui_BeginChild :: CString -> ImVec2 -> ImGuiChildFlags -> ImGuiWindowFlags -> IO CBool
imGui_BeginChild str_id size child_flags window_flags =
  with size $ \_p1 -> c_imGui_BeginChild str_id _p1 child_flags window_flags

foreign import capi unsafe "DearImGuiWrappers.h ImGui_BeginChildID_wrap"
  c_imGui_BeginChildID :: ImGuiID -> (Ptr ImVec2) -> ImGuiChildFlags -> ImGuiWindowFlags -> IO CBool

imGui_BeginChildID :: ImGuiID -> ImVec2 -> ImGuiChildFlags -> ImGuiWindowFlags -> IO CBool
imGui_BeginChildID id_ size child_flags window_flags =
  with size $ \_p1 -> c_imGui_BeginChildID id_ _p1 child_flags window_flags

-- C: bool ImGui::BeginCombo(const char* label, const char* preview_value, ImGuiComboFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_BeginCombo"
  imGui_BeginCombo :: CString -> CString -> ImGuiComboFlags -> IO CBool
-- C: void ImGui::BeginDisabled(bool disabled)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_BeginDisabled"
  imGui_BeginDisabled :: CBool -> IO ()
-- C: bool ImGui::BeginDragDropSource(ImGuiDragDropFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_BeginDragDropSource"
  imGui_BeginDragDropSource :: ImGuiDragDropFlags -> IO CBool
-- C: bool ImGui::BeginDragDropTarget()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_BeginDragDropTarget"
  imGui_BeginDragDropTarget :: IO CBool
-- C: void ImGui::BeginGroup()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_BeginGroup"
  imGui_BeginGroup :: IO ()
-- C: bool ImGui::BeginItemTooltip()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_BeginItemTooltip"
  imGui_BeginItemTooltip :: IO CBool
foreign import capi unsafe "DearImGuiWrappers.h ImGui_BeginListBox_wrap"
  c_imGui_BeginListBox :: CString -> (Ptr ImVec2) -> IO CBool

imGui_BeginListBox :: CString -> ImVec2 -> IO CBool
imGui_BeginListBox label size =
  with size $ \_p1 -> c_imGui_BeginListBox label _p1

-- C: bool ImGui::BeginMainMenuBar()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_BeginMainMenuBar"
  imGui_BeginMainMenuBar :: IO CBool
-- C: bool ImGui::BeginMenu(const char* label, bool enabled)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_BeginMenu"
  imGui_BeginMenu :: CString -> CBool -> IO CBool
-- C: bool ImGui::BeginMenuBar()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_BeginMenuBar"
  imGui_BeginMenuBar :: IO CBool
-- C: ImGuiMultiSelectIO* ImGui::BeginMultiSelect(ImGuiMultiSelectFlags flags, int selection_size, int items_count)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_BeginMultiSelect"
  imGui_BeginMultiSelect :: ImGuiMultiSelectFlags -> CInt -> CInt -> IO (Ptr ImGuiMultiSelectIO)
-- C: bool ImGui::BeginPopup(const char* str_id, ImGuiWindowFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_BeginPopup"
  imGui_BeginPopup :: CString -> ImGuiWindowFlags -> IO CBool
-- C: bool ImGui::BeginPopupContextItem(const char* str_id, ImGuiPopupFlags popup_flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_BeginPopupContextItem"
  imGui_BeginPopupContextItem :: CString -> ImGuiPopupFlags -> IO CBool
-- C: bool ImGui::BeginPopupContextVoid(const char* str_id, ImGuiPopupFlags popup_flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_BeginPopupContextVoid"
  imGui_BeginPopupContextVoid :: CString -> ImGuiPopupFlags -> IO CBool
-- C: bool ImGui::BeginPopupContextWindow(const char* str_id, ImGuiPopupFlags popup_flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_BeginPopupContextWindow"
  imGui_BeginPopupContextWindow :: CString -> ImGuiPopupFlags -> IO CBool
-- C: bool ImGui::BeginPopupModal(const char* name, bool* p_open, ImGuiWindowFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_BeginPopupModal"
  imGui_BeginPopupModal :: CString -> (Ptr CBool) -> ImGuiWindowFlags -> IO CBool
-- C: bool ImGui::BeginTabBar(const char* str_id, ImGuiTabBarFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_BeginTabBar"
  imGui_BeginTabBar :: CString -> ImGuiTabBarFlags -> IO CBool
-- C: bool ImGui::BeginTabItem(const char* label, bool* p_open, ImGuiTabItemFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_BeginTabItem"
  imGui_BeginTabItem :: CString -> (Ptr CBool) -> ImGuiTabItemFlags -> IO CBool
foreign import capi unsafe "DearImGuiWrappers.h ImGui_BeginTable_wrap"
  c_imGui_BeginTable :: CString -> CInt -> ImGuiTableFlags -> (Ptr ImVec2) -> CFloat -> IO CBool

imGui_BeginTable :: CString -> CInt -> ImGuiTableFlags -> ImVec2 -> CFloat -> IO CBool
imGui_BeginTable str_id columns flags outer_size inner_width =
  with outer_size $ \_p3 -> c_imGui_BeginTable str_id columns flags _p3 inner_width

-- C: bool ImGui::BeginTooltip()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_BeginTooltip"
  imGui_BeginTooltip :: IO CBool
-- C: void ImGui::Bullet()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_Bullet"
  imGui_Bullet :: IO ()
foreign import capi unsafe "DearImGuiWrappers.h ImGui_Button_wrap"
  c_imGui_Button :: CString -> (Ptr ImVec2) -> IO CBool

imGui_Button :: CString -> ImVec2 -> IO CBool
imGui_Button label size =
  with size $ \_p1 -> c_imGui_Button label _p1

-- C: float ImGui::CalcItemWidth()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_CalcItemWidth"
  imGui_CalcItemWidth :: IO CFloat
foreign import capi unsafe "DearImGuiWrappers.h ImGui_CalcTextSize_wrap"
  c_imGui_CalcTextSize :: CString -> CString -> CBool -> CFloat -> (Ptr ImVec2) -> IO ()

imGui_CalcTextSize :: CString -> CString -> CBool -> CFloat -> IO ImVec2
imGui_CalcTextSize text text_end hide_text_after_double_hash wrap_width =
  alloca $ \_pOut -> c_imGui_CalcTextSize text text_end hide_text_after_double_hash wrap_width _pOut >> peek _pOut

-- C: bool ImGui::Checkbox(const char* label, bool* v)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_Checkbox"
  imGui_Checkbox :: CString -> (Ptr CBool) -> IO CBool
-- C: bool ImGui::CheckboxFlags(const char* label, int* flags, int flags_value)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_CheckboxFlagsIntPtr"
  imGui_CheckboxFlagsIntPtr :: CString -> (Ptr CInt) -> CInt -> IO CBool
-- C: bool ImGui::CheckboxFlags(const char* label, unsigned int* flags, unsigned int flags_value)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_CheckboxFlagsUintPtr"
  imGui_CheckboxFlagsUintPtr :: CString -> (Ptr CUInt) -> CUInt -> IO CBool
-- C: void ImGui::CloseCurrentPopup()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_CloseCurrentPopup"
  imGui_CloseCurrentPopup :: IO ()
-- C: bool ImGui::CollapsingHeader(const char* label, ImGuiTreeNodeFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_CollapsingHeader"
  imGui_CollapsingHeader :: CString -> ImGuiTreeNodeFlags -> IO CBool
-- C: bool ImGui::CollapsingHeader(const char* label, bool* p_visible, ImGuiTreeNodeFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_CollapsingHeaderBoolPtr"
  imGui_CollapsingHeaderBoolPtr :: CString -> (Ptr CBool) -> ImGuiTreeNodeFlags -> IO CBool
foreign import capi unsafe "DearImGuiWrappers.h ImGui_ColorButton_wrap"
  c_imGui_ColorButton :: CString -> (Ptr ImVec4) -> ImGuiColorEditFlags -> (Ptr ImVec2) -> IO CBool

imGui_ColorButton :: CString -> ImVec4 -> ImGuiColorEditFlags -> ImVec2 -> IO CBool
imGui_ColorButton desc_id col flags size =
  with col $ \_p1 -> with size $ \_p3 -> c_imGui_ColorButton desc_id _p1 flags _p3

foreign import capi unsafe "DearImGuiWrappers.h ImGui_ColorConvertFloat4ToU32_wrap"
  c_imGui_ColorConvertFloat4ToU32 :: (Ptr ImVec4) -> IO ImU32

imGui_ColorConvertFloat4ToU32 :: ImVec4 -> IO ImU32
imGui_ColorConvertFloat4ToU32 in_ =
  with in_ $ \_p0 -> c_imGui_ColorConvertFloat4ToU32 _p0

-- C: void ImGui::ColorConvertHSVtoRGB(float h, float s, float v, float* out_r, float* out_g, float* out_b)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_ColorConvertHSVtoRGB"
  imGui_ColorConvertHSVtoRGB :: CFloat -> CFloat -> CFloat -> (Ptr CFloat) -> (Ptr CFloat) -> (Ptr CFloat) -> IO ()
-- C: void ImGui::ColorConvertRGBtoHSV(float r, float g, float b, float* out_h, float* out_s, float* out_v)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_ColorConvertRGBtoHSV"
  imGui_ColorConvertRGBtoHSV :: CFloat -> CFloat -> CFloat -> (Ptr CFloat) -> (Ptr CFloat) -> (Ptr CFloat) -> IO ()
foreign import capi unsafe "DearImGuiWrappers.h ImGui_ColorConvertU32ToFloat4_wrap"
  c_imGui_ColorConvertU32ToFloat4 :: ImU32 -> (Ptr ImVec4) -> IO ()

imGui_ColorConvertU32ToFloat4 :: ImU32 -> IO ImVec4
imGui_ColorConvertU32ToFloat4 in_ =
  alloca $ \_pOut -> c_imGui_ColorConvertU32ToFloat4 in_ _pOut >> peek _pOut

-- C: bool ImGui::ColorEdit3(const char* label, float[3] col, ImGuiColorEditFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_ColorEdit3"
  imGui_ColorEdit3 :: CString -> (Ptr CFloat) -> ImGuiColorEditFlags -> IO CBool
-- C: bool ImGui::ColorEdit4(const char* label, float[4] col, ImGuiColorEditFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_ColorEdit4"
  imGui_ColorEdit4 :: CString -> (Ptr CFloat) -> ImGuiColorEditFlags -> IO CBool
-- C: bool ImGui::ColorPicker3(const char* label, float[3] col, ImGuiColorEditFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_ColorPicker3"
  imGui_ColorPicker3 :: CString -> (Ptr CFloat) -> ImGuiColorEditFlags -> IO CBool
-- C: bool ImGui::ColorPicker4(const char* label, float[4] col, ImGuiColorEditFlags flags, const float* ref_col)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_ColorPicker4"
  imGui_ColorPicker4 :: CString -> (Ptr CFloat) -> ImGuiColorEditFlags -> (Ptr CFloat) -> IO CBool
-- C: void ImGui::Columns(int count, const char* id, bool borders)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_Columns"
  imGui_Columns :: CInt -> CString -> CBool -> IO ()
-- C: bool ImGui::Combo(const char* label, int* current_item, const char* items_separated_by_zeros, int popup_max_height_in_items)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_Combo"
  imGui_Combo :: CString -> (Ptr CInt) -> CString -> CInt -> IO CBool
-- C: bool ImGui::Combo(const char* label, int* current_item, const char* (*getter)(void* user_data, int idx) getter, void* user_data, int items_count, int popup_max_height_in_items)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_ComboCallback"
  imGui_ComboCallback :: CString -> (Ptr CInt) -> (FunPtr ((Ptr ()) -> CInt -> IO CString)) -> (Ptr ()) -> CInt -> CInt -> IO CBool
-- C: bool ImGui::Combo(const char* label, int* current_item, const char*const[] items, int items_count, int popup_max_height_in_items)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_ComboChar"
  imGui_ComboChar :: CString -> (Ptr CInt) -> (Ptr CString) -> CInt -> CInt -> IO CBool
-- C: ImGuiContext* ImGui::CreateContext(ImFontAtlas* shared_font_atlas)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_CreateContext"
  imGui_CreateContext :: (Ptr ImFontAtlas) -> IO (Ptr ImGuiContext)
-- C: bool ImGui::DebugCheckVersionAndDataLayout(const char* version_str, size_t sz_io, size_t sz_style, size_t sz_vec2, size_t sz_vec4, size_t sz_drawvert, size_t sz_drawidx)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_DebugCheckVersionAndDataLayout"
  imGui_DebugCheckVersionAndDataLayout :: CString -> CSize -> CSize -> CSize -> CSize -> CSize -> CSize -> IO CBool
-- C: void ImGui::DebugFlashStyleColor(ImGuiCol idx)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_DebugFlashStyleColor"
  imGui_DebugFlashStyleColor :: ImGuiCol -> IO ()
-- C: void ImGui::DebugStartItemPicker()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_DebugStartItemPicker"
  imGui_DebugStartItemPicker :: IO ()
-- C: void ImGui::DebugTextEncoding(const char* text)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_DebugTextEncoding"
  imGui_DebugTextEncoding :: CString -> IO ()
-- C: void ImGui::DestroyContext(ImGuiContext* ctx)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_DestroyContext"
  imGui_DestroyContext :: (Ptr ImGuiContext) -> IO ()
-- C: void ImGui::DestroyPlatformWindows()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_DestroyPlatformWindows"
  imGui_DestroyPlatformWindows :: IO ()
foreign import capi unsafe "DearImGuiWrappers.h ImGui_DockSpace_wrap"
  c_imGui_DockSpace :: ImGuiID -> (Ptr ImVec2) -> ImGuiDockNodeFlags -> (Ptr ImGuiWindowClass) -> IO ImGuiID

imGui_DockSpace :: ImGuiID -> ImVec2 -> ImGuiDockNodeFlags -> (Ptr ImGuiWindowClass) -> IO ImGuiID
imGui_DockSpace dockspace_id size flags window_class =
  with size $ \_p1 -> c_imGui_DockSpace dockspace_id _p1 flags window_class

-- C: ImGuiID ImGui::DockSpaceOverViewport(ImGuiID dockspace_id, const ImGuiViewport* viewport, ImGuiDockNodeFlags flags, const ImGuiWindowClass* window_class)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_DockSpaceOverViewport"
  imGui_DockSpaceOverViewport :: ImGuiID -> (Ptr ImGuiViewport) -> ImGuiDockNodeFlags -> (Ptr ImGuiWindowClass) -> IO ImGuiID
-- C: bool ImGui::DragFloat(const char* label, float* v, float v_speed, float v_min, float v_max, const char* format, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_DragFloat"
  imGui_DragFloat :: CString -> (Ptr CFloat) -> CFloat -> CFloat -> CFloat -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::DragFloat2(const char* label, float[2] v, float v_speed, float v_min, float v_max, const char* format, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_DragFloat2"
  imGui_DragFloat2 :: CString -> (Ptr CFloat) -> CFloat -> CFloat -> CFloat -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::DragFloat3(const char* label, float[3] v, float v_speed, float v_min, float v_max, const char* format, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_DragFloat3"
  imGui_DragFloat3 :: CString -> (Ptr CFloat) -> CFloat -> CFloat -> CFloat -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::DragFloat4(const char* label, float[4] v, float v_speed, float v_min, float v_max, const char* format, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_DragFloat4"
  imGui_DragFloat4 :: CString -> (Ptr CFloat) -> CFloat -> CFloat -> CFloat -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::DragFloatRange2(const char* label, float* v_current_min, float* v_current_max, float v_speed, float v_min, float v_max, const char* format, const char* format_max, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_DragFloatRange2"
  imGui_DragFloatRange2 :: CString -> (Ptr CFloat) -> (Ptr CFloat) -> CFloat -> CFloat -> CFloat -> CString -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::DragInt(const char* label, int* v, float v_speed, int v_min, int v_max, const char* format, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_DragInt"
  imGui_DragInt :: CString -> (Ptr CInt) -> CFloat -> CInt -> CInt -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::DragInt2(const char* label, int[2] v, float v_speed, int v_min, int v_max, const char* format, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_DragInt2"
  imGui_DragInt2 :: CString -> (Ptr CInt) -> CFloat -> CInt -> CInt -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::DragInt3(const char* label, int[3] v, float v_speed, int v_min, int v_max, const char* format, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_DragInt3"
  imGui_DragInt3 :: CString -> (Ptr CInt) -> CFloat -> CInt -> CInt -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::DragInt4(const char* label, int[4] v, float v_speed, int v_min, int v_max, const char* format, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_DragInt4"
  imGui_DragInt4 :: CString -> (Ptr CInt) -> CFloat -> CInt -> CInt -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::DragIntRange2(const char* label, int* v_current_min, int* v_current_max, float v_speed, int v_min, int v_max, const char* format, const char* format_max, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_DragIntRange2"
  imGui_DragIntRange2 :: CString -> (Ptr CInt) -> (Ptr CInt) -> CFloat -> CInt -> CInt -> CString -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::DragScalar(const char* label, ImGuiDataType data_type, void* p_data, float v_speed, const void* p_min, const void* p_max, const char* format, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_DragScalar"
  imGui_DragScalar :: CString -> ImGuiDataType -> (Ptr ()) -> CFloat -> (Ptr ()) -> (Ptr ()) -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::DragScalarN(const char* label, ImGuiDataType data_type, void* p_data, int components, float v_speed, const void* p_min, const void* p_max, const char* format, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_DragScalarN"
  imGui_DragScalarN :: CString -> ImGuiDataType -> (Ptr ()) -> CInt -> CFloat -> (Ptr ()) -> (Ptr ()) -> CString -> ImGuiSliderFlags -> IO CBool
foreign import capi unsafe "DearImGuiWrappers.h ImGui_Dummy_wrap"
  c_imGui_Dummy :: (Ptr ImVec2) -> IO ()

imGui_Dummy :: ImVec2 -> IO ()
imGui_Dummy size =
  with size $ \_p0 -> c_imGui_Dummy _p0

-- C: void ImGui::End()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_End"
  imGui_End :: IO ()
-- C: void ImGui::EndChild()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_EndChild"
  imGui_EndChild :: IO ()
-- C: void ImGui::EndCombo()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_EndCombo"
  imGui_EndCombo :: IO ()
-- C: void ImGui::EndDisabled()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_EndDisabled"
  imGui_EndDisabled :: IO ()
-- C: void ImGui::EndDragDropSource()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_EndDragDropSource"
  imGui_EndDragDropSource :: IO ()
-- C: void ImGui::EndDragDropTarget()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_EndDragDropTarget"
  imGui_EndDragDropTarget :: IO ()
-- C: void ImGui::EndFrame()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_EndFrame"
  imGui_EndFrame :: IO ()
-- C: void ImGui::EndGroup()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_EndGroup"
  imGui_EndGroup :: IO ()
-- C: void ImGui::EndListBox()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_EndListBox"
  imGui_EndListBox :: IO ()
-- C: void ImGui::EndMainMenuBar()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_EndMainMenuBar"
  imGui_EndMainMenuBar :: IO ()
-- C: void ImGui::EndMenu()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_EndMenu"
  imGui_EndMenu :: IO ()
-- C: void ImGui::EndMenuBar()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_EndMenuBar"
  imGui_EndMenuBar :: IO ()
-- C: ImGuiMultiSelectIO* ImGui::EndMultiSelect()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_EndMultiSelect"
  imGui_EndMultiSelect :: IO (Ptr ImGuiMultiSelectIO)
-- C: void ImGui::EndPopup()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_EndPopup"
  imGui_EndPopup :: IO ()
-- C: void ImGui::EndTabBar()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_EndTabBar"
  imGui_EndTabBar :: IO ()
-- C: void ImGui::EndTabItem()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_EndTabItem"
  imGui_EndTabItem :: IO ()
-- C: void ImGui::EndTable()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_EndTable"
  imGui_EndTable :: IO ()
-- C: void ImGui::EndTooltip()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_EndTooltip"
  imGui_EndTooltip :: IO ()
-- C: ImGuiViewport* ImGui::FindViewportByID(ImGuiID viewport_id)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_FindViewportByID"
  imGui_FindViewportByID :: ImGuiID -> IO (Ptr ImGuiViewport)
-- C: ImGuiViewport* ImGui::FindViewportByPlatformHandle(void* platform_handle)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_FindViewportByPlatformHandle"
  imGui_FindViewportByPlatformHandle :: (Ptr ()) -> IO (Ptr ImGuiViewport)
-- C: void ImGui::GetAllocatorFunctions(ImGuiMemAllocFunc* p_alloc_func, ImGuiMemFreeFunc* p_free_func, void** p_user_data)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetAllocatorFunctions"
  imGui_GetAllocatorFunctions :: (Ptr ImGuiMemAllocFunc) -> (Ptr ImGuiMemFreeFunc) -> (Ptr (Ptr ())) -> IO ()
-- C: ImDrawList* ImGui::GetBackgroundDrawList(ImGuiViewport* viewport)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetBackgroundDrawList"
  imGui_GetBackgroundDrawList :: (Ptr ImGuiViewport) -> IO (Ptr ImDrawList)
-- C: const char* ImGui::GetClipboardText()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetClipboardText"
  imGui_GetClipboardText :: IO CString
-- C: ImU32 ImGui::GetColorU32(ImGuiCol idx, float alpha_mul)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetColorU32"
  imGui_GetColorU32 :: ImGuiCol -> CFloat -> IO ImU32
-- C: ImU32 ImGui::GetColorU32(ImU32 col, float alpha_mul)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetColorU32ImU32"
  imGui_GetColorU32ImU32 :: ImU32 -> CFloat -> IO ImU32
foreign import capi unsafe "DearImGuiWrappers.h ImGui_GetColorU32ImVec4_wrap"
  c_imGui_GetColorU32ImVec4 :: (Ptr ImVec4) -> IO ImU32

imGui_GetColorU32ImVec4 :: ImVec4 -> IO ImU32
imGui_GetColorU32ImVec4 col =
  with col $ \_p0 -> c_imGui_GetColorU32ImVec4 _p0

-- C: int ImGui::GetColumnIndex()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetColumnIndex"
  imGui_GetColumnIndex :: IO CInt
-- C: float ImGui::GetColumnOffset(int column_index)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetColumnOffset"
  imGui_GetColumnOffset :: CInt -> IO CFloat
-- C: float ImGui::GetColumnWidth(int column_index)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetColumnWidth"
  imGui_GetColumnWidth :: CInt -> IO CFloat
-- C: int ImGui::GetColumnsCount()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetColumnsCount"
  imGui_GetColumnsCount :: IO CInt
foreign import capi unsafe "DearImGuiWrappers.h ImGui_GetContentRegionAvail_wrap"
  c_imGui_GetContentRegionAvail :: (Ptr ImVec2) -> IO ()

imGui_GetContentRegionAvail :: IO ImVec2
imGui_GetContentRegionAvail =
  alloca $ \_pOut -> c_imGui_GetContentRegionAvail _pOut >> peek _pOut

foreign import capi unsafe "DearImGuiWrappers.h ImGui_GetContentRegionMax_wrap"
  c_imGui_GetContentRegionMax :: (Ptr ImVec2) -> IO ()

imGui_GetContentRegionMax :: IO ImVec2
imGui_GetContentRegionMax =
  alloca $ \_pOut -> c_imGui_GetContentRegionMax _pOut >> peek _pOut

-- C: ImGuiContext* ImGui::GetCurrentContext()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetCurrentContext"
  imGui_GetCurrentContext :: IO (Ptr ImGuiContext)
foreign import capi unsafe "DearImGuiWrappers.h ImGui_GetCursorPos_wrap"
  c_imGui_GetCursorPos :: (Ptr ImVec2) -> IO ()

imGui_GetCursorPos :: IO ImVec2
imGui_GetCursorPos =
  alloca $ \_pOut -> c_imGui_GetCursorPos _pOut >> peek _pOut

-- C: float ImGui::GetCursorPosX()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetCursorPosX"
  imGui_GetCursorPosX :: IO CFloat
-- C: float ImGui::GetCursorPosY()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetCursorPosY"
  imGui_GetCursorPosY :: IO CFloat
foreign import capi unsafe "DearImGuiWrappers.h ImGui_GetCursorScreenPos_wrap"
  c_imGui_GetCursorScreenPos :: (Ptr ImVec2) -> IO ()

imGui_GetCursorScreenPos :: IO ImVec2
imGui_GetCursorScreenPos =
  alloca $ \_pOut -> c_imGui_GetCursorScreenPos _pOut >> peek _pOut

foreign import capi unsafe "DearImGuiWrappers.h ImGui_GetCursorStartPos_wrap"
  c_imGui_GetCursorStartPos :: (Ptr ImVec2) -> IO ()

imGui_GetCursorStartPos :: IO ImVec2
imGui_GetCursorStartPos =
  alloca $ \_pOut -> c_imGui_GetCursorStartPos _pOut >> peek _pOut

-- C: const ImGuiPayload* ImGui::GetDragDropPayload()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetDragDropPayload"
  imGui_GetDragDropPayload :: IO (Ptr ImGuiPayload)
-- C: ImDrawData* ImGui::GetDrawData()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetDrawData"
  imGui_GetDrawData :: IO (Ptr ImDrawData)
-- C: ImDrawListSharedData* ImGui::GetDrawListSharedData()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetDrawListSharedData"
  imGui_GetDrawListSharedData :: IO (Ptr ImDrawListSharedData)
-- C: ImFont* ImGui::GetFont()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetFont"
  imGui_GetFont :: IO (Ptr ImFont)
-- C: ImFontBaked* ImGui::GetFontBaked()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetFontBaked"
  imGui_GetFontBaked :: IO (Ptr ImFontBaked)
-- C: float ImGui::GetFontSize()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetFontSize"
  imGui_GetFontSize :: IO CFloat
foreign import capi unsafe "DearImGuiWrappers.h ImGui_GetFontTexUvWhitePixel_wrap"
  c_imGui_GetFontTexUvWhitePixel :: (Ptr ImVec2) -> IO ()

imGui_GetFontTexUvWhitePixel :: IO ImVec2
imGui_GetFontTexUvWhitePixel =
  alloca $ \_pOut -> c_imGui_GetFontTexUvWhitePixel _pOut >> peek _pOut

-- C: ImDrawList* ImGui::GetForegroundDrawList(ImGuiViewport* viewport)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetForegroundDrawList"
  imGui_GetForegroundDrawList :: (Ptr ImGuiViewport) -> IO (Ptr ImDrawList)
-- C: int ImGui::GetFrameCount()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetFrameCount"
  imGui_GetFrameCount :: IO CInt
-- C: float ImGui::GetFrameHeight()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetFrameHeight"
  imGui_GetFrameHeight :: IO CFloat
-- C: float ImGui::GetFrameHeightWithSpacing()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetFrameHeightWithSpacing"
  imGui_GetFrameHeightWithSpacing :: IO CFloat
-- C: ImGuiID ImGui::GetID(const char* str_id)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetID"
  imGui_GetID :: CString -> IO ImGuiID
-- C: ImGuiID ImGui::GetID(int int_id)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetIDInt"
  imGui_GetIDInt :: CInt -> IO ImGuiID
-- C: ImGuiID ImGui::GetID(const void* ptr_id)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetIDPtr"
  imGui_GetIDPtr :: (Ptr ()) -> IO ImGuiID
-- C: ImGuiID ImGui::GetID(const char* str_id_begin, const char* str_id_end)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetIDStr"
  imGui_GetIDStr :: CString -> CString -> IO ImGuiID
-- C: ImGuiIO* ImGui::GetIO()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetIO"
  imGui_GetIO :: IO (Ptr ImGuiIO)
-- C: ImGuiItemFlags ImGui::GetItemFlags()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetItemFlags"
  imGui_GetItemFlags :: IO ImGuiItemFlags
-- C: ImGuiID ImGui::GetItemID()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetItemID"
  imGui_GetItemID :: IO ImGuiID
foreign import capi unsafe "DearImGuiWrappers.h ImGui_GetItemRectMax_wrap"
  c_imGui_GetItemRectMax :: (Ptr ImVec2) -> IO ()

imGui_GetItemRectMax :: IO ImVec2
imGui_GetItemRectMax =
  alloca $ \_pOut -> c_imGui_GetItemRectMax _pOut >> peek _pOut

foreign import capi unsafe "DearImGuiWrappers.h ImGui_GetItemRectMin_wrap"
  c_imGui_GetItemRectMin :: (Ptr ImVec2) -> IO ()

imGui_GetItemRectMin :: IO ImVec2
imGui_GetItemRectMin =
  alloca $ \_pOut -> c_imGui_GetItemRectMin _pOut >> peek _pOut

foreign import capi unsafe "DearImGuiWrappers.h ImGui_GetItemRectSize_wrap"
  c_imGui_GetItemRectSize :: (Ptr ImVec2) -> IO ()

imGui_GetItemRectSize :: IO ImVec2
imGui_GetItemRectSize =
  alloca $ \_pOut -> c_imGui_GetItemRectSize _pOut >> peek _pOut

-- C: const char* ImGui::GetKeyName(ImGuiKey key)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetKeyName"
  imGui_GetKeyName :: ImGuiKey -> IO CString
-- C: int ImGui::GetKeyPressedAmount(ImGuiKey key, float repeat_delay, float rate)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetKeyPressedAmount"
  imGui_GetKeyPressedAmount :: ImGuiKey -> CFloat -> CFloat -> IO CInt
-- C: ImGuiViewport* ImGui::GetMainViewport()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetMainViewport"
  imGui_GetMainViewport :: IO (Ptr ImGuiViewport)
-- C: int ImGui::GetMouseClickedCount(ImGuiMouseButton button)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetMouseClickedCount"
  imGui_GetMouseClickedCount :: ImGuiMouseButton -> IO CInt
-- C: ImGuiMouseCursor ImGui::GetMouseCursor()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetMouseCursor"
  imGui_GetMouseCursor :: IO ImGuiMouseCursor
foreign import capi unsafe "DearImGuiWrappers.h ImGui_GetMouseDragDelta_wrap"
  c_imGui_GetMouseDragDelta :: ImGuiMouseButton -> CFloat -> (Ptr ImVec2) -> IO ()

imGui_GetMouseDragDelta :: ImGuiMouseButton -> CFloat -> IO ImVec2
imGui_GetMouseDragDelta button lock_threshold =
  alloca $ \_pOut -> c_imGui_GetMouseDragDelta button lock_threshold _pOut >> peek _pOut

foreign import capi unsafe "DearImGuiWrappers.h ImGui_GetMousePos_wrap"
  c_imGui_GetMousePos :: (Ptr ImVec2) -> IO ()

imGui_GetMousePos :: IO ImVec2
imGui_GetMousePos =
  alloca $ \_pOut -> c_imGui_GetMousePos _pOut >> peek _pOut

foreign import capi unsafe "DearImGuiWrappers.h ImGui_GetMousePosOnOpeningCurrentPopup_wrap"
  c_imGui_GetMousePosOnOpeningCurrentPopup :: (Ptr ImVec2) -> IO ()

imGui_GetMousePosOnOpeningCurrentPopup :: IO ImVec2
imGui_GetMousePosOnOpeningCurrentPopup =
  alloca $ \_pOut -> c_imGui_GetMousePosOnOpeningCurrentPopup _pOut >> peek _pOut

-- C: ImGuiPlatformIO* ImGui::GetPlatformIO()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetPlatformIO"
  imGui_GetPlatformIO :: IO (Ptr ImGuiPlatformIO)
-- C: float ImGui::GetScrollMaxX()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetScrollMaxX"
  imGui_GetScrollMaxX :: IO CFloat
-- C: float ImGui::GetScrollMaxY()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetScrollMaxY"
  imGui_GetScrollMaxY :: IO CFloat
-- C: float ImGui::GetScrollX()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetScrollX"
  imGui_GetScrollX :: IO CFloat
-- C: float ImGui::GetScrollY()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetScrollY"
  imGui_GetScrollY :: IO CFloat
-- C: ImGuiStorage* ImGui::GetStateStorage()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetStateStorage"
  imGui_GetStateStorage :: IO (Ptr ImGuiStorage)
-- C: ImGuiStyle* ImGui::GetStyle()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetStyle"
  imGui_GetStyle :: IO (Ptr ImGuiStyle)
-- C: const char* ImGui::GetStyleColorName(ImGuiCol idx)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetStyleColorName"
  imGui_GetStyleColorName :: ImGuiCol -> IO CString
-- C: const ImVec4* ImGui::GetStyleColorVec4(ImGuiCol idx)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetStyleColorVec4"
  imGui_GetStyleColorVec4 :: ImGuiCol -> IO (Ptr ImVec4)
-- C: float ImGui::GetTextLineHeight()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetTextLineHeight"
  imGui_GetTextLineHeight :: IO CFloat
-- C: float ImGui::GetTextLineHeightWithSpacing()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetTextLineHeightWithSpacing"
  imGui_GetTextLineHeightWithSpacing :: IO CFloat
-- C: double ImGui::GetTime()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetTime"
  imGui_GetTime :: IO CDouble
-- C: float ImGui::GetTreeNodeToLabelSpacing()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetTreeNodeToLabelSpacing"
  imGui_GetTreeNodeToLabelSpacing :: IO CFloat
-- C: const char* ImGui::GetVersion()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetVersion"
  imGui_GetVersion :: IO CString
foreign import capi unsafe "DearImGuiWrappers.h ImGui_GetWindowContentRegionMax_wrap"
  c_imGui_GetWindowContentRegionMax :: (Ptr ImVec2) -> IO ()

imGui_GetWindowContentRegionMax :: IO ImVec2
imGui_GetWindowContentRegionMax =
  alloca $ \_pOut -> c_imGui_GetWindowContentRegionMax _pOut >> peek _pOut

foreign import capi unsafe "DearImGuiWrappers.h ImGui_GetWindowContentRegionMin_wrap"
  c_imGui_GetWindowContentRegionMin :: (Ptr ImVec2) -> IO ()

imGui_GetWindowContentRegionMin :: IO ImVec2
imGui_GetWindowContentRegionMin =
  alloca $ \_pOut -> c_imGui_GetWindowContentRegionMin _pOut >> peek _pOut

-- C: ImGuiID ImGui::GetWindowDockID()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetWindowDockID"
  imGui_GetWindowDockID :: IO ImGuiID
-- C: float ImGui::GetWindowDpiScale()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetWindowDpiScale"
  imGui_GetWindowDpiScale :: IO CFloat
-- C: ImDrawList* ImGui::GetWindowDrawList()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetWindowDrawList"
  imGui_GetWindowDrawList :: IO (Ptr ImDrawList)
-- C: float ImGui::GetWindowHeight()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetWindowHeight"
  imGui_GetWindowHeight :: IO CFloat
foreign import capi unsafe "DearImGuiWrappers.h ImGui_GetWindowPos_wrap"
  c_imGui_GetWindowPos :: (Ptr ImVec2) -> IO ()

imGui_GetWindowPos :: IO ImVec2
imGui_GetWindowPos =
  alloca $ \_pOut -> c_imGui_GetWindowPos _pOut >> peek _pOut

foreign import capi unsafe "DearImGuiWrappers.h ImGui_GetWindowSize_wrap"
  c_imGui_GetWindowSize :: (Ptr ImVec2) -> IO ()

imGui_GetWindowSize :: IO ImVec2
imGui_GetWindowSize =
  alloca $ \_pOut -> c_imGui_GetWindowSize _pOut >> peek _pOut

-- C: ImGuiViewport* ImGui::GetWindowViewport()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetWindowViewport"
  imGui_GetWindowViewport :: IO (Ptr ImGuiViewport)
-- C: float ImGui::GetWindowWidth()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_GetWindowWidth"
  imGui_GetWindowWidth :: IO CFloat
foreign import capi unsafe "DearImGuiWrappers.h ImGui_Image_wrap"
  c_imGui_Image :: (Ptr ImTextureRef) -> (Ptr ImVec2) -> (Ptr ImVec2) -> (Ptr ImVec2) -> IO ()

imGui_Image :: ImTextureRef -> ImVec2 -> ImVec2 -> ImVec2 -> IO ()
imGui_Image tex_ref image_size uv0 uv1 =
  with tex_ref $ \_p0 -> with image_size $ \_p1 -> with uv0 $ \_p2 -> with uv1 $ \_p3 -> c_imGui_Image _p0 _p1 _p2 _p3

foreign import capi unsafe "DearImGuiWrappers.h ImGui_ImageButton_wrap"
  c_imGui_ImageButton :: CString -> (Ptr ImTextureRef) -> (Ptr ImVec2) -> (Ptr ImVec2) -> (Ptr ImVec2) -> (Ptr ImVec4) -> (Ptr ImVec4) -> IO CBool

imGui_ImageButton :: CString -> ImTextureRef -> ImVec2 -> ImVec2 -> ImVec2 -> ImVec4 -> ImVec4 -> IO CBool
imGui_ImageButton str_id tex_ref image_size uv0 uv1 bg_col tint_col =
  with tex_ref $ \_p1 -> with image_size $ \_p2 -> with uv0 $ \_p3 -> with uv1 $ \_p4 -> with bg_col $ \_p5 -> with tint_col $ \_p6 -> c_imGui_ImageButton str_id _p1 _p2 _p3 _p4 _p5 _p6

foreign import capi unsafe "DearImGuiWrappers.h ImGui_ImageImVec4_wrap"
  c_imGui_ImageImVec4 :: (Ptr ImTextureRef) -> (Ptr ImVec2) -> (Ptr ImVec2) -> (Ptr ImVec2) -> (Ptr ImVec4) -> (Ptr ImVec4) -> IO ()

imGui_ImageImVec4 :: ImTextureRef -> ImVec2 -> ImVec2 -> ImVec2 -> ImVec4 -> ImVec4 -> IO ()
imGui_ImageImVec4 tex_ref image_size uv0 uv1 tint_col border_col =
  with tex_ref $ \_p0 -> with image_size $ \_p1 -> with uv0 $ \_p2 -> with uv1 $ \_p3 -> with tint_col $ \_p4 -> with border_col $ \_p5 -> c_imGui_ImageImVec4 _p0 _p1 _p2 _p3 _p4 _p5

foreign import capi unsafe "DearImGuiWrappers.h ImGui_ImageWithBg_wrap"
  c_imGui_ImageWithBg :: (Ptr ImTextureRef) -> (Ptr ImVec2) -> (Ptr ImVec2) -> (Ptr ImVec2) -> (Ptr ImVec4) -> (Ptr ImVec4) -> IO ()

imGui_ImageWithBg :: ImTextureRef -> ImVec2 -> ImVec2 -> ImVec2 -> ImVec4 -> ImVec4 -> IO ()
imGui_ImageWithBg tex_ref image_size uv0 uv1 bg_col tint_col =
  with tex_ref $ \_p0 -> with image_size $ \_p1 -> with uv0 $ \_p2 -> with uv1 $ \_p3 -> with bg_col $ \_p4 -> with tint_col $ \_p5 -> c_imGui_ImageWithBg _p0 _p1 _p2 _p3 _p4 _p5

-- C: void ImGui::Indent(float indent_w)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_Indent"
  imGui_Indent :: CFloat -> IO ()
-- C: bool ImGui::InputDouble(const char* label, double* v, double step, double step_fast, const char* format, ImGuiInputTextFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_InputDouble"
  imGui_InputDouble :: CString -> (Ptr CDouble) -> CDouble -> CDouble -> CString -> ImGuiInputTextFlags -> IO CBool
-- C: bool ImGui::InputFloat(const char* label, float* v, float step, float step_fast, const char* format, ImGuiInputTextFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_InputFloat"
  imGui_InputFloat :: CString -> (Ptr CFloat) -> CFloat -> CFloat -> CString -> ImGuiInputTextFlags -> IO CBool
-- C: bool ImGui::InputFloat2(const char* label, float[2] v, const char* format, ImGuiInputTextFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_InputFloat2"
  imGui_InputFloat2 :: CString -> (Ptr CFloat) -> CString -> ImGuiInputTextFlags -> IO CBool
-- C: bool ImGui::InputFloat3(const char* label, float[3] v, const char* format, ImGuiInputTextFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_InputFloat3"
  imGui_InputFloat3 :: CString -> (Ptr CFloat) -> CString -> ImGuiInputTextFlags -> IO CBool
-- C: bool ImGui::InputFloat4(const char* label, float[4] v, const char* format, ImGuiInputTextFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_InputFloat4"
  imGui_InputFloat4 :: CString -> (Ptr CFloat) -> CString -> ImGuiInputTextFlags -> IO CBool
-- C: bool ImGui::InputInt(const char* label, int* v, int step, int step_fast, ImGuiInputTextFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_InputInt"
  imGui_InputInt :: CString -> (Ptr CInt) -> CInt -> CInt -> ImGuiInputTextFlags -> IO CBool
-- C: bool ImGui::InputInt2(const char* label, int[2] v, ImGuiInputTextFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_InputInt2"
  imGui_InputInt2 :: CString -> (Ptr CInt) -> ImGuiInputTextFlags -> IO CBool
-- C: bool ImGui::InputInt3(const char* label, int[3] v, ImGuiInputTextFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_InputInt3"
  imGui_InputInt3 :: CString -> (Ptr CInt) -> ImGuiInputTextFlags -> IO CBool
-- C: bool ImGui::InputInt4(const char* label, int[4] v, ImGuiInputTextFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_InputInt4"
  imGui_InputInt4 :: CString -> (Ptr CInt) -> ImGuiInputTextFlags -> IO CBool
-- C: bool ImGui::InputScalar(const char* label, ImGuiDataType data_type, void* p_data, const void* p_step, const void* p_step_fast, const char* format, ImGuiInputTextFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_InputScalar"
  imGui_InputScalar :: CString -> ImGuiDataType -> (Ptr ()) -> (Ptr ()) -> (Ptr ()) -> CString -> ImGuiInputTextFlags -> IO CBool
-- C: bool ImGui::InputScalarN(const char* label, ImGuiDataType data_type, void* p_data, int components, const void* p_step, const void* p_step_fast, const char* format, ImGuiInputTextFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_InputScalarN"
  imGui_InputScalarN :: CString -> ImGuiDataType -> (Ptr ()) -> CInt -> (Ptr ()) -> (Ptr ()) -> CString -> ImGuiInputTextFlags -> IO CBool
-- C: bool ImGui::InputText(const char* label, char* buf, size_t buf_size, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback, void* user_data)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_InputText"
  imGui_InputText :: CString -> (Ptr CChar) -> CSize -> ImGuiInputTextFlags -> ImGuiInputTextCallback -> (Ptr ()) -> IO CBool
foreign import capi unsafe "DearImGuiWrappers.h ImGui_InputTextMultiline_wrap"
  c_imGui_InputTextMultiline :: CString -> (Ptr CChar) -> CSize -> (Ptr ImVec2) -> ImGuiInputTextFlags -> ImGuiInputTextCallback -> (Ptr ()) -> IO CBool

imGui_InputTextMultiline :: CString -> (Ptr CChar) -> CSize -> ImVec2 -> ImGuiInputTextFlags -> ImGuiInputTextCallback -> (Ptr ()) -> IO CBool
imGui_InputTextMultiline label buf buf_size size flags callback user_data =
  with size $ \_p3 -> c_imGui_InputTextMultiline label buf buf_size _p3 flags callback user_data

-- C: bool ImGui::InputTextWithHint(const char* label, const char* hint, char* buf, size_t buf_size, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback, void* user_data)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_InputTextWithHint"
  imGui_InputTextWithHint :: CString -> CString -> (Ptr CChar) -> CSize -> ImGuiInputTextFlags -> ImGuiInputTextCallback -> (Ptr ()) -> IO CBool
foreign import capi unsafe "DearImGuiWrappers.h ImGui_InvisibleButton_wrap"
  c_imGui_InvisibleButton :: CString -> (Ptr ImVec2) -> ImGuiButtonFlags -> IO CBool

imGui_InvisibleButton :: CString -> ImVec2 -> ImGuiButtonFlags -> IO CBool
imGui_InvisibleButton str_id size flags =
  with size $ \_p1 -> c_imGui_InvisibleButton str_id _p1 flags

-- C: bool ImGui::IsAnyItemActive()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsAnyItemActive"
  imGui_IsAnyItemActive :: IO CBool
-- C: bool ImGui::IsAnyItemFocused()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsAnyItemFocused"
  imGui_IsAnyItemFocused :: IO CBool
-- C: bool ImGui::IsAnyItemHovered()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsAnyItemHovered"
  imGui_IsAnyItemHovered :: IO CBool
-- C: bool ImGui::IsAnyMouseDown()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsAnyMouseDown"
  imGui_IsAnyMouseDown :: IO CBool
-- C: bool ImGui::IsItemActivated()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsItemActivated"
  imGui_IsItemActivated :: IO CBool
-- C: bool ImGui::IsItemActive()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsItemActive"
  imGui_IsItemActive :: IO CBool
-- C: bool ImGui::IsItemClicked(ImGuiMouseButton mouse_button)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsItemClicked"
  imGui_IsItemClicked :: ImGuiMouseButton -> IO CBool
-- C: bool ImGui::IsItemDeactivated()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsItemDeactivated"
  imGui_IsItemDeactivated :: IO CBool
-- C: bool ImGui::IsItemDeactivatedAfterEdit()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsItemDeactivatedAfterEdit"
  imGui_IsItemDeactivatedAfterEdit :: IO CBool
-- C: bool ImGui::IsItemEdited()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsItemEdited"
  imGui_IsItemEdited :: IO CBool
-- C: bool ImGui::IsItemFocused()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsItemFocused"
  imGui_IsItemFocused :: IO CBool
-- C: bool ImGui::IsItemHovered(ImGuiHoveredFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsItemHovered"
  imGui_IsItemHovered :: ImGuiHoveredFlags -> IO CBool
-- C: bool ImGui::IsItemToggledOpen()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsItemToggledOpen"
  imGui_IsItemToggledOpen :: IO CBool
-- C: bool ImGui::IsItemToggledSelection()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsItemToggledSelection"
  imGui_IsItemToggledSelection :: IO CBool
-- C: bool ImGui::IsItemVisible()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsItemVisible"
  imGui_IsItemVisible :: IO CBool
-- C: bool ImGui::IsKeyChordPressed(ImGuiKeyChord key_chord)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsKeyChordPressed"
  imGui_IsKeyChordPressed :: ImGuiKeyChord -> IO CBool
-- C: bool ImGui::IsKeyDown(ImGuiKey key)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsKeyDown"
  imGui_IsKeyDown :: ImGuiKey -> IO CBool
-- C: bool ImGui::IsKeyPressed(ImGuiKey key, bool repeat)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsKeyPressed"
  imGui_IsKeyPressed :: ImGuiKey -> CBool -> IO CBool
-- C: bool ImGui::IsKeyReleased(ImGuiKey key)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsKeyReleased"
  imGui_IsKeyReleased :: ImGuiKey -> IO CBool
-- C: bool ImGui::IsMouseClicked(ImGuiMouseButton button, bool repeat)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsMouseClicked"
  imGui_IsMouseClicked :: ImGuiMouseButton -> CBool -> IO CBool
-- C: bool ImGui::IsMouseDoubleClicked(ImGuiMouseButton button)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsMouseDoubleClicked"
  imGui_IsMouseDoubleClicked :: ImGuiMouseButton -> IO CBool
-- C: bool ImGui::IsMouseDown(ImGuiMouseButton button)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsMouseDown"
  imGui_IsMouseDown :: ImGuiMouseButton -> IO CBool
-- C: bool ImGui::IsMouseDragging(ImGuiMouseButton button, float lock_threshold)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsMouseDragging"
  imGui_IsMouseDragging :: ImGuiMouseButton -> CFloat -> IO CBool
foreign import capi unsafe "DearImGuiWrappers.h ImGui_IsMouseHoveringRect_wrap"
  c_imGui_IsMouseHoveringRect :: (Ptr ImVec2) -> (Ptr ImVec2) -> CBool -> IO CBool

imGui_IsMouseHoveringRect :: ImVec2 -> ImVec2 -> CBool -> IO CBool
imGui_IsMouseHoveringRect r_min r_max clip =
  with r_min $ \_p0 -> with r_max $ \_p1 -> c_imGui_IsMouseHoveringRect _p0 _p1 clip

-- C: bool ImGui::IsMousePosValid(const ImVec2* mouse_pos)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsMousePosValid"
  imGui_IsMousePosValid :: (Ptr ImVec2) -> IO CBool
-- C: bool ImGui::IsMouseReleased(ImGuiMouseButton button)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsMouseReleased"
  imGui_IsMouseReleased :: ImGuiMouseButton -> IO CBool
-- C: bool ImGui::IsMouseReleasedWithDelay(ImGuiMouseButton button, float delay)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsMouseReleasedWithDelay"
  imGui_IsMouseReleasedWithDelay :: ImGuiMouseButton -> CFloat -> IO CBool
-- C: bool ImGui::IsPopupOpen(const char* str_id, ImGuiPopupFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsPopupOpen"
  imGui_IsPopupOpen :: CString -> ImGuiPopupFlags -> IO CBool
foreign import capi unsafe "DearImGuiWrappers.h ImGui_IsRectVisible_wrap"
  c_imGui_IsRectVisible :: (Ptr ImVec2) -> (Ptr ImVec2) -> IO CBool

imGui_IsRectVisible :: ImVec2 -> ImVec2 -> IO CBool
imGui_IsRectVisible rect_min rect_max =
  with rect_min $ \_p0 -> with rect_max $ \_p1 -> c_imGui_IsRectVisible _p0 _p1

foreign import capi unsafe "DearImGuiWrappers.h ImGui_IsRectVisibleBySize_wrap"
  c_imGui_IsRectVisibleBySize :: (Ptr ImVec2) -> IO CBool

imGui_IsRectVisibleBySize :: ImVec2 -> IO CBool
imGui_IsRectVisibleBySize size =
  with size $ \_p0 -> c_imGui_IsRectVisibleBySize _p0

-- C: bool ImGui::IsWindowAppearing()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsWindowAppearing"
  imGui_IsWindowAppearing :: IO CBool
-- C: bool ImGui::IsWindowCollapsed()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsWindowCollapsed"
  imGui_IsWindowCollapsed :: IO CBool
-- C: bool ImGui::IsWindowDocked()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsWindowDocked"
  imGui_IsWindowDocked :: IO CBool
-- C: bool ImGui::IsWindowFocused(ImGuiFocusedFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsWindowFocused"
  imGui_IsWindowFocused :: ImGuiFocusedFlags -> IO CBool
-- C: bool ImGui::IsWindowHovered(ImGuiHoveredFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_IsWindowHovered"
  imGui_IsWindowHovered :: ImGuiHoveredFlags -> IO CBool
-- C: bool ImGui::ListBox(const char* label, int* current_item, const char*const[] items, int items_count, int height_in_items)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_ListBox"
  imGui_ListBox :: CString -> (Ptr CInt) -> (Ptr CString) -> CInt -> CInt -> IO CBool
-- C: bool ImGui::ListBox(const char* label, int* current_item, const char* (*getter)(void* user_data, int idx) getter, void* user_data, int items_count, int height_in_items)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_ListBoxCallback"
  imGui_ListBoxCallback :: CString -> (Ptr CInt) -> (FunPtr ((Ptr ()) -> CInt -> IO CString)) -> (Ptr ()) -> CInt -> CInt -> IO CBool
-- C: void ImGui::LoadIniSettingsFromDisk(const char* ini_filename)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_LoadIniSettingsFromDisk"
  imGui_LoadIniSettingsFromDisk :: CString -> IO ()
-- C: void ImGui::LoadIniSettingsFromMemory(const char* ini_data, size_t ini_size)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_LoadIniSettingsFromMemory"
  imGui_LoadIniSettingsFromMemory :: CString -> CSize -> IO ()
-- C: void ImGui::LogButtons()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_LogButtons"
  imGui_LogButtons :: IO ()
-- C: void ImGui::LogFinish()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_LogFinish"
  imGui_LogFinish :: IO ()
-- C: void ImGui::LogToClipboard(int auto_open_depth)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_LogToClipboard"
  imGui_LogToClipboard :: CInt -> IO ()
-- C: void ImGui::LogToFile(int auto_open_depth, const char* filename)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_LogToFile"
  imGui_LogToFile :: CInt -> CString -> IO ()
-- C: void ImGui::LogToTTY(int auto_open_depth)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_LogToTTY"
  imGui_LogToTTY :: CInt -> IO ()
-- C: void* ImGui::MemAlloc(size_t size)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_MemAlloc"
  imGui_MemAlloc :: CSize -> IO (Ptr ())
-- C: void ImGui::MemFree(void* ptr)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_MemFree"
  imGui_MemFree :: (Ptr ()) -> IO ()
-- C: bool ImGui::MenuItem(const char* label, const char* shortcut, bool selected, bool enabled)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_MenuItem"
  imGui_MenuItem :: CString -> CString -> CBool -> CBool -> IO CBool
-- C: bool ImGui::MenuItem(const char* label, const char* shortcut, bool* p_selected, bool enabled)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_MenuItemBoolPtr"
  imGui_MenuItemBoolPtr :: CString -> CString -> (Ptr CBool) -> CBool -> IO CBool
-- C: void ImGui::NewFrame()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_NewFrame"
  imGui_NewFrame :: IO ()
-- C: void ImGui::NewLine()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_NewLine"
  imGui_NewLine :: IO ()
-- C: void ImGui::NextColumn()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_NextColumn"
  imGui_NextColumn :: IO ()
-- C: void ImGui::OpenPopup(const char* str_id, ImGuiPopupFlags popup_flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_OpenPopup"
  imGui_OpenPopup :: CString -> ImGuiPopupFlags -> IO ()
-- C: void ImGui::OpenPopup(ImGuiID id, ImGuiPopupFlags popup_flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_OpenPopupID"
  imGui_OpenPopupID :: ImGuiID -> ImGuiPopupFlags -> IO ()
-- C: void ImGui::OpenPopupOnItemClick(const char* str_id, ImGuiPopupFlags popup_flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_OpenPopupOnItemClick"
  imGui_OpenPopupOnItemClick :: CString -> ImGuiPopupFlags -> IO ()
foreign import capi unsafe "DearImGuiWrappers.h ImGui_PlotHistogram_wrap"
  c_imGui_PlotHistogram :: CString -> (Ptr CFloat) -> CInt -> CInt -> CString -> CFloat -> CFloat -> (Ptr ImVec2) -> CInt -> IO ()

imGui_PlotHistogram :: CString -> (Ptr CFloat) -> CInt -> CInt -> CString -> CFloat -> CFloat -> ImVec2 -> CInt -> IO ()
imGui_PlotHistogram label values values_count values_offset overlay_text scale_min scale_max graph_size stride =
  with graph_size $ \_p7 -> c_imGui_PlotHistogram label values values_count values_offset overlay_text scale_min scale_max _p7 stride

foreign import capi unsafe "DearImGuiWrappers.h ImGui_PlotHistogramCallback_wrap"
  c_imGui_PlotHistogramCallback :: CString -> (FunPtr ((Ptr ()) -> CInt -> IO CFloat)) -> (Ptr ()) -> CInt -> CInt -> CString -> CFloat -> CFloat -> (Ptr ImVec2) -> IO ()

imGui_PlotHistogramCallback :: CString -> (FunPtr ((Ptr ()) -> CInt -> IO CFloat)) -> (Ptr ()) -> CInt -> CInt -> CString -> CFloat -> CFloat -> ImVec2 -> IO ()
imGui_PlotHistogramCallback label values_getter data_ values_count values_offset overlay_text scale_min scale_max graph_size =
  with graph_size $ \_p8 -> c_imGui_PlotHistogramCallback label values_getter data_ values_count values_offset overlay_text scale_min scale_max _p8

foreign import capi unsafe "DearImGuiWrappers.h ImGui_PlotLines_wrap"
  c_imGui_PlotLines :: CString -> (Ptr CFloat) -> CInt -> CInt -> CString -> CFloat -> CFloat -> (Ptr ImVec2) -> CInt -> IO ()

imGui_PlotLines :: CString -> (Ptr CFloat) -> CInt -> CInt -> CString -> CFloat -> CFloat -> ImVec2 -> CInt -> IO ()
imGui_PlotLines label values values_count values_offset overlay_text scale_min scale_max graph_size stride =
  with graph_size $ \_p7 -> c_imGui_PlotLines label values values_count values_offset overlay_text scale_min scale_max _p7 stride

foreign import capi unsafe "DearImGuiWrappers.h ImGui_PlotLinesCallback_wrap"
  c_imGui_PlotLinesCallback :: CString -> (FunPtr ((Ptr ()) -> CInt -> IO CFloat)) -> (Ptr ()) -> CInt -> CInt -> CString -> CFloat -> CFloat -> (Ptr ImVec2) -> IO ()

imGui_PlotLinesCallback :: CString -> (FunPtr ((Ptr ()) -> CInt -> IO CFloat)) -> (Ptr ()) -> CInt -> CInt -> CString -> CFloat -> CFloat -> ImVec2 -> IO ()
imGui_PlotLinesCallback label values_getter data_ values_count values_offset overlay_text scale_min scale_max graph_size =
  with graph_size $ \_p8 -> c_imGui_PlotLinesCallback label values_getter data_ values_count values_offset overlay_text scale_min scale_max _p8

-- C: void ImGui::PopButtonRepeat()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PopButtonRepeat"
  imGui_PopButtonRepeat :: IO ()
-- C: void ImGui::PopClipRect()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PopClipRect"
  imGui_PopClipRect :: IO ()
-- C: void ImGui::PopFont()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PopFont"
  imGui_PopFont :: IO ()
-- C: void ImGui::PopID()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PopID"
  imGui_PopID :: IO ()
-- C: void ImGui::PopItemFlag()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PopItemFlag"
  imGui_PopItemFlag :: IO ()
-- C: void ImGui::PopItemWidth()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PopItemWidth"
  imGui_PopItemWidth :: IO ()
-- C: void ImGui::PopStyleColor(int count)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PopStyleColor"
  imGui_PopStyleColor :: CInt -> IO ()
-- C: void ImGui::PopStyleVar(int count)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PopStyleVar"
  imGui_PopStyleVar :: CInt -> IO ()
-- C: void ImGui::PopTabStop()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PopTabStop"
  imGui_PopTabStop :: IO ()
-- C: void ImGui::PopTextWrapPos()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PopTextWrapPos"
  imGui_PopTextWrapPos :: IO ()
foreign import capi unsafe "DearImGuiWrappers.h ImGui_ProgressBar_wrap"
  c_imGui_ProgressBar :: CFloat -> (Ptr ImVec2) -> CString -> IO ()

imGui_ProgressBar :: CFloat -> ImVec2 -> CString -> IO ()
imGui_ProgressBar fraction size_arg overlay =
  with size_arg $ \_p1 -> c_imGui_ProgressBar fraction _p1 overlay

-- C: void ImGui::PushButtonRepeat(bool repeat)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PushButtonRepeat"
  imGui_PushButtonRepeat :: CBool -> IO ()
foreign import capi unsafe "DearImGuiWrappers.h ImGui_PushClipRect_wrap"
  c_imGui_PushClipRect :: (Ptr ImVec2) -> (Ptr ImVec2) -> CBool -> IO ()

imGui_PushClipRect :: ImVec2 -> ImVec2 -> CBool -> IO ()
imGui_PushClipRect clip_rect_min clip_rect_max intersect_with_current_clip_rect =
  with clip_rect_min $ \_p0 -> with clip_rect_max $ \_p1 -> c_imGui_PushClipRect _p0 _p1 intersect_with_current_clip_rect

-- C: void ImGui::PushFont(ImFont* font)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PushFont"
  imGui_PushFont :: (Ptr ImFont) -> IO ()
-- C: void ImGui::PushFont(ImFont* font, float font_size_base_unscaled)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PushFontFloat"
  imGui_PushFontFloat :: (Ptr ImFont) -> CFloat -> IO ()
-- C: void ImGui::PushID(const char* str_id)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PushID"
  imGui_PushID :: CString -> IO ()
-- C: void ImGui::PushID(int int_id)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PushIDInt"
  imGui_PushIDInt :: CInt -> IO ()
-- C: void ImGui::PushID(const void* ptr_id)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PushIDPtr"
  imGui_PushIDPtr :: (Ptr ()) -> IO ()
-- C: void ImGui::PushID(const char* str_id_begin, const char* str_id_end)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PushIDStr"
  imGui_PushIDStr :: CString -> CString -> IO ()
-- C: void ImGui::PushItemFlag(ImGuiItemFlags option, bool enabled)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PushItemFlag"
  imGui_PushItemFlag :: ImGuiItemFlags -> CBool -> IO ()
-- C: void ImGui::PushItemWidth(float item_width)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PushItemWidth"
  imGui_PushItemWidth :: CFloat -> IO ()
-- C: void ImGui::PushStyleColor(ImGuiCol idx, ImU32 col)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PushStyleColor"
  imGui_PushStyleColor :: ImGuiCol -> ImU32 -> IO ()
foreign import capi unsafe "DearImGuiWrappers.h ImGui_PushStyleColorImVec4_wrap"
  c_imGui_PushStyleColorImVec4 :: ImGuiCol -> (Ptr ImVec4) -> IO ()

imGui_PushStyleColorImVec4 :: ImGuiCol -> ImVec4 -> IO ()
imGui_PushStyleColorImVec4 idx col =
  with col $ \_p1 -> c_imGui_PushStyleColorImVec4 idx _p1

-- C: void ImGui::PushStyleVar(ImGuiStyleVar idx, float val)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PushStyleVar"
  imGui_PushStyleVar :: ImGuiStyleVar -> CFloat -> IO ()
foreign import capi unsafe "DearImGuiWrappers.h ImGui_PushStyleVarImVec2_wrap"
  c_imGui_PushStyleVarImVec2 :: ImGuiStyleVar -> (Ptr ImVec2) -> IO ()

imGui_PushStyleVarImVec2 :: ImGuiStyleVar -> ImVec2 -> IO ()
imGui_PushStyleVarImVec2 idx val =
  with val $ \_p1 -> c_imGui_PushStyleVarImVec2 idx _p1

-- C: void ImGui::PushStyleVarX(ImGuiStyleVar idx, float val_x)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PushStyleVarX"
  imGui_PushStyleVarX :: ImGuiStyleVar -> CFloat -> IO ()
-- C: void ImGui::PushStyleVarY(ImGuiStyleVar idx, float val_y)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PushStyleVarY"
  imGui_PushStyleVarY :: ImGuiStyleVar -> CFloat -> IO ()
-- C: void ImGui::PushTabStop(bool tab_stop)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PushTabStop"
  imGui_PushTabStop :: CBool -> IO ()
-- C: void ImGui::PushTextWrapPos(float wrap_local_pos_x)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_PushTextWrapPos"
  imGui_PushTextWrapPos :: CFloat -> IO ()
-- C: bool ImGui::RadioButton(const char* label, bool active)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_RadioButton"
  imGui_RadioButton :: CString -> CBool -> IO CBool
-- C: bool ImGui::RadioButton(const char* label, int* v, int v_button)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_RadioButtonIntPtr"
  imGui_RadioButtonIntPtr :: CString -> (Ptr CInt) -> CInt -> IO CBool
-- C: void ImGui::Render()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_Render"
  imGui_Render :: IO ()
-- C: void ImGui::RenderPlatformWindowsDefault(void* platform_render_arg, void* renderer_render_arg)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_RenderPlatformWindowsDefault"
  imGui_RenderPlatformWindowsDefault :: (Ptr ()) -> (Ptr ()) -> IO ()
-- C: void ImGui::ResetMouseDragDelta(ImGuiMouseButton button)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_ResetMouseDragDelta"
  imGui_ResetMouseDragDelta :: ImGuiMouseButton -> IO ()
-- C: void ImGui::SameLine(float offset_from_start_x, float spacing)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SameLine"
  imGui_SameLine :: CFloat -> CFloat -> IO ()
-- C: void ImGui::SaveIniSettingsToDisk(const char* ini_filename)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SaveIniSettingsToDisk"
  imGui_SaveIniSettingsToDisk :: CString -> IO ()
-- C: const char* ImGui::SaveIniSettingsToMemory(size_t* out_ini_size)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SaveIniSettingsToMemory"
  imGui_SaveIniSettingsToMemory :: (Ptr CSize) -> IO CString
foreign import capi unsafe "DearImGuiWrappers.h ImGui_Selectable_wrap"
  c_imGui_Selectable :: CString -> CBool -> ImGuiSelectableFlags -> (Ptr ImVec2) -> IO CBool

imGui_Selectable :: CString -> CBool -> ImGuiSelectableFlags -> ImVec2 -> IO CBool
imGui_Selectable label selected flags size =
  with size $ \_p3 -> c_imGui_Selectable label selected flags _p3

foreign import capi unsafe "DearImGuiWrappers.h ImGui_SelectableBoolPtr_wrap"
  c_imGui_SelectableBoolPtr :: CString -> (Ptr CBool) -> ImGuiSelectableFlags -> (Ptr ImVec2) -> IO CBool

imGui_SelectableBoolPtr :: CString -> (Ptr CBool) -> ImGuiSelectableFlags -> ImVec2 -> IO CBool
imGui_SelectableBoolPtr label p_selected flags size =
  with size $ \_p3 -> c_imGui_SelectableBoolPtr label p_selected flags _p3

-- C: void ImGui::Separator()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_Separator"
  imGui_Separator :: IO ()
-- C: void ImGui::SeparatorText(const char* label)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SeparatorText"
  imGui_SeparatorText :: CString -> IO ()
-- C: void ImGui::SetAllocatorFunctions(ImGuiMemAllocFunc alloc_func, ImGuiMemFreeFunc free_func, void* user_data)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetAllocatorFunctions"
  imGui_SetAllocatorFunctions :: ImGuiMemAllocFunc -> ImGuiMemFreeFunc -> (Ptr ()) -> IO ()
-- C: void ImGui::SetClipboardText(const char* text)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetClipboardText"
  imGui_SetClipboardText :: CString -> IO ()
-- C: void ImGui::SetColorEditOptions(ImGuiColorEditFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetColorEditOptions"
  imGui_SetColorEditOptions :: ImGuiColorEditFlags -> IO ()
-- C: void ImGui::SetColumnOffset(int column_index, float offset_x)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetColumnOffset"
  imGui_SetColumnOffset :: CInt -> CFloat -> IO ()
-- C: void ImGui::SetColumnWidth(int column_index, float width)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetColumnWidth"
  imGui_SetColumnWidth :: CInt -> CFloat -> IO ()
-- C: void ImGui::SetCurrentContext(ImGuiContext* ctx)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetCurrentContext"
  imGui_SetCurrentContext :: (Ptr ImGuiContext) -> IO ()
foreign import capi unsafe "DearImGuiWrappers.h ImGui_SetCursorPos_wrap"
  c_imGui_SetCursorPos :: (Ptr ImVec2) -> IO ()

imGui_SetCursorPos :: ImVec2 -> IO ()
imGui_SetCursorPos local_pos =
  with local_pos $ \_p0 -> c_imGui_SetCursorPos _p0

-- C: void ImGui::SetCursorPosX(float local_x)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetCursorPosX"
  imGui_SetCursorPosX :: CFloat -> IO ()
-- C: void ImGui::SetCursorPosY(float local_y)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetCursorPosY"
  imGui_SetCursorPosY :: CFloat -> IO ()
foreign import capi unsafe "DearImGuiWrappers.h ImGui_SetCursorScreenPos_wrap"
  c_imGui_SetCursorScreenPos :: (Ptr ImVec2) -> IO ()

imGui_SetCursorScreenPos :: ImVec2 -> IO ()
imGui_SetCursorScreenPos pos =
  with pos $ \_p0 -> c_imGui_SetCursorScreenPos _p0

-- C: bool ImGui::SetDragDropPayload(const char* type, const void* data, size_t sz, ImGuiCond cond)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetDragDropPayload"
  imGui_SetDragDropPayload :: CString -> (Ptr ()) -> CSize -> ImGuiCond -> IO CBool
-- C: void ImGui::SetItemDefaultFocus()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetItemDefaultFocus"
  imGui_SetItemDefaultFocus :: IO ()
-- C: void ImGui::SetItemKeyOwner(ImGuiKey key)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetItemKeyOwner"
  imGui_SetItemKeyOwner :: ImGuiKey -> IO ()
-- C: void ImGui::SetKeyboardFocusHere(int offset)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetKeyboardFocusHere"
  imGui_SetKeyboardFocusHere :: CInt -> IO ()
-- C: void ImGui::SetMouseCursor(ImGuiMouseCursor cursor_type)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetMouseCursor"
  imGui_SetMouseCursor :: ImGuiMouseCursor -> IO ()
-- C: void ImGui::SetNavCursorVisible(bool visible)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetNavCursorVisible"
  imGui_SetNavCursorVisible :: CBool -> IO ()
-- C: void ImGui::SetNextFrameWantCaptureKeyboard(bool want_capture_keyboard)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetNextFrameWantCaptureKeyboard"
  imGui_SetNextFrameWantCaptureKeyboard :: CBool -> IO ()
-- C: void ImGui::SetNextFrameWantCaptureMouse(bool want_capture_mouse)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetNextFrameWantCaptureMouse"
  imGui_SetNextFrameWantCaptureMouse :: CBool -> IO ()
-- C: void ImGui::SetNextItemAllowOverlap()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetNextItemAllowOverlap"
  imGui_SetNextItemAllowOverlap :: IO ()
-- C: void ImGui::SetNextItemOpen(bool is_open, ImGuiCond cond)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetNextItemOpen"
  imGui_SetNextItemOpen :: CBool -> ImGuiCond -> IO ()
-- C: void ImGui::SetNextItemSelectionUserData(ImGuiSelectionUserData selection_user_data)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetNextItemSelectionUserData"
  imGui_SetNextItemSelectionUserData :: ImGuiSelectionUserData -> IO ()
-- C: void ImGui::SetNextItemShortcut(ImGuiKeyChord key_chord, ImGuiInputFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetNextItemShortcut"
  imGui_SetNextItemShortcut :: ImGuiKeyChord -> ImGuiInputFlags -> IO ()
-- C: void ImGui::SetNextItemStorageID(ImGuiID storage_id)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetNextItemStorageID"
  imGui_SetNextItemStorageID :: ImGuiID -> IO ()
-- C: void ImGui::SetNextItemWidth(float item_width)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetNextItemWidth"
  imGui_SetNextItemWidth :: CFloat -> IO ()
-- C: void ImGui::SetNextWindowBgAlpha(float alpha)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetNextWindowBgAlpha"
  imGui_SetNextWindowBgAlpha :: CFloat -> IO ()
-- C: void ImGui::SetNextWindowClass(const ImGuiWindowClass* window_class)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetNextWindowClass"
  imGui_SetNextWindowClass :: (Ptr ImGuiWindowClass) -> IO ()
-- C: void ImGui::SetNextWindowCollapsed(bool collapsed, ImGuiCond cond)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetNextWindowCollapsed"
  imGui_SetNextWindowCollapsed :: CBool -> ImGuiCond -> IO ()
foreign import capi unsafe "DearImGuiWrappers.h ImGui_SetNextWindowContentSize_wrap"
  c_imGui_SetNextWindowContentSize :: (Ptr ImVec2) -> IO ()

imGui_SetNextWindowContentSize :: ImVec2 -> IO ()
imGui_SetNextWindowContentSize size =
  with size $ \_p0 -> c_imGui_SetNextWindowContentSize _p0

-- C: void ImGui::SetNextWindowDockID(ImGuiID dock_id, ImGuiCond cond)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetNextWindowDockID"
  imGui_SetNextWindowDockID :: ImGuiID -> ImGuiCond -> IO ()
-- C: void ImGui::SetNextWindowFocus()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetNextWindowFocus"
  imGui_SetNextWindowFocus :: IO ()
foreign import capi unsafe "DearImGuiWrappers.h ImGui_SetNextWindowPos_wrap"
  c_imGui_SetNextWindowPos :: (Ptr ImVec2) -> ImGuiCond -> (Ptr ImVec2) -> IO ()

imGui_SetNextWindowPos :: ImVec2 -> ImGuiCond -> ImVec2 -> IO ()
imGui_SetNextWindowPos pos cond pivot =
  with pos $ \_p0 -> with pivot $ \_p2 -> c_imGui_SetNextWindowPos _p0 cond _p2

foreign import capi unsafe "DearImGuiWrappers.h ImGui_SetNextWindowScroll_wrap"
  c_imGui_SetNextWindowScroll :: (Ptr ImVec2) -> IO ()

imGui_SetNextWindowScroll :: ImVec2 -> IO ()
imGui_SetNextWindowScroll scroll =
  with scroll $ \_p0 -> c_imGui_SetNextWindowScroll _p0

foreign import capi unsafe "DearImGuiWrappers.h ImGui_SetNextWindowSize_wrap"
  c_imGui_SetNextWindowSize :: (Ptr ImVec2) -> ImGuiCond -> IO ()

imGui_SetNextWindowSize :: ImVec2 -> ImGuiCond -> IO ()
imGui_SetNextWindowSize size cond =
  with size $ \_p0 -> c_imGui_SetNextWindowSize _p0 cond

foreign import capi unsafe "DearImGuiWrappers.h ImGui_SetNextWindowSizeConstraints_wrap"
  c_imGui_SetNextWindowSizeConstraints :: (Ptr ImVec2) -> (Ptr ImVec2) -> ImGuiSizeCallback -> (Ptr ()) -> IO ()

imGui_SetNextWindowSizeConstraints :: ImVec2 -> ImVec2 -> ImGuiSizeCallback -> (Ptr ()) -> IO ()
imGui_SetNextWindowSizeConstraints size_min size_max custom_callback custom_callback_data =
  with size_min $ \_p0 -> with size_max $ \_p1 -> c_imGui_SetNextWindowSizeConstraints _p0 _p1 custom_callback custom_callback_data

-- C: void ImGui::SetNextWindowViewport(ImGuiID viewport_id)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetNextWindowViewport"
  imGui_SetNextWindowViewport :: ImGuiID -> IO ()
-- C: void ImGui::SetScrollFromPosX(float local_x, float center_x_ratio)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetScrollFromPosX"
  imGui_SetScrollFromPosX :: CFloat -> CFloat -> IO ()
-- C: void ImGui::SetScrollFromPosY(float local_y, float center_y_ratio)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetScrollFromPosY"
  imGui_SetScrollFromPosY :: CFloat -> CFloat -> IO ()
-- C: void ImGui::SetScrollHereX(float center_x_ratio)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetScrollHereX"
  imGui_SetScrollHereX :: CFloat -> IO ()
-- C: void ImGui::SetScrollHereY(float center_y_ratio)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetScrollHereY"
  imGui_SetScrollHereY :: CFloat -> IO ()
-- C: void ImGui::SetScrollX(float scroll_x)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetScrollX"
  imGui_SetScrollX :: CFloat -> IO ()
-- C: void ImGui::SetScrollY(float scroll_y)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetScrollY"
  imGui_SetScrollY :: CFloat -> IO ()
-- C: void ImGui::SetStateStorage(ImGuiStorage* storage)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetStateStorage"
  imGui_SetStateStorage :: (Ptr ImGuiStorage) -> IO ()
-- C: void ImGui::SetTabItemClosed(const char* tab_or_docked_window_label)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetTabItemClosed"
  imGui_SetTabItemClosed :: CString -> IO ()
-- C: void ImGui::SetWindowCollapsed(bool collapsed, ImGuiCond cond)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetWindowCollapsed"
  imGui_SetWindowCollapsed :: CBool -> ImGuiCond -> IO ()
-- C: void ImGui::SetWindowCollapsed(const char* name, bool collapsed, ImGuiCond cond)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetWindowCollapsedStr"
  imGui_SetWindowCollapsedStr :: CString -> CBool -> ImGuiCond -> IO ()
-- C: void ImGui::SetWindowFocus()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetWindowFocus"
  imGui_SetWindowFocus :: IO ()
-- C: void ImGui::SetWindowFocus(const char* name)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetWindowFocusStr"
  imGui_SetWindowFocusStr :: CString -> IO ()
-- C: void ImGui::SetWindowFontScale(float scale)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SetWindowFontScale"
  imGui_SetWindowFontScale :: CFloat -> IO ()
foreign import capi unsafe "DearImGuiWrappers.h ImGui_SetWindowPos_wrap"
  c_imGui_SetWindowPos :: (Ptr ImVec2) -> ImGuiCond -> IO ()

imGui_SetWindowPos :: ImVec2 -> ImGuiCond -> IO ()
imGui_SetWindowPos pos cond =
  with pos $ \_p0 -> c_imGui_SetWindowPos _p0 cond

foreign import capi unsafe "DearImGuiWrappers.h ImGui_SetWindowPosStr_wrap"
  c_imGui_SetWindowPosStr :: CString -> (Ptr ImVec2) -> ImGuiCond -> IO ()

imGui_SetWindowPosStr :: CString -> ImVec2 -> ImGuiCond -> IO ()
imGui_SetWindowPosStr name pos cond =
  with pos $ \_p1 -> c_imGui_SetWindowPosStr name _p1 cond

foreign import capi unsafe "DearImGuiWrappers.h ImGui_SetWindowSize_wrap"
  c_imGui_SetWindowSize :: (Ptr ImVec2) -> ImGuiCond -> IO ()

imGui_SetWindowSize :: ImVec2 -> ImGuiCond -> IO ()
imGui_SetWindowSize size cond =
  with size $ \_p0 -> c_imGui_SetWindowSize _p0 cond

foreign import capi unsafe "DearImGuiWrappers.h ImGui_SetWindowSizeStr_wrap"
  c_imGui_SetWindowSizeStr :: CString -> (Ptr ImVec2) -> ImGuiCond -> IO ()

imGui_SetWindowSizeStr :: CString -> ImVec2 -> ImGuiCond -> IO ()
imGui_SetWindowSizeStr name size cond =
  with size $ \_p1 -> c_imGui_SetWindowSizeStr name _p1 cond

-- C: bool ImGui::Shortcut(ImGuiKeyChord key_chord, ImGuiInputFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_Shortcut"
  imGui_Shortcut :: ImGuiKeyChord -> ImGuiInputFlags -> IO CBool
-- C: void ImGui::ShowAboutWindow(bool* p_open)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_ShowAboutWindow"
  imGui_ShowAboutWindow :: (Ptr CBool) -> IO ()
-- C: void ImGui::ShowDebugLogWindow(bool* p_open)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_ShowDebugLogWindow"
  imGui_ShowDebugLogWindow :: (Ptr CBool) -> IO ()
-- C: void ImGui::ShowDemoWindow(bool* p_open)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_ShowDemoWindow"
  imGui_ShowDemoWindow :: (Ptr CBool) -> IO ()
-- C: void ImGui::ShowFontSelector(const char* label)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_ShowFontSelector"
  imGui_ShowFontSelector :: CString -> IO ()
-- C: void ImGui::ShowIDStackToolWindow(bool* p_open)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_ShowIDStackToolWindow"
  imGui_ShowIDStackToolWindow :: (Ptr CBool) -> IO ()
-- C: void ImGui::ShowMetricsWindow(bool* p_open)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_ShowMetricsWindow"
  imGui_ShowMetricsWindow :: (Ptr CBool) -> IO ()
-- C: void ImGui::ShowStyleEditor(ImGuiStyle* ref)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_ShowStyleEditor"
  imGui_ShowStyleEditor :: (Ptr ImGuiStyle) -> IO ()
-- C: bool ImGui::ShowStyleSelector(const char* label)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_ShowStyleSelector"
  imGui_ShowStyleSelector :: CString -> IO CBool
-- C: void ImGui::ShowUserGuide()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_ShowUserGuide"
  imGui_ShowUserGuide :: IO ()
-- C: bool ImGui::SliderAngle(const char* label, float* v_rad, float v_degrees_min, float v_degrees_max, const char* format, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SliderAngle"
  imGui_SliderAngle :: CString -> (Ptr CFloat) -> CFloat -> CFloat -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::SliderFloat(const char* label, float* v, float v_min, float v_max, const char* format, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SliderFloat"
  imGui_SliderFloat :: CString -> (Ptr CFloat) -> CFloat -> CFloat -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::SliderFloat2(const char* label, float[2] v, float v_min, float v_max, const char* format, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SliderFloat2"
  imGui_SliderFloat2 :: CString -> (Ptr CFloat) -> CFloat -> CFloat -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::SliderFloat3(const char* label, float[3] v, float v_min, float v_max, const char* format, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SliderFloat3"
  imGui_SliderFloat3 :: CString -> (Ptr CFloat) -> CFloat -> CFloat -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::SliderFloat4(const char* label, float[4] v, float v_min, float v_max, const char* format, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SliderFloat4"
  imGui_SliderFloat4 :: CString -> (Ptr CFloat) -> CFloat -> CFloat -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::SliderInt(const char* label, int* v, int v_min, int v_max, const char* format, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SliderInt"
  imGui_SliderInt :: CString -> (Ptr CInt) -> CInt -> CInt -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::SliderInt2(const char* label, int[2] v, int v_min, int v_max, const char* format, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SliderInt2"
  imGui_SliderInt2 :: CString -> (Ptr CInt) -> CInt -> CInt -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::SliderInt3(const char* label, int[3] v, int v_min, int v_max, const char* format, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SliderInt3"
  imGui_SliderInt3 :: CString -> (Ptr CInt) -> CInt -> CInt -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::SliderInt4(const char* label, int[4] v, int v_min, int v_max, const char* format, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SliderInt4"
  imGui_SliderInt4 :: CString -> (Ptr CInt) -> CInt -> CInt -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::SliderScalar(const char* label, ImGuiDataType data_type, void* p_data, const void* p_min, const void* p_max, const char* format, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SliderScalar"
  imGui_SliderScalar :: CString -> ImGuiDataType -> (Ptr ()) -> (Ptr ()) -> (Ptr ()) -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::SliderScalarN(const char* label, ImGuiDataType data_type, void* p_data, int components, const void* p_min, const void* p_max, const char* format, ImGuiSliderFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SliderScalarN"
  imGui_SliderScalarN :: CString -> ImGuiDataType -> (Ptr ()) -> CInt -> (Ptr ()) -> (Ptr ()) -> CString -> ImGuiSliderFlags -> IO CBool
-- C: bool ImGui::SmallButton(const char* label)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_SmallButton"
  imGui_SmallButton :: CString -> IO CBool
-- C: void ImGui::Spacing()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_Spacing"
  imGui_Spacing :: IO ()
-- C: void ImGui::StyleColorsClassic(ImGuiStyle* dst)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_StyleColorsClassic"
  imGui_StyleColorsClassic :: (Ptr ImGuiStyle) -> IO ()
-- C: void ImGui::StyleColorsDark(ImGuiStyle* dst)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_StyleColorsDark"
  imGui_StyleColorsDark :: (Ptr ImGuiStyle) -> IO ()
-- C: void ImGui::StyleColorsLight(ImGuiStyle* dst)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_StyleColorsLight"
  imGui_StyleColorsLight :: (Ptr ImGuiStyle) -> IO ()
-- C: bool ImGui::TabItemButton(const char* label, ImGuiTabItemFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TabItemButton"
  imGui_TabItemButton :: CString -> ImGuiTabItemFlags -> IO CBool
-- C: void ImGui::TableAngledHeadersRow()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TableAngledHeadersRow"
  imGui_TableAngledHeadersRow :: IO ()
-- C: int ImGui::TableGetColumnCount()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TableGetColumnCount"
  imGui_TableGetColumnCount :: IO CInt
-- C: ImGuiTableColumnFlags ImGui::TableGetColumnFlags(int column_n)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TableGetColumnFlags"
  imGui_TableGetColumnFlags :: CInt -> IO ImGuiTableColumnFlags
-- C: int ImGui::TableGetColumnIndex()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TableGetColumnIndex"
  imGui_TableGetColumnIndex :: IO CInt
-- C: const char* ImGui::TableGetColumnName(int column_n)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TableGetColumnName"
  imGui_TableGetColumnName :: CInt -> IO CString
-- C: int ImGui::TableGetHoveredColumn()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TableGetHoveredColumn"
  imGui_TableGetHoveredColumn :: IO CInt
-- C: int ImGui::TableGetRowIndex()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TableGetRowIndex"
  imGui_TableGetRowIndex :: IO CInt
-- C: ImGuiTableSortSpecs* ImGui::TableGetSortSpecs()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TableGetSortSpecs"
  imGui_TableGetSortSpecs :: IO (Ptr ImGuiTableSortSpecs)
-- C: void ImGui::TableHeader(const char* label)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TableHeader"
  imGui_TableHeader :: CString -> IO ()
-- C: void ImGui::TableHeadersRow()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TableHeadersRow"
  imGui_TableHeadersRow :: IO ()
-- C: bool ImGui::TableNextColumn()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TableNextColumn"
  imGui_TableNextColumn :: IO CBool
-- C: void ImGui::TableNextRow(ImGuiTableRowFlags row_flags, float min_row_height)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TableNextRow"
  imGui_TableNextRow :: ImGuiTableRowFlags -> CFloat -> IO ()
-- C: void ImGui::TableSetBgColor(ImGuiTableBgTarget target, ImU32 color, int column_n)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TableSetBgColor"
  imGui_TableSetBgColor :: ImGuiTableBgTarget -> ImU32 -> CInt -> IO ()
-- C: void ImGui::TableSetColumnEnabled(int column_n, bool v)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TableSetColumnEnabled"
  imGui_TableSetColumnEnabled :: CInt -> CBool -> IO ()
-- C: bool ImGui::TableSetColumnIndex(int column_n)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TableSetColumnIndex"
  imGui_TableSetColumnIndex :: CInt -> IO CBool
-- C: void ImGui::TableSetupColumn(const char* label, ImGuiTableColumnFlags flags, float init_width_or_weight, ImGuiID user_id)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TableSetupColumn"
  imGui_TableSetupColumn :: CString -> ImGuiTableColumnFlags -> CFloat -> ImGuiID -> IO ()
-- C: void ImGui::TableSetupScrollFreeze(int cols, int rows)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TableSetupScrollFreeze"
  imGui_TableSetupScrollFreeze :: CInt -> CInt -> IO ()
-- C: bool ImGui::TextLink(const char* label)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TextLink"
  imGui_TextLink :: CString -> IO CBool
-- C: bool ImGui::TextLinkOpenURL(const char* label, const char* url)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TextLinkOpenURL"
  imGui_TextLinkOpenURL :: CString -> CString -> IO CBool
-- C: void ImGui::TextUnformatted(const char* text, const char* text_end)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TextUnformatted"
  imGui_TextUnformatted :: CString -> CString -> IO ()
-- C: bool ImGui::TreeNode(const char* label)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TreeNode"
  imGui_TreeNode :: CString -> IO CBool
-- C: bool ImGui::TreeNodeEx(const char* label, ImGuiTreeNodeFlags flags)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TreeNodeEx"
  imGui_TreeNodeEx :: CString -> ImGuiTreeNodeFlags -> IO CBool
-- C: bool ImGui::TreeNodeGetOpen(ImGuiID storage_id)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TreeNodeGetOpen"
  imGui_TreeNodeGetOpen :: ImGuiID -> IO CBool
-- C: void ImGui::TreePop()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TreePop"
  imGui_TreePop :: IO ()
-- C: void ImGui::TreePush(const char* str_id)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TreePush"
  imGui_TreePush :: CString -> IO ()
-- C: void ImGui::TreePush(const void* ptr_id)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_TreePushPtr"
  imGui_TreePushPtr :: (Ptr ()) -> IO ()
-- C: void ImGui::Unindent(float indent_w)
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_Unindent"
  imGui_Unindent :: CFloat -> IO ()
-- C: void ImGui::UpdatePlatformWindows()
foreign import capi unsafe "dcimgui_nodefaultargfunctions.h ImGui_UpdatePlatformWindows"
  imGui_UpdatePlatformWindows :: IO ()
foreign import capi unsafe "DearImGuiWrappers.h ImGui_VSliderFloat_wrap"
  c_imGui_VSliderFloat :: CString -> (Ptr ImVec2) -> (Ptr CFloat) -> CFloat -> CFloat -> CString -> ImGuiSliderFlags -> IO CBool

imGui_VSliderFloat :: CString -> ImVec2 -> (Ptr CFloat) -> CFloat -> CFloat -> CString -> ImGuiSliderFlags -> IO CBool
imGui_VSliderFloat label size v v_min v_max format flags =
  with size $ \_p1 -> c_imGui_VSliderFloat label _p1 v v_min v_max format flags

foreign import capi unsafe "DearImGuiWrappers.h ImGui_VSliderInt_wrap"
  c_imGui_VSliderInt :: CString -> (Ptr ImVec2) -> (Ptr CInt) -> CInt -> CInt -> CString -> ImGuiSliderFlags -> IO CBool

imGui_VSliderInt :: CString -> ImVec2 -> (Ptr CInt) -> CInt -> CInt -> CString -> ImGuiSliderFlags -> IO CBool
imGui_VSliderInt label size v v_min v_max format flags =
  with size $ \_p1 -> c_imGui_VSliderInt label _p1 v v_min v_max format flags

foreign import capi unsafe "DearImGuiWrappers.h ImGui_VSliderScalar_wrap"
  c_imGui_VSliderScalar :: CString -> (Ptr ImVec2) -> ImGuiDataType -> (Ptr ()) -> (Ptr ()) -> (Ptr ()) -> CString -> ImGuiSliderFlags -> IO CBool

imGui_VSliderScalar :: CString -> ImVec2 -> ImGuiDataType -> (Ptr ()) -> (Ptr ()) -> (Ptr ()) -> CString -> ImGuiSliderFlags -> IO CBool
imGui_VSliderScalar label size data_type p_data p_min p_max format flags =
  with size $ \_p1 -> c_imGui_VSliderScalar label _p1 data_type p_data p_min p_max format flags

