{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- This file was generated by dear-bindings-ffi. Do not edit by hand.
-- Haskell function names: lower the first character of the C name.
-- e.g. ImGui_Begin -> imGui_Begin

module DearImGui.Raw.Impl.GLFW where

import Foreign.C.String (CString)
import Foreign.C.Types
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Utils (with)
import Foreign.Ptr (FunPtr, Ptr)
import Foreign.Storable (Storable (..))
import Data.Int (Int8, Int16, Int32, Int64)
import Data.Word (Word8, Word16, Word32, Word64)
import DearImGui.Raw.Types
import DearImGui.Raw.Impl.GLFW.Types

#include "dcimgui_impl_glfw.h"

-- functions

-- C: void ImGui_ImplGlfw_CharCallback(GLFWwindow* window, unsigned int c)
foreign import capi unsafe "dcimgui_impl_glfw.h cImGui_ImplGlfw_CharCallback"
  cImGui_ImplGlfw_CharCallback :: (Ptr GLFWwindow) -> CUInt -> IO ()
-- C: void ImGui_ImplGlfw_CursorEnterCallback(GLFWwindow* window, int entered)
foreign import capi unsafe "dcimgui_impl_glfw.h cImGui_ImplGlfw_CursorEnterCallback"
  cImGui_ImplGlfw_CursorEnterCallback :: (Ptr GLFWwindow) -> CInt -> IO ()
-- C: void ImGui_ImplGlfw_CursorPosCallback(GLFWwindow* window, double x, double y)
foreign import capi unsafe "dcimgui_impl_glfw.h cImGui_ImplGlfw_CursorPosCallback"
  cImGui_ImplGlfw_CursorPosCallback :: (Ptr GLFWwindow) -> CDouble -> CDouble -> IO ()
-- C: float ImGui_ImplGlfw_GetContentScaleForMonitor(GLFWmonitor* monitor)
foreign import capi unsafe "dcimgui_impl_glfw.h cImGui_ImplGlfw_GetContentScaleForMonitor"
  cImGui_ImplGlfw_GetContentScaleForMonitor :: (Ptr GLFWmonitor) -> IO CFloat
-- C: float ImGui_ImplGlfw_GetContentScaleForWindow(GLFWwindow* window)
foreign import capi unsafe "dcimgui_impl_glfw.h cImGui_ImplGlfw_GetContentScaleForWindow"
  cImGui_ImplGlfw_GetContentScaleForWindow :: (Ptr GLFWwindow) -> IO CFloat
-- C: bool ImGui_ImplGlfw_InitForOpenGL(GLFWwindow* window, bool install_callbacks)
foreign import capi unsafe "dcimgui_impl_glfw.h cImGui_ImplGlfw_InitForOpenGL"
  cImGui_ImplGlfw_InitForOpenGL :: (Ptr GLFWwindow) -> CBool -> IO CBool
-- C: bool ImGui_ImplGlfw_InitForOther(GLFWwindow* window, bool install_callbacks)
foreign import capi unsafe "dcimgui_impl_glfw.h cImGui_ImplGlfw_InitForOther"
  cImGui_ImplGlfw_InitForOther :: (Ptr GLFWwindow) -> CBool -> IO CBool
-- C: bool ImGui_ImplGlfw_InitForVulkan(GLFWwindow* window, bool install_callbacks)
foreign import capi unsafe "dcimgui_impl_glfw.h cImGui_ImplGlfw_InitForVulkan"
  cImGui_ImplGlfw_InitForVulkan :: (Ptr GLFWwindow) -> CBool -> IO CBool
-- C: void ImGui_ImplGlfw_InstallCallbacks(GLFWwindow* window)
foreign import capi unsafe "dcimgui_impl_glfw.h cImGui_ImplGlfw_InstallCallbacks"
  cImGui_ImplGlfw_InstallCallbacks :: (Ptr GLFWwindow) -> IO ()
-- C: void ImGui_ImplGlfw_KeyCallback(GLFWwindow* window, int key, int scancode, int action, int mods)
foreign import capi unsafe "dcimgui_impl_glfw.h cImGui_ImplGlfw_KeyCallback"
  cImGui_ImplGlfw_KeyCallback :: (Ptr GLFWwindow) -> CInt -> CInt -> CInt -> CInt -> IO ()
-- C: void ImGui_ImplGlfw_MonitorCallback(GLFWmonitor* monitor, int event)
foreign import capi unsafe "dcimgui_impl_glfw.h cImGui_ImplGlfw_MonitorCallback"
  cImGui_ImplGlfw_MonitorCallback :: (Ptr GLFWmonitor) -> CInt -> IO ()
-- C: void ImGui_ImplGlfw_MouseButtonCallback(GLFWwindow* window, int button, int action, int mods)
foreign import capi unsafe "dcimgui_impl_glfw.h cImGui_ImplGlfw_MouseButtonCallback"
  cImGui_ImplGlfw_MouseButtonCallback :: (Ptr GLFWwindow) -> CInt -> CInt -> CInt -> IO ()
-- C: void ImGui_ImplGlfw_NewFrame()
foreign import capi unsafe "dcimgui_impl_glfw.h cImGui_ImplGlfw_NewFrame"
  cImGui_ImplGlfw_NewFrame :: IO ()
-- C: void ImGui_ImplGlfw_RestoreCallbacks(GLFWwindow* window)
foreign import capi unsafe "dcimgui_impl_glfw.h cImGui_ImplGlfw_RestoreCallbacks"
  cImGui_ImplGlfw_RestoreCallbacks :: (Ptr GLFWwindow) -> IO ()
-- C: void ImGui_ImplGlfw_ScrollCallback(GLFWwindow* window, double xoffset, double yoffset)
foreign import capi unsafe "dcimgui_impl_glfw.h cImGui_ImplGlfw_ScrollCallback"
  cImGui_ImplGlfw_ScrollCallback :: (Ptr GLFWwindow) -> CDouble -> CDouble -> IO ()
-- C: void ImGui_ImplGlfw_SetCallbacksChainForAllWindows(bool chain_for_all_windows)
foreign import capi unsafe "dcimgui_impl_glfw.h cImGui_ImplGlfw_SetCallbacksChainForAllWindows"
  cImGui_ImplGlfw_SetCallbacksChainForAllWindows :: CBool -> IO ()
-- C: void ImGui_ImplGlfw_Shutdown()
foreign import capi unsafe "dcimgui_impl_glfw.h cImGui_ImplGlfw_Shutdown"
  cImGui_ImplGlfw_Shutdown :: IO ()
-- C: void ImGui_ImplGlfw_Sleep(int milliseconds)
foreign import capi unsafe "dcimgui_impl_glfw.h cImGui_ImplGlfw_Sleep"
  cImGui_ImplGlfw_Sleep :: CInt -> IO ()
-- C: void ImGui_ImplGlfw_WindowFocusCallback(GLFWwindow* window, int focused)
foreign import capi unsafe "dcimgui_impl_glfw.h cImGui_ImplGlfw_WindowFocusCallback"
  cImGui_ImplGlfw_WindowFocusCallback :: (Ptr GLFWwindow) -> CInt -> IO ()
